package org.upyog.dashboard.entity;
import org.upyog.dashboard.common.constants.DashboardConstants;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * Data-transfer / entity object that represents a single <em>legacy</em> ingestion
 * record persisted in the {@code legacy_data_ingestion_detail} PostgreSQL table.
 *
 * <p>Legacy ingestion covers historical data that was not originally ingested
 * through the regular daily pipeline.  Each record corresponds to one
 * calendar <em>month</em> of data for a given ULB-module combination, as opposed
 * to the day-level granularity used by {@link DailyIngestionData}.
 *
 * <h3>Kafka flow</h3>
 * <ol>
 *   <li>The legacy scheduler or retry mechanism builds an instance of this class
 *       after each HTTP push attempt.</li>
 *   <li>For a new record the instance is wrapped under the key
 *       {@code "legacyIngestionData"} and pushed to the
 *       {@code save-adapter-module-ingestion-detail} topic via
 *       {@link org.upyog.dashboard.producer.DashboardProducer}.</li>
 *   <li>For updates to an existing record (e.g. status change after a retry)
 *       the same wrapper is published to the
 *       {@code update-adapter-module-ingestion-detail} topic.</li>
 *   <li>The persister service consumes each topic and executes the
 *       corresponding INSERT / UPDATE statement defined in
 *       {@code adapter-service-persister.yml}.</li>
 * </ol>
 *
 * <h3>Table mapping</h3>
 * <pre>
 * Java field            DB column
 * ──────────────────    ──────────────────────────────────
 * moduleIngestionId  →  module_ingestion_id  (PK, VARCHAR 64)
 * moduleDetailId     →  module_detail_id     (FK → module_ingestion_detail.detail_id)
 * tenantId           →  tenant_id
 * ulbName            →  ulb_name
 * moduleName         →  module_name
 * pushMonth          →  push_month           (DATE, first day of the month)
 * userId             →  user_id
 * requestData        →  request_data         (JSONB)
 * responseData       →  response_data        (JSONB)
 * ingestionStatus    →  ingestion_status     (default NOT_STARTED in DB)
 * createdBy          →  created_by
 * createdTime        →  created_time         (epoch millis)
 * lastModifiedBy     →  last_modified_by
 * lastModifiedTime   →  last_modified_time   (epoch millis)
 * </pre>
 *
 * @see org.upyog.dashboard.entity.DailyIngestionData
 * @see org.upyog.dashboard.producer.DashboardProducer
 */
/**
 * Class representing the LegacyIngestionData class.
 * 
 * <p>Contributes to the core Property Tax metrics ingestion pipeline.
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
public class LegacyIngestionData {

    /**
     * Universally unique identifier for this legacy ingestion attempt.
     * Generated by the application layer (e.g. {@link java.util.UUID#randomUUID()})
     * before the record is published to Kafka.
     * Maps to {@code legacy_data_ingestion_detail.module_ingestion_id} (primary key).
     */
    private String moduleIngestionId;

    /**
     * Foreign key that links this record to the parent
     * {@code module_ingestion_detail} row which holds the ULB-module
     * configuration including the legacy migration flag and last migration date.
     * Maps to {@code legacy_data_ingestion_detail.module_detail_id}.
     */
    private String moduleDetailId;

    /**
     * tenant identifier for the ULB whose historical data was pushed.
     * Typically matches the ULB code (e.g. {@code pb.amritsar}).
     * Maps to {@code legacy_data_ingestion_detail.tenant_id}.
     */
    private String tenantId;

    /**
     * Human-readable name of the Urban Local Body (ULB) whose legacy data
     * was ingested.
     * Maps to {@code legacy_data_ingestion_detail.ulb_name}.
     */
    private String ulbName;

    /**
     * Short code identifying the module that was ingested
     * (e.g. {@code PT}, {@code TL}, {@code FSM}).
     * Maps to {@code legacy_data_ingestion_detail.module_name}.
     */
    private String moduleName;

    /**
     * The calendar date for which legacy data was pushed,
     * expressed as an ISO date string in {@code yyyy-MM-dd} format.
     * Maps to {@code legacy_data_ingestion_detail.push_date}.
     */
    private String pushDate;

    /**
     * Start date for legacy ingestion range (e.g. 01-01-2024).
     * Maps to legacy_data_ingestion_detail.start_date.
     */
    private String startDate;

    /**
     * End date for legacy ingestion range (e.g. 31-01-2026).
     * Maps to legacy_data_ingestion_detail.end_date.
     */
    private String endDate;

    /**
     * Identifier of the system or human user that triggered the legacy
     * ingestion.  May be {@code null} when the push originates from a
     * scheduled background job.
     * Maps to {@code legacy_data_ingestion_detail.user_id}.
     */
    private String userId;

    /**
     * Full JSON string of the {@link org.upyog.dashboard.model.NationalDashboardIngestRequest}
     * that was serialized and sent to the national dashboard endpoint.
     * Stored as {@code JSONB} in the database.
     * Maps to {@code legacy_data_ingestion_detail.request_data}.
     */
    private String requestData;

    /**
     * Full JSON string of the HTTP response body returned by the national
     * dashboard endpoint on success, or the exception message on failure.
     * Stored as {@code JSONB} in the database.
     * Maps to {@code legacy_data_ingestion_detail.response_data}.
     */
    private String responseData;

    /**
     * Terminal outcome of the legacy ingestion attempt.
     * <ul>
     *   <li>{@code NOT_STARTED} — default DB value; the row has been created but
     *       no push has been attempted yet.</li>
     *   <li>{@code SUCCESS} — the national dashboard endpoint returned HTTP 2xx.</li>
     *   <li>{@code FAILURE} — an exception was thrown or a non-2xx status was received.</li>
     * </ul>
     * Maps to {@code legacy_data_ingestion_detail.ingestion_status}.
     */
    private String ingestionStatus;

    /**
     * Optional code representing the specific type of failure, if applicable.
     */
    private String exceptionCode;

    /**
     * Identity of the process or user that created this record.
     * Defaults to {@code DashboardConstants.SYSTEM_USER} for scheduler-originated records.
     * Maps to {@code legacy_data_ingestion_detail.created_by}.
     */
    private String createdBy;

    /**
     * Unix epoch timestamp (milliseconds) at which this record was created.
     * Maps to {@code legacy_data_ingestion_detail.created_time}.
     */
    private Long createdTime;

    /**
     * Identity of the process or user that last updated this record.
     * Maps to {@code legacy_data_ingestion_detail.last_modified_by}.
     */
    private String lastModifiedBy;

    /**
     * Unix epoch timestamp (milliseconds) of the most recent update.
     * Maps to {@code legacy_data_ingestion_detail.last_modified_time}.
     */
    private Long lastModifiedTime;
}
