spring.application.name=adapter-service

server.context-path=/adapter-services
server.servlet.context-path=/adapter-services
server.port=9999
app.timezone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ec2-13-203-111-246.ap-south-1.compute.amazonaws.com:5432/niuatt
spring.datasource.username=niuatt_read
spring.datasource.password=z3gzzOQGyDlrxkwz

spring.flyway.url=jdbc:postgresql://ec2-13-203-111-246.ap-south-1.compute.amazonaws.com:5432/niuatt
spring.flyway.user=niuatt_read
spring.flyway.password=z3gzzOQGyDlrxkwz
spring.flyway.table=chb_schema_version
spring.flyway.baseline-on-migrate=true
spring.flyway.outOfOrder=true
spring.flyway.locations=classpath:/db/migration/main
spring.flyway.enabled=false

egov.mdms.host=http://egov-mdms-service:8080/
egov.mdms.search.endpoint=egov-mdms-service/v1/_search
upyog.mdms.v2.host=http://mdms-v2.egov:8080/
upyog.mdms.v2.search.endpoint=mdms-v2/v1/_search
upyog.mdms.v2.enabled=false

egov.user.host=http://egov-user:8080/
egov.user.context.path=user/users/
egov.user.create.path=_createnovalidate
egov.user.search.path=user/_search
egov.user.update.path=_updatenovalidate

as.module.name=adapter-service
as.business.service.name=adapter-services

egov.enc.host=http://egov-enc-service.egov:8080/
egov.enc.encrypt.endpoint=egov-enc-service/crypto/v1/_encrypt
egov.enc.decypt.endpoint =egov-enc-service/crypto/v1/_decrypt

state.level.tenant.id=pg

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

national.dashboard.ingest.url=https://niuatt.niua.in/national-dashboard/metric/_ingest

egov.user.oauth.host=https://niuatt.niua.in
egov.user.oauth.path=/user/oauth/token?_=1783573693774
egov.user.oauth.basic.auth=Basic ZWdvdi11c2VyLWNsaWVudDo=
adapter.system.user.username=NDS1
adapter.system.user.password=eGov@123
adapter.system.user.tenantId=pg
adapter.system.user.type=EMPLOYEE
employee.allowed.search.params=uuid,userName,mobileNumber
egov.user.host=https://niuatt.niua.in
egov.user.search.path=/user/_search