ALTER TABLE INDIVIDUAL_IDENTIFIER DROP COLUMN IF EXISTS id;
ALTER TABLE INDIVIDUAL_IDENTIFIER DROP CONSTRAINT IF EXISTS uk_individual_identifier_mapping;
ALTER TABLE INDIVIDUAL_IDENTIFIER
    ADD CONSTRAINT uk_individual_identifier_mapping UNIQUE(individualId, identifierType);