ALTER TABLE INDIVIDUAL_IDENTIFIER ADD COLUMN clientReferenceId character varying(64) UNIQUE;
ALTER TABLE ADDRESS ADD COLUMN IF NOT EXISTS clientReferenceId character varying(64) UNIQUE;
ALTER TABLE INDIVIDUAL_SKILL ADD COLUMN clientReferenceId character varying(64) UNIQUE;