package org.upyog.adapter.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data-transfer / entity object that represents a single <em>daily</em> ingestion
 * record persisted in the {@code ingestion_detail} PostgreSQL table.
 *
 * <p>One row is created for every attempt to push a module's daily data to the
 * National Dashboard ingest endpoint, regardless of whether the attempt succeeds
 * or fails.  The record captures the full request and response payloads as JSONB
 * so that failures can be diagnosed and retried without re-fetching source data.
 *
 * <h3>Kafka flow</h3>
 * <ol>
 *   <li>{@link org.upyog.adapter.loader.impl.HttpLoader} builds an instance of this
 *       class after each HTTP call.</li>
 *   <li>The instance is wrapped in a {@code Map} under the key
 *       {@code "dailyIngestionData"} and pushed to the
 *       {@code save-adapter-ingestion-detail} topic via
 *       {@link org.upyog.adapter.producer.AdapterProducer}.</li>
 *   <li>The DIGIT persister service consumes the topic and executes the INSERT
 *       statement defined in {@code adapter-service-persister.yml}.</li>
 * </ol>
 *
 * <h3>Table mapping</h3>
 * <pre>
 * Java field            DB column
 * ──────────────────    ──────────────────────
 * moduleIngestionId  →  module_ingestion_id  (PK, VARCHAR 64)
 * moduleDetailId     →  module_detail_id     (FK → module_ingestion_detail.detail_id)
 * tenantId           →  tenant_id
 * ulbName            →  ulb_name
 * moduleName         →  module_name
 * pushDate           →  push_date            (DATE, stored via TO_DATE)
 * userId             →  user_id
 * requestData        →  request_data         (JSONB)
 * responseData       →  response_data        (JSONB)
 * ingestionStatus    →  ingestion_status
 * createdBy          →  created_by
 * createdTime        →  created_time         (epoch millis)
 * lastModifiedBy     →  last_modified_by
 * lastModifiedTime   →  last_modified_time   (epoch millis)
 * </pre>
 *
 * @see org.upyog.adapter.entity.LegacyIngestionData
 * @see org.upyog.adapter.loader.impl.HttpLoader
 * @see org.upyog.adapter.producer.AdapterProducer
 */
/**
 * Class representing the DailyIngestionData class.
 * 
 * <p>Contributes to the core Property Tax metrics ingestion pipeline.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DailyIngestionData {

    /**
     * Universally unique identifier for this ingestion attempt.
     * Generated by the application layer (e.g. {@link java.util.UUID#randomUUID()})
     * before the record is published to Kafka.
     * Maps to {@code ingestion_detail.module_ingestion_id} (primary key).
     */
    private String moduleIngestionId;

    /**
     * Foreign key that links this record to the parent
     * {@code module_ingestion_detail} row which describes the ULB-module
     * configuration (schedules, legacy migration flags, etc.).
     * Maps to {@code ingestion_detail.module_detail_id}.
     *
     * <p>This field is intentionally left {@code null} inside
     * {@link org.upyog.adapter.loader.impl.HttpLoader} and must be populated
     * by the higher-level service layer that owns the
     * {@code module_ingestion_detail} FK relationship.
     */
    private String moduleDetailId;

    /**
     * DIGIT tenant identifier for the ULB whose data was pushed.
     * Typically matches the ULB code (e.g. {@code pb.amritsar}).
     * Maps to {@code ingestion_detail.tenant_id}.
     */
    private String tenantId;

    /**
     * Short code identifying the DIGIT module that was ingested
     * (e.g. {@code PT}, {@code TL}, {@code FSM}).
     * Derived from {@link org.upyog.adapter.model.DashboardData#getModule()}.
     * Maps to {@code ingestion_detail.module_name}.
     */
    private String moduleName;

    /**
     * Calendar date for which the module data was pushed, in
     * {@code yyyy-MM-dd} format.  The persister converts this to a PostgreSQL
     * {@code DATE} type using {@code TO_DATE(?, 'YYYY-MM-DD')}.
     * Maps to {@code ingestion_detail.push_date}.
     */
    private String pushDate;

    /**
     * Full JSON string of the {@link org.upyog.adapter.model.NationalDashboardIngestRequest}
     * that was serialized and sent to the national dashboard endpoint.
     * Stored as {@code JSONB} in the database to allow querying individual
     * request fields without re-parsing.
     * Maps to {@code ingestion_detail.request_data}.
     */
    private String requestData;

    /**
     * Full JSON string of the HTTP response body returned by the national
     * dashboard endpoint on success, or the exception message on failure.
     * Stored as {@code JSONB} in the database.
     * Maps to {@code ingestion_detail.response_data}.
     */
    private String responseData;

    /**
     * Terminal outcome of the ingestion attempt.
     * <ul>
     *   <li>{@code SUCCESS} — the national dashboard endpoint returned HTTP 2xx.</li>
     *   <li>{@code FAILURE} — an exception was thrown or a non-2xx status was received.</li>
     * </ul>
     * Maps to {@code ingestion_detail.ingestion_status}.
     */
    private String ingestionStatus;

    /**
     * Optional code representing the specific type of failure, if applicable.
     */
    private String exceptionCode;

    /**
     * Identity of the process or user that created this record.
     * Defaults to {@code "SYSTEM"} when the record originates from a
     * scheduled background job.
     * Maps to {@code ingestion_detail.created_by}.
     */
    private String createdBy;

    /**
     * Unix epoch timestamp (milliseconds) at which this record was created.
     * Maps to {@code ingestion_detail.created_time}.
     */
    private Long createdTime;

    /**
     * Identity of the process or user that last updated this record.
     * Maps to {@code ingestion_detail.last_modified_by}.
     */
    private String lastModifiedBy;

    /**
     * Unix epoch timestamp (milliseconds) of the most recent update.
     * Maps to {@code ingestion_detail.last_modified_time}.
     */
    private Long lastModifiedTime;
}
