package org.egov.common.entity.edcr;

import java.io.File;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Transient;

import org.egov.edcr.entity.PdfPageSize;

public class EdcrPdfDetail implements Serializable {

    private static final long serialVersionUID = 63L;

    private String layer;

    @Transient
    private File convertedPdf;

    private String failureReasons;

    private String standardViolations;

    private List<String> violations;

    @Transient
    private List<String> layers;
    @Transient
    private PdfPageSize pageSize;
    @Transient
    private List<String> measurementLayers = new ArrayList<>();
    @Transient
    private List<String> dimensionLayers = new ArrayList<>();
    @Transient
    private List<String> printNameLayers = new ArrayList<>();

    @Transient
    private Map<String, Integer> colorOverrides = new HashMap<>();
    @Transient
    private Map<String, Integer> thicknessOverrides = new HashMap<>();

    /**
     * Indicates that this configuration represents the single page PDF
     * generated by Kabeja.
     *
     * <p>This flag is set only on the synthetic configuration row created by
     * {@code DxfToPdfConverterExtract} when legacy sheet mode is disabled
     * ({@code DcrConstants.DXF_TO_PDF_USE_LEGACY_LAYER_SHEETS = false}).
     * When enabled, {@code DxfToPdfUnifiedConverter} applies single-PDF specific
     * generator settings, including {@code DcrSvgGenerator.PROPERTY_SINGLE_PDF},
     * and configures drawing bounds, margins, stroke rendering, text handling,
     * and font settings accordingly.</p>
     *
     * <p>When {@code null} or {@code false}, the converter falls back to the
     * legacy multi-sheet PDF generation flow and uses the standard layer-based
     * property configuration.</p>
     *
     * <p>This flag must not be enabled for configurations loaded from MDMS
     * ({@code DxfToPdfLayerConfig}) or from the {@code EDCR_DXF_PDF}
     * application configuration.</p>
     */
    @Transient
    private Boolean kabejaSinglePageDXFToPdf;

    private String downloadURL;

    public String getLayer() {
        return layer;
    }

    public void setLayer(String layer) {
        this.layer = layer;
    }

    public File getConvertedPdf() {
        return convertedPdf;
    }

    public void setConvertedPdf(File convertedPdf) {
        this.convertedPdf = convertedPdf;
    }

    public String getFailureReasons() {
        return failureReasons;
    }

    public void setFailureReasons(String failureReasons) {
        this.failureReasons = failureReasons;
    }

    public String getStandardViolations() {
        return standardViolations;
    }

    public void setStandardViolations(String standardViolations) {
        this.standardViolations = standardViolations;
    }

    public List<String> getViolations() {
        return violations;
    }

    public void setViolations(List<String> violations) {
        this.violations = violations;
    }

    public List<String> getLayers() {
        return layers;
    }

    public void setLayers(List<String> layers) {
        this.layers = layers;
    }

    public PdfPageSize getPageSize() {
        return pageSize;
    }

    public void setPageSize(PdfPageSize pageSize) {
        this.pageSize = pageSize;
    }

    public List<String> getMeasurementLayers() {
        return measurementLayers;
    }

    public void setMeasurementLayers(List<String> measurementLayers) {
        this.measurementLayers = measurementLayers;
    }

    public List<String> getDimensionLayers() {
        return dimensionLayers;
    }

    public void setDimensionLayers(List<String> dimensionLayers) {
        this.dimensionLayers = dimensionLayers;
    }

    public List<String> getPrintNameLayers() {
        return printNameLayers;
    }

    public void setPrintNameLayers(List<String> printNameLayers) {
        this.printNameLayers = printNameLayers;
    }

    public Map<String, Integer> getColorOverrides() {
        return colorOverrides;
    }

    public void setColorOverrides(Map<String, Integer> colorOverrides) {
        this.colorOverrides = colorOverrides;
    }

    public Map<String, Integer> getThicknessOverrides() {
        return thicknessOverrides;
    }

    public void setThicknessOverrides(Map<String, Integer> thicknessOverrides) {
        this.thicknessOverrides = thicknessOverrides;
    }

    public Boolean getKabejaSinglePageDXFToPdf() {
        return kabejaSinglePageDXFToPdf;
    }

    public void setKabejaSinglePageDXFToPdf(Boolean kabejaSinglePageDXFToPdf) {
        this.kabejaSinglePageDXFToPdf = kabejaSinglePageDXFToPdf;
    }

    public String getDownloadURL() {
        return downloadURL;
    }

    public void setDownloadURL(String downloadURL) {
        this.downloadURL = downloadURL;
    }

}
