cmdserver.workDir-path=/egov-pb-digilocker

#rest config
server.port=8080
server.context-path=/pt-services-dx
server.servlet.context-path=/pt-services-dx
logging.level.org.egov=DEBUG

#egov.services.hostname = http://pdf-service:8080
egov.services.hostname = http://localhost:8083
egov.pdf.service.create = /pdf-service/v1/_create

#egov.collectionservice.host=http://localhost:8080
egov.collectionservice.host=https://mseva.lgpunjab.gov.in
egov.payment.search.endpoint=/collection-services/payments/PT/_search


egov.searchservice.host=https://mseva.lgpunjab.gov.in
egov.searchservice.ws.endpoint=/egov-searcher/bill-genie/waterbills/_get
egov.searchservice.sw.endpoint=/egov-searcher/bill-genie/seweragebills/_get

egov.ws.host=https://egov-microservice-dev.org
egov.ws.search.endpoint=/ws-services/wc/_search

egov.sw.host=https://egov-microservice-dev.org
egov.sw.search.endpoint=/sw-services/swc/_search


egov.property.search.host=https://mseva.lgpunjab.gov.in
egov.property.search.endpoint=/property-services/property/_search?tenantId=

#egov.filestore.host=http://localhost:8080
egov.filestore.host=https://mseva.lgpunjab.gov.in
egov.filestore.search.endpoint=/filestore/v1/files/url?tenantId=pb&fileStoreIds=

egov.mdms.host=http://egov-mdms-service:8080
#egov.mdms.host=http://localhost:9874
egov.mdms.search.endpoint=/egov-mdms-service/v1/_search

user.service.host=https://mseva.lgpunjab.gov.in
user.search.endpoint=/user/oauth/token
egov.payer.validation.enable=true

# DigiLocker Specific
egov.digilocker.origin=https://partners.digitallocker.gov.in
egov.digilocker.issuer.id=in.gov.lgpunjab
egov.digilocker.doctype.prtax=PRTAX
egov.pt.language.code=99
egov.pt.issuer.org.name=Punjab Municipal Infrastructure Development Company
egov.pt.issuer.pin=160022
egov.pt.person.state=Punjab

egov.integration.system.user.uuid=3b666f31-92c2-4e74-8122-300494b8e978
