cmdserver.workDir-path=/egov-pb-digilocker

# rest config
server.port=8080
server.context-path=/pt-services-dx
server.servlet.context-path=/pt-services-dx
logging.level.org.egov=DEBUG

# PDF Service (Updated to dev)
egov.services.hostname = https://mseva-dev.lgpunjab.gov.in
egov.pdf.service.create = /pdf-service/v1/_create

# Collection Service (Updated to dev)
egov.collectionservice.host=https://mseva-dev.lgpunjab.gov.in
egov.payment.search.endpoint=/collection-services/payments/PT/_search

# Searcher Service (Updated to dev)
egov.searchservice.host=https://mseva-dev.lgpunjab.gov.in
egov.searchservice.ws.endpoint=/egov-searcher/bill-genie/waterbills/_get
egov.searchservice.sw.endpoint=/egov-searcher/bill-genie/seweragebills/_get

# WS/SW Microservices (Updated to dev)
egov.ws.host=https://mseva-dev.lgpunjab.gov.in
egov.ws.search.endpoint=/ws-services/wc/_search

egov.sw.host=https://mseva-dev.lgpunjab.gov.in
egov.sw.search.endpoint=/sw-services/swc/_search

# Property Search (Updated to dev)
egov.property.search.host=https://mseva-dev.lgpunjab.gov.in
egov.property.search.endpoint=/property-services/property/_search?tenantId=

# Filestore (Updated to dev)
egov.filestore.host=https://mseva-dev.lgpunjab.gov.in
egov.filestore.search.endpoint=/filestore/v1/files/url?tenantId=pb&fileStoreIds=
# Path for local file switch logic
egov.filestore.local-path=/egov-pb-digilocker/filestore

# MDMS (Updated to dev)
egov.mdms.host=https://mseva-dev.lgpunjab.gov.in
egov.mdms.search.endpoint=/egov-mdms-service/v1/_search

# User Service (Updated to dev)
user.service.host=https://mseva-dev.lgpunjab.gov.in
user.search.endpoint=/user/oauth/token
egov.payer.validation.enable=true

# DigiLocker Specific
egov.digilocker.origin=https://partners.digitallocker.gov.in
egov.digilocker.issuer.id=in.gov.lgpunjab
egov.digilocker.doctype.prtax=PRTAX
egov.pt.language.code=99
egov.pt.issuer.org.name=Punjab Municipal Infrastructure Development Company
egov.pt.issuer.pin=160022
egov.pt.person.state=Punjab

egov.integration.system.user.uuid=3b666f31-92c2-4e74-8122-300494b8e978