const { createProxyMiddleware } = require("http-proxy-middleware");

const createProxy = createProxyMiddleware({
  //target: process.env.REACT_APP_PROXY_API || "https://uat.digit.org",
  // target: process.env.REACT_APP_PROXY_API || "https://qa.digit.org",
  target: process.env.REACT_APP_PROXY_API || "https://qa.digit.org",
  changeOrigin: true,
});
const assetsProxy = createProxyMiddleware({
  target: process.env.REACT_APP_PROXY_ASSETS || "https://qa.digit.org",
  changeOrigin: true,
});
module.exports = function (app) {
  [
    "/access/v1/actions/mdms",
    "/egov-mdms-service",
    "/egov-location",
    "/mdms-v2",
    "/localization",
    "/egov-workflow-v2",
    "/pgr-services",
    "/filestore",
    "/egov-hrms",
    "/user-otp",
    "/user",
    "/fsm",
    "/billing-service",
    "/collection-services",
    "/pdf-service",
    "/pg-service",
    "/vehicle",
    "/vendor",
    "/property-services",
    "/fsm-calculator/v1/billingSlab/_search",
    "/pt-calculator-v2",
    "/dashboard-analytics",
    "/echallan-services",
    "/egov-searcher/bill-genie/mcollectbills/_get",
    "/egov-searcher/bill-genie/billswithaddranduser/_get",
    "/egov-searcher/bill-genie/waterbills/_get",
    "/egov-searcher/bill-genie/seweragebills/_get",
    "/egov-pdf/download/UC/mcollect-challan",
    "/egov-hrms/employees/_count",
    "/tl-services/v1/_create",
    "/tl-services/v1/_search",
    "/egov-url-shortening/shortener",
    "/inbox/v1/_search",
    "/tl-services",
    "/tl-calculator",
    "/edcr",
    "/bpa-services",
    "/noc-services",
    "/egov-user-event",
    "/egov-document-uploader",
    "/egov-pdf",
    "/egov-survey-services",
    "/ws-services",
    "/sw-services",
    "/ws-calculator",
    "/sw-calculator/",
    "/egov-searcher",
    "/report",
    "/inbox/v1/dss/_search",
    "/inbox/v1/elastic/_search",
    "/fsm-calculator",
    "/service-request",
    "/pet-services/pet-registration/_create",
    "/pet-services/pet-registration/_search",
    "/pet-services/pet-registration/_update",
    "/sv-services/street-vending/_create",
    "/sv-services/street-vending/_search",
    "/sv-services/street-vending/_update",
    "/sv-services/street-vending/_deletedraft",
    "/ewaste-services/ewaste-request/_create",
    "/ewaste-services/ewaste-request/_search",
    "/ewaste-services/ewaste-request/_update",
    "/chb-services/booking/v1/_create",
    "/chb-services/booking/v1/_search",
    "/chb-services/booking/v1/_update",
    "/chb-services/booking/v1/_slot-search",
    "/chb-services/booking/v1/_estimate",
    "/adv-services/booking/v1/_create", // API to create advertisement bookings
    "/adv-services/booking/v1/_search", // API to search advertisement bookings
    "/adv-services/booking/v1/_update", // API to update advertisement bookings
    "/adv-services/booking/v1/_slot-search", // API to search available slots for advertisement bookings
    "/adv-services/booking/v1/_estimate", // API to estimate costs for advertisement bookings
    "/employee-dashboard/_search",
    "/verification-service/validity/_search",
    "/request-service/water-tanker/v1/_create",
    "/asset-services/v1/assets/_create",
    "/asset-services/v1/assets/_search",
    "/asset-services/v1/assets/_update",
    "/asset-services/v1/assets/assignment/_create",
    "/asset-services/v1/assets/assignment/_update",
    "/asset-services/v1/assets/_search",
    "/asset-services/v1/assets/depreciation/_process",
    "/asset-services/v1/assets/depreciation/list",
    "/asset-services/v1/disposal/_create",
    "/asset-services/maintenance/v1/_create",
    "/asset-services/maintenance/v1/_update",
    "/asset-services/maintenance/v1/_search",
    "/asset-services/v1/disposal/_search",
    "/asset-services/v1/assets/assignment/_search",
    "/request-service/water-tanker/v1/_search",
    "/request-service/water-tanker/v1/_update",
    "/vendor-management/api/v1/_create",
    "/sv-services/street-vending/_createdemand",
    "/request-service/mobile-toilet/v1/_create",
    "/tp-services/tree-pruning/v1/_create",
    "/tp-services/tree-pruning/v1/_search",
    "/tp-services/tree-pruning/v1/_update",
    "/request-service/mobile-toilet/v1/_update",
    "/request-service/mobile-toilet/v1/_search",
    "/vendor-management/api/v1/vendorPlusAdditional/_search",
    "/user/_updateAddress",
    "/pgr-ai-services/v1/request/_create",
    "/pgr-ai-services/v1/request/_search",
    "/pgr-ai-services/v1/request/_update",
    "/individual/v1/_search",
    "/bpa-services/v1/preapprovedplan/_search",
    "/bpa-calculator/_estimate"
  ].forEach((location) => app.use(location, createProxy));
  ["/pb-egov-assets"].forEach((location) => app.use(location, assetsProxy));
};