package org.egov.finance.voucher.enumeration;

public enum VoucherSubTypeEnum {

	JOURNALVOUCHER, CONTRA, RECEIPT, PAYMENT, PURCHASEJOURNAL, PENSIONJOURNAL, PURCHASE, WORKS, CONTRACTORJOURNAL,
	FIXEDASSETJOURNAL, FIXEDASSET, PENSION, WORKSJOURNAL, CONTINGENTJOURNAL, SALARY, SALARYJOURNAL, EXPENSE,
	EXPENSEJOURNAL, JVGENERAL;

}
