spring.application.name=upyog-selenium-tests
server.port=8080
localhost=8080


# Selenium Grid Configuration (for Docker)
#false for local and true for server
selenium.grid.enabled=false
selenium.grid.url=http://selenium-chrome:4444/wd/hub
novnc.url=http://65.0.8.57:8000


# Selenium WebDriver Configuration
chrome.driver.path=/usr/local/bin/chromedriver
webdriver.wait.timeout=30
browser=chrome
timeout.explicit=30
user.mobile=9999999999
user.otp=123456
city.name=Delhi


language.name=English
locality.name=Main Road Abadpura

#EWASTE
applicant.name=Arpit Rao
applicant.email=arpit@gmail.com

address.pincode=143001
address.street=Raj Nagar
address.doorNo=201
address.building=Jagbir Bhawan
address.line1=test address 1
address.line2=test address 2
address.landmark=test landmark

product.quantity=10

# EWaste - Product Page

ewaste.product.dropdown.index=0
ewaste.product.option.index=1

ewaste.input.product.quantity.name=productQuantity

ewaste.button.addProduct.xpath=//button[contains(.,'Add Product')]
ewaste.button.next.xpath=//button[contains(@class,'submit-bar') and .//header[text()='Next']]


# Chrome Browser Options
chrome.option.1=--remote-allow-origins=*
chrome.option.2=--disable-blink-features=AutomationControlled
chrome.option.3=--start-maximized
chrome.option.4=--disable-autofill
chrome.option.5=--disable-autofill-keyboard-accessory-view
chrome.option.6=--disable-full-form-autofill-ios
chrome.option.7=--disable-save-password-bubble

# Chrome Preferences
chrome.prefs.autofill.address_enabled=false
chrome.prefs.autofill.profile_enabled=false

# Test Data Configuration
test.otp=123456
test.city.name=City A Muncipal Corporation
test.cityA.name=Delhi
test.city1.name=mohali

#OBPAS
permit.number=PG-BP-1013-000453

# Application URLs
#employee.base.url=https://upyog-test.niua.org/upyog-ui/employee/user/login
#citizen.base.url=https://upyog-test.niua.org/upyog-ui/citizen/login

#Application sv url
sv.employee.base.url=https://upyog-test.niua.org/sv-ui/employee/user/login
#Application cnd url
cnd.employee.base.url=https://niuatt.niua.in/cnd-ui/employee/user/login

# Login Credentials
app.login.username=PTRCEMP
app.login.password=eGov@123

#TL LOGIN
tl.login.username=TLCE1
tl.login.password=eGov@123

#ADVERTISEMENT LOGIN
adv.login.username=ADS_CEMP
adv.login.password=upyog@123

#ASSET LOGIN
ast.login.username=ASSET_INITIATOR
ast.login.password=upyog@123

#CHB
chb.login.username=CHB2
chb.login.password=upyog@123

#CND
cnd.login.username=CND_SUPERUSER
cnd.login.password=upyog@123

#EWASTE
ewaste.login.username=EWASTE
ewaste.login.password=upyog@123

#OBPAS
obpas.login.username=BPASU1
obpas.login.password=upyog@123

#PROPERTY TAX
property.login.username=PTSU
property.login.password=upyog@123

#PUBLIC GRIEVANCE
pgr.login.username=PGRSU2
pgr.login.password=upyog@123

#REQUEST SERVICE
#Water TAnker
wt.login.username=WTCEMP
wt.login.password=eGov@123

#Mobile Toilet
mt.login.username=MTCEMP
mt.login.password=eGov@123

#Tree Pruning
tp.login.username=TPCEMP
tp.login.password=eGov@123

#WATER AND SEWERAGE
wns.login.username=WSSU2
wns.login.password=upyog@123

citizen.mobile.number=9999999999
architect.mobile.number=7272727216

#VENDOR NUMBER
water.vendor.mobile.number=7033145533
toilet.vendor.mobile.number=9800000000
cnd.mobile.number= 9000000001


#SVLOGIN
sv.login.username=SV_CEMP
SV.login.password=upyogTest@123





# Employee Configuration Application Numbers
tl.application.number=PG-TL-2025-08-18-005174
pet.application.number=PG-PTR-2025-08-18-000117
sv.application.number=SV-1013-000049
ast.application.number=PG-1013-2025-I-001334
adv.application.number=ADV-1013-000153
waterTanker.application.number= WT-1013-001139
mobileToilet.application.number= MT-1013-000017
chb.application.number= CHB-1508-000137
treePruning.application.number= TP-1013-000163
cnd.application.number=CND-1013-000543
pgr.application.number=PG-PGR-2026-04-12-002444
sewerage.application.number=SW_AP/1013/2026-27/000667
water.application.number=WS_AP/1013/2026-27/001387
obpas.application.number=PG-BP-2026-04-10-001344
ewaste.application.number=PG-EW-2026-04-30-000095

# Document Upload Paths
#document.identity.proof=/Users/kaveri/Downloads/doc.pdf
#document.owner.proof=/Users/kaveri/Downloads/owner.pdf
#document.vaccination.cert=/Users/kaveri/Downloads/vaccination.pdf
#document.fitness.cert=/Users/kaveri/Downloads/fitness.pdf
#document.pet.photo=/Users/kaveri/Downloads/deep.png


#document.identity.proof=/home/seluser/doc.pdf
#document.owner.proof=/home/seluser/doc.pdf
#document.vaccination.cert=/home/seluser/doc.pdf
#document.fitness.cert=/home/seluser/doc.pdf
#document.pet.photo=/home/seluser/doc.pdf

#Local
document.identity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.owner.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.vaccination.cert=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.fitness.cert=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.pet.photo=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#Advertisement
#document.sampleDocument.proof=/home/seluser/doc.pdf
#document.address.proof=/home/seluser/doc.pdf
#document.Identity.proof=/home/seluser/doc.pdf

#Advertisement Local
document.sampleDocument.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.address.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.Identity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#TreePruning
#document.site.proof=/home/seluser/doc.pdf

#TreePruning Local
document.site.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#Tl
tl.document.identity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
tl.document.image=/Users/niua-l1232/Downloads/selenium.png

#Property Tax
#document.propertyaddress.proof=/home/seluser/doc.pdf
#document.propertyidentity.proof=/home/seluser/doc.pdf

#Property Tax Local
document.propertyaddress.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.propertyidentity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#Public Grievance Redressal
#document.complaint.proof=/home/seluser/selenium.png

#Public Grievance Redressal Local
document.complaint.proof=/Users/niua-l1232/Downloads/selenium.png

#OBPAS
#document.drawing.dxf=/home/seluser/OBPAS1.dxf
#document.iDentity.proof=/home/seluser/doc.pdf
#document.aDdress.proof=/home/seluser/doc.pdf
#document.landTax.proof=/home/seluser/doc.pdf
#document.titleDeedOfTheProperty.proof=/home/seluser/doc.pdf
#document.layoutApprovalCopy.proof=/home/seluser/doc.pdf
#document.structuralStabilityCertificate.proof=/home/seluser/doc.pdf
#document.locationSketchAndVillageSketch.proof=/home/seluser/doc.pdf
#document.sitePlan.proof=/home/seluser/doc.pdf
#document.floorPlan.proof=/home/seluser/doc.pdf
#document.servicePlan.proof=/home/seluser/doc.pdfh
#document.elevationPlan.proof=/home/seluser/doc.pdf
#document.sectionPlan.proof=/home/seluser/doc.pdf
#document.parkingPlan.proof=/home/seluser/doc.pdf

#OBPAS Local
document.drawing.dxf=/Users/niua-l1232/Documents/automation_upyog/UPYOG-NIUA-Arpit/upyog-automation-testing/src/main/resources/Documents/OBPASDoc/OBPAS1.dxf
document.iDentity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.aDdress.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.landTax.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.titleDeedOfTheProperty.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.layoutApprovalCopy.proof=//Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.structuralStabilityCertificate.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.locationSketchAndVillageSketch.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.sitePlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.floorPlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.servicePlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.elevationPlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.sectionPlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.parkingPlan.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#E-Waste
#document.EwasteImage.proof=/home/seluser/doc.pdf

#E-Waste Local
document.EwasteImage.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#Asset-Management
#document.asset.proof=/home/seluser/doc.pdf
#document.asset1.proof=/home/seluser/selenium.png
#document.asset2.proof=/home/seluser/doc.pdf

#Asset-Management Local
document.asset.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.asset1.proof=/Users/niua-l1232/Downloads/selenium.png
document.asset2.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#Construction And Demolition
#document.siteMediaPhoto.proof=/home/seluser/doc.pdf
#document.stackPhoto.proof=/home/seluser/doc.pdf

#Construction And Demolition Local
document.siteMediaPhoto.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.stackPhoto.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

#CHB
#document.bankAccount.proof=/home/seluser/doc.pdf
#document.addressChb.proof=/home/seluser/doc.pdf
#document.applicantIdentity.proof=/home/seluser/doc.pdf

#CHB Local
document.bankAccount.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.addressChb.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.applicantIdentity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf


#Desludging
#document.pitPhoto.proof=/home/seluser/selenium.png

#Desludging Local
document.pitPhoto.proof=/Users/niua-l1232/Downloads/selenium.png

#Water And Sewerage
#document.identity1.proof=/home/seluser/doc.pdf
#document.address1.proof=/home/seluser/doc.pdf
#document.electricityBill.proof=/home/seluser/doc.pdf
#document.plumberReportDrawing.proof=/home/seluser/doc.pdf

#Water And Sewerage Local
document.identity1.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.address1.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.electricityBill.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
document.plumberReportDrawing.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf

sv.document.identity.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
sv.document.address.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
sv.document.business.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf
//sv.document.business.proof=/Users/niua-l1232/Downloads/C&D-Acknowledgement (1).pdf


upyog.city=Delhi
niuatt.city=City A

upyog.locality=Main Road Abadpura
niuatt.locality=Main Road Abadpura