spring.application.name=upyog-selenium-tests
server.port=8080
localhost=8080


# Selenium Grid Configuration (for Docker)
#false for local and true for server
selenium.grid.enabled=True
selenium.grid.url=http://selenium-chrome:4444/wd/hub
novnc.url=http://65.0.8.57:8000


# Selenium WebDriver Configuration
chrome.driver.path=/usr/local/bin/chromedriver
webdriver.wait.timeout=30
browser=chrome
timeout.explicit=30
executionMode=vnc
citizen.base.url=https://niuatt.niua.in/upyog-ui/citizen/login
employee.base.url=https://niuatt.niua.in/upyog-ui/employee/login
employee.niuatt.base.url=https://niuatt.niua.in/upyog-ui/employee/login
language.name=English
locality.name=Main Road Abadpura

house.number=12
house.name=Jagbir Bhawan
street.name=Raj Nagar
asset.name=MacBook
coordinates.value=28.590086610421395,77.2256714858255

holding.number=Test1234
land.registration=Test Land Registration

#EWASTE
module.ewaste.url=/upyog-ui/citizen/ew-home
ewaste.create.button=Create Ewaste Request
applicant.name=Arpit Rao
mobile.number=7906413996
applicant.birth.date=20-05-1990
applicant.guardian=Amit Kumar
applicant.email=arpit@gmail.com
purchase.number=P0123
purchase.cost=400000
market.value=300000
invoice.number=INV123
random.number=10
plot.area=1400
land.area=1200
construction.area= 1100


waste.quantity=10
vehicle.number=PN 45 HU 8485
road.width=200
distance.pit=300

closets.proposed=12
toilet.proposed=6
water.proposed=15
toilet.seats=4

purpose.description=Community Meeting

comment.verify=Verified
comment.approve=Approved
comment.forward=Forwarded
comment.assign=Assigned
comment.pickup=Pickup Alert
comment.complete=Completed
comment.resolve=Resolved
comment.execute=Executed

account.number=1168977476837687
ifsc.code=UBIN0530786
receipt.number=GEN123456
card.number=4111111111111111
expiry.year=2033
enter.cvv=123

authority.name=Local Authority
vending.license=VL123456

pet.birth.date=20-05-2025
vaccination.date=20-07-2025
vaccination.number=34545645
pet.name=Cheery
pet.age=5
pet.identification=Black Mark on face
doctor.name=Dr Amit
clinic.name=Amit Clinic
gis.code=2343453

pgr.description=The park is dirty and needs to be cleaned soon.
water.description=Need Water Tanker urgently

trade.name=Institute
trade1.name=ijijhvhgcy
uom.value=7
gst.number=10SEIJI3622O0Z4

address.pincode=143001
address.doorNo=201
address.building=Jagbir Bhawan
address.line1=test address
address.line2=test address
address.landmark=test landmark
address.owner=Owner Address
upyog.city=Delhi
niuatt.city=City A

product.quantity=10
enter.length=10
enter.breadth=8
enter.height=6
septage.dump=500

user.mobile=9999999999
user.otp=123456
property.id=PG-PT-1013-008453

#E-Waste Local
document.common.proof=/home/ubuntu/documents/advertisement/advertisement.pdf
document.common.png=/home/ubuntu/documents/Asset-Management/send (1).png
#EWASTE
ewaste.login.username=EW_CEMP1
ewaste.login.password=eGov@123
ewaste.application.number=PG-EW-2026-05-25-001106
final.amount=1400
transaction.id=000321932743764

#ADV
adv.login.username=ADS_CEMP
adv.login.password=upyog@123
adv.application.number=ADV-1013-000217

#PT
module.propertTax.url=/upyog-ui/citizen/pt-home
property.type=Independent Building
property.login.username=PTSU
property.login.password=upyog@123
pt.application.number=PG-PT-1013-008738

#ASSET
asset.login.username=ASSET_INITIATOR
asset.login.password=eGov@123
asset1.login.username=ASSET_VERIFIER
asset1.login.password=eGov@123
asset2.login.username=ASSET_APPROVER
asset2.login.password=eGov@123
asset.application.number=PG-1013-2025-I-001329

#CHB
chb.login.username=CHB2
chb.login.password=upyog@123
chb.application.number=CHB-1508-000145

#CND
cnd.login.username=CND_SUPER
cnd.login.password=upyog@123
cnd.application.number=CND-1013-000021
cnd.mobile.number=9000453435

#OBPAS
upyog.architect.mobile=8888888881
niuatt.architect.mobile=7272727216
document.drawing.dxf=/home/ubuntu/OBPAS1.dxf
obpas.application.number=PG-SK-2026-03-16-005459
obpas.login.username=BPASU1
obpas.login.password=upyog@123
permit.number=
permit.date=



#PET
pet.login.username=PTRSU3
pet.login.password=upyog@123
pet.application.number=PG-PTR-2026-02-24-000139

#PGR
pgr.login.username=PGRSU
pgr.login.password=upyog@123
pgr.application.number=PG-PGR-2026-05-20-002518

#MOBILE_TOILET
mt.login.username=MTCEMP
mt.login.password=eGov@123
mt.application.number=MT-1013-001194
toilet.vendor.mobile.number=9800000000

#TREE_PRUNING
tp.login.username=TPCEMP
tp.login.password=eGov@123
tp.application.number=TP-1013-000173

#WATER_TANKER
wt.login.username=WTCEMP
wt.login.password=eGov@123
wt.application.number=WT-1013-001197
water.vendor.mobile.number=7033145533



#SV
sv.login.username=SV_CEMP
sv.login.password=upyog@123
sv.application.number=SV-1013-000113


#TL
tl.login.username=TLSU1
tl.login.password=upyog@123
tl.application.number=PG-TL-2026-05-20-005526

#WATER
ws.login.username=WSSU2
ws.login.password=upyog@123
ws.application.number=WS_AP/1013/2026-27/001416
sw.application.number=SW_AP/1013/2026-27/000700


#DESLUDGING
fsm.login.username=QAEE
fsm.login.password=upyog@123
fsm.application.number=FSM-1013-2026-05-12-001423
fstpo.login.username=QAFSTPO
fstpo.login.password=upyog@123




