#citizen.base.url=https://niuatt.niua.in/upyog-ui/citizen/login
#city.name=City A
#language.name=English
#locality.name=Main Road Abadpura
#
##EWASTE
#applicant.name=Arpit Rao
#applicant.email=arpit@gmail.com
#
#address.pincode=143001
#address.street=Raj Nagar
#address.doorNo=201
#address.building=Jagbir Bhawan
#address.line1=test address 1
#address.line2=test address 2
#address.landmark=test landmark
#
#product.quantity=10
#
#user.mobile=9999999999
#user.otp=123456
