pipeline {
  agent any

  environment {
    REGISTRY = "docker.io"
    REPO = "upyoguddhp"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'master',
            url: 'https://github.com/upyoguddhp/UPYOG.git',
            credentialsId: 'git-creds'
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('municipal-services/scheduler-service') {
          sh """
            echo Building scheduler-service
            docker build -t ${REGISTRY}/${REPO}/scheduler-service:latest \
             -f build/maven/Dockerfile .
          """
        }
      }
    }

    stage('Push Image to Docker Hub') {
      steps {
        script {
          docker.withRegistry("https://${env.REGISTRY}", "docker-creds") {
            sh "docker push ${REGISTRY}/${REPO}/scheduler-service:latest"
          }
        }
      }
    }
  }
}
