<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.egov.test</groupId>
    <artifactId>sitemesh-jakarta-test</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <build>
        <plugins>

            <plugin>
                <groupId>org.eclipse.transformer</groupId>
                <artifactId>transformer-maven-plugin</artifactId>
                <version>0.5.0</version>

                <executions>
                    <execution>
                        <id>transform-sitemesh</id>
                        <phase>package</phase>

                        <goals>
                            <goal>jar</goal>
                        </goals>

                        <configuration>

                            <artifact>
                                <groupId>opensymphony</groupId>
                                <artifactId>sitemesh</artifactId>
                                <version>2.5.0</version>
                            </artifact>

                            <classifier>jakarta</classifier>

                            <rules>
                                <jakartaDefaults>true</jakartaDefaults>
                            </rules>

                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>