/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new echallan. 2. Update the details of existing echallan 3. Search the existing echallan 4. Generate the demand and bill for the echallan amount so that collection can be done in online and offline mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallan.model;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Size;

import org.egov.echallan.validation.SanitizeHtml;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Representation of a address. Indiavidual APIs may choose to extend from this using allOf if more details needed to be added in their case. 
 */
@Schema(description = "Representation of a address. Indiavidual APIs may choose to extend from this using allOf if more details needed to be added in their case. ")
@Validated
@jakarta.annotation.Generated(value = "org.egov.codegen.SpringBootCodegen", date = "2018-09-18T17:06:11.263+05:30")

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Address   {

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("id")
        private String id;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("tenantId")
        private String tenantId = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("doorNo")
        private String doorNo = null;

        @JsonProperty("latitude")
        private Double latitude = null;

        @JsonProperty("longitude")
        private Double longitude = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("addressId")
        private String addressId = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("addressNumber")
        private String addressNumber = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("type")
        private String type = null;

        @SanitizeHtml
        @JsonProperty("addressLine1")
        private String addressLine1 = null;

        @SanitizeHtml
        @Size(max=256)
        @JsonProperty("addressLine2")
        private String addressLine2 = null;

        @SanitizeHtml
        @Size(max=64)
        @JsonProperty("landmark")
        private String landmark = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("city")
        private String city = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("pincode")
        private String pincode = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("detail")
        private String detail = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("buildingName")
        private String buildingName = null;

        @Size(max=64)
        @SanitizeHtml
        @JsonProperty("street")
        private String street = null;

        @Valid
        @JsonProperty("locality")
        private Boundary locality = null;

        @SanitizeHtml
        @JsonProperty("plotNo")
        private String plotNo = null;

        @SanitizeHtml
        @JsonProperty("district")
        private String district = null;

        @SanitizeHtml
        @JsonProperty("state")
        private String state = null;

        @SanitizeHtml
        @JsonProperty("country")
        private String country = null;

        @SanitizeHtml
        @JsonProperty("region")
        private String region = null;
        
        /**
         * Helper method to get locality code for persister
         * Returns null if locality is null, otherwise returns the code
         */
        @JsonProperty("localityCode")
        public String getLocalityCode() {
            return locality != null ? locality.getCode() : null;
        }
}
