ALTER TABLE public.eg_adv_address_detail
ALTER COLUMN city DROP NOT NULL,
ALTER COLUMN city_code DROP NOT NULL,
ALTER COLUMN locality DROP NOT NULL,
ALTER COLUMN locality_code DROP NOT NULL,
ALTER COLUMN landmark DROP NOT NULL,
ALTER COLUMN address_line_1 DROP NOT NULL,
ALTER COLUMN house_no DROP NOT NULL,
ALTER COLUMN street_name DROP NOT NULL;
