package org.upyog.employee.dasboard.query.constant;

import org.springframework.stereotype.Component;

import lombok.Data;


public class DashboardQueryConstant {

	// Dashboard query constants
	// Dashboard query constants
	public static StringBuilder DASHBOARD_QUERY_ALL = new StringBuilder("WITH tenant_data AS (\n"
			+ "    SELECT ? AS tenant_id\n"
			+ "),\n"
			+ "Today_Collection AS (\n"
			+ "    SELECT CAST(SUM(amountpaid) AS BIGINT) AS Today_Collection\n"
			+ "    FROM egcl_paymentdetail\n"
			+ "    WHERE createdtime >= EXTRACT(EPOCH FROM CURRENT_DATE) * 1000\n"
			+ "      AND createdtime < EXTRACT(EPOCH FROM (CURRENT_DATE + INTERVAL '1 day')) * 1000\n"
			+ "),\n"
			+ "Total_Collection AS (\n"
			+ "    SELECT CAST(SUM(amountpaid) AS BIGINT) AS Total_Collection\n"
			+ "    FROM egcl_paymentdetail\n"
			+ "    WHERE createdtime >= (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) - INTERVAL '9 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "    AND createdtime < (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '15 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "),\n"
			+ "Total_Applications_Received AS (\n"
			+ "    SELECT COUNT(DISTINCT businessid) AS Total_Applications_Received\n"
			+ "    FROM eg_wf_processinstance_v2, tenant_data\n"
			+ "    WHERE tenantid = tenant_data.tenant_id\n"
			+ "      AND createdtime >= (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) - INTERVAL '9 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "    AND createdtime < (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '15 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "),\n"
			+ "Total_Application_Approved AS (\n"
			+ "    SELECT COUNT(DISTINCT businessid) AS Total_Application_Approved\n"
			+ "    FROM eg_wf_processinstance_v2, tenant_data\n"
			+ "    WHERE tenantid = tenant_data.tenant_id\n"
			+ "      AND action = 'APPROVE'\n"
			+ "      AND createdtime >= (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) - INTERVAL '9 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "    AND createdtime < (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '15 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "        END\n"
			+ "    )\n"
			+ "),\n"
			+ "Total_Applications_Pending AS (\n"
			+ "    SELECT COUNT(DISTINCT businessid) AS Total_Applications_Pending\n"
			+ "    FROM eg_wf_processinstance_v2, tenant_data\n"
			+ "    WHERE tenantid = tenant_data.tenant_id\n"
			+ "      AND businessid NOT IN (\n"
			+ "        SELECT DISTINCT businessid\n"
			+ "        FROM eg_wf_processinstance_v2\n"
			+ "        WHERE action IN ('ACTIVATE_CONNECTION', 'APPROVE', 'REJECT', 'CANCEL')\n"
			+ "      )\n"
			+ "      AND createdtime >= (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) - INTERVAL '9 months') * 1000\n"
			+ "        END\n"
			+ "      )\n"
			+ "      AND createdtime < (\n"
			+ "        CASE\n"
			+ "            WHEN EXTRACT(MONTH FROM NOW()) >= 4\n"
			+ "            THEN EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '15 months') * 1000\n"
			+ "            ELSE EXTRACT(EPOCH FROM DATE_TRUNC('year', NOW()) + INTERVAL '3 months') * 1000\n"
			+ "        END\n"
			+ "      )\n"
			+ ")\n"
			+ "SELECT \n"
			+ "    CAST(tc.Today_Collection AS BIGINT) AS Today_Collection,\n"
			+ "    CAST(tcc.Total_Collection AS BIGINT) AS Total_Collection,\n"
			+ "    tar.Total_Applications_Received,\n"
			+ "    taa.Total_Application_Approved,\n"
			+ "    tap.Total_Applications_Pending\n"
			+ "FROM \n"
			+ "    Today_Collection tc,\n"
			+ "    Total_Collection tcc,\n"
			+ "    Total_Applications_Received tar,\n"
			+ "    Total_Application_Approved taa,\n"
			+ "    Total_Applications_Pending tap;");

	public static StringBuilder OBPAS_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "    COUNT(DISTINCT CASE \n"
					+ "        WHEN businessservice = 'BPA' \n"
					+ "        THEN applicationno \n"
					+ "    END) AS Total_Applications_Received,\n"
					+ "    COUNT(DISTINCT CASE \n"
					+ "        WHEN businessservice = 'BPA' \n"
					+ "        AND status = 'APPROVED' \n"
					+ "        THEN applicationno \n"
					+ "    END) AS Total_Applications_Approved,\n"
					+ "    COUNT(DISTINCT CASE \n"
					+ "        WHEN businessservice = 'BPA' \n"
					+ "        AND status <> 'APPROVED'\n"
					+ "        THEN applicationno \n"
					+ "    END) AS Total_Applications_Pending,\n"
					+ "    (\n"
					+ "        SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ "        FROM egcl_paymentdetail o\n"
					+ "        WHERE o.businessservice IN (\n"
					+ "            'BPA.NC_OC_APP_FEE', \n"
					+ "            'BPA.NC_SAN_FEE', \n"
					+ "            'BPA.NC_APP_FEE', \n"
					+ "            'BPA.NC_OC_SAN_FEE', \n"
					+ "            'BPA.LOW_RISK_PERMIT_FEE', \n"
					+ "            'BPA.REG'\n"
					+ "        )\n"
					+ "        AND o.createdtime >= EXTRACT(EPOCH FROM \n"
					+ "            CASE \n"
					+ "            WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "            THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "            ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "            END\n"
					+ "        ) * 1000\n"
					+ "        AND o.createdtime < EXTRACT(EPOCH FROM \n"
					+ "            CASE \n"
					+ "            WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "            THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "            ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "            END\n"
					+ "        ) * 1000\n"
					+ "    ) AS Total_Amount\n"
					+ "FROM eg_bpa_buildingplan\n"
					+ "WHERE businessservice = 'BPA'\n"
					+ "AND createdtime >= EXTRACT(EPOCH FROM \n"
					+ "    CASE \n"
					+ "    WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "    THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "    ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "    END\n"
					+ ") * 1000\n"
					+ "AND createdtime < EXTRACT(EPOCH FROM \n"
					+ "    CASE \n"
					+ "    WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "    THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "    ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "    END\n"
					+ ") * 1000\n"
					+ "AND tenantid = ?"
	);

	public static StringBuilder ASSET_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "    COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "    COUNT(DISTINCT CASE WHEN pi.action = 'APPROVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "    COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "        SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'APPROVE'\n"
					+ "    ) THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "    (\n"
					+ "        SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ "        FROM egcl_paymentdetail o\n"
					+ "        WHERE o.businessservice = 'asset-create'\n"
					+ "        AND o.createdtime >= EXTRACT(EPOCH FROM \n"
					+ "            CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "                 THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "                 ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END\n"
					+ "        ) * 1000\n"
					+ "        AND o.createdtime < EXTRACT(EPOCH FROM \n"
					+ "            CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "                 THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "                 ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END\n"
					+ "        ) * 1000\n"
					+ "    ) AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'asset-create'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM \n"
					+ "    CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "         THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "         ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END\n"
					+ ") * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM \n"
					+ "    CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "         THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "         ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END\n"
					+ ") * 1000"
	);

	public static StringBuilder FSM_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'COMPLETED' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'COMPLETED'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'FSM'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'FSM'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder PGR_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'RESOLVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'RESOLVE'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'PGR'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'PGR'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder CHB_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT wf.booking_no) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.booking_status = 'BOOKED' THEN wf.booking_no END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.booking_status <> 'BOOKED' THEN wf.booking_no END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " JOIN eg_chb_booking_detail wf_approved ON o.receiptnumber = wf_approved.receipt_no\n"
					+ " WHERE o.businessservice = 'chb-services'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_chb_booking_detail wf\n"
					+ "WHERE wf.tenant_id = ?\n"
					+ "AND wf.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND wf.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);



	public static StringBuilder PT_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT wf.propertyid) AS Total_Applications_Received,\n"
					+ "SUM(CASE WHEN wf.status = 'ACTIVE' THEN 1 ELSE 0 END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.status = 'INWORKFLOW' THEN wf.propertyid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice LIKE 'PT%'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_pt_property wf\n"
					+ "WHERE wf.tenantid = ?\n"
					+ "AND wf.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND wf.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder PETSERVICES_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'APPROVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'APPROVE'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'pet-services'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'ptr'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder EWASTE_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'COMPLETEREQUEST' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'COMPLETEREQUEST'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'ewst'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'ewst'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder TL_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT wf.applicationnumber) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.status = 'APPROVED' THEN wf.applicationnumber END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.status <> 'APPROVED' THEN wf.applicationnumber END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice LIKE 'TL%'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_tl_tradelicense wf\n"
					+ "WHERE wf.tenantid = ?\n"
					+ "AND wf.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND wf.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);


	public static StringBuilder WATER_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'ACTIVATE_CONNECTION' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'ACTIVATE_CONNECTION'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice LIKE 'WS%'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'NewWS1'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder SEWERAGE_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'ACTIVATE_CONNECTION' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'ACTIVATE_CONNECTION'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice LIKE 'SW%'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'NewSW1'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder SV_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "    COUNT(DISTINCT wf.application_no) AS Total_Applications_Received,\n"
					+ "    SUM(CASE WHEN wf.application_status = 'REGISTRATIONCOMPLETED' THEN 1 ELSE 0 END) AS Total_Applications_Approved,\n"
					+ "    COUNT(DISTINCT wf.application_no) - SUM(CASE WHEN wf.application_status = 'REGISTRATIONCOMPLETED' THEN 1 ELSE 0 END) AS Total_Applications_Pending,\n"
					+ "    COALESCE(\n"
					+ "        (SELECT SUM(pd.amountpaid)\n"
					+ "         FROM egcl_paymentdetail pd\n"
					+ "         JOIN egcl_bill b ON pd.billid = b.id\n"
					+ "         JOIN eg_sv_street_vending_detail wf_sub ON b.consumercode = wf_sub.application_no\n"
					+ "         WHERE wf_sub.application_status = 'REGISTRATIONCOMPLETED'\n"
					+ "           AND pd.businessservice IN ('sv-services')\n"
					+ "           AND wf_sub.createdtime >= EXTRACT(EPOCH FROM \n"
					+ "              CASE \n"
					+ "                  WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 4 THEN \n"
					+ "                      DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year' + INTERVAL '3 months'\n"
					+ "                  ELSE \n"
					+ "                      DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "              END) * 1000\n"
					+ "           AND wf_sub.createdtime < EXTRACT(EPOCH FROM \n"
					+ "              CASE \n"
					+ "                  WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 4 THEN \n"
					+ "                      DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "                  ELSE \n"
					+ "                      DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year' + INTERVAL '3 months'\n"
					+ "              END) * 1000\n"
					+ "        ), 0) AS Total_Amount\n"
					+ "FROM \n"
					+ "    eg_sv_street_vending_detail wf\n"
					+ "WHERE \n"
					+ "    wf.createdtime >= EXTRACT(EPOCH FROM \n"
					+ "      CASE \n"
					+ "          WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 4 THEN \n"
					+ "              DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '1 year' + INTERVAL '3 months'\n"
					+ "          ELSE \n"
					+ "              DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "      END) * 1000\n"
					+ "    AND wf.createdtime < EXTRACT(EPOCH FROM \n"
					+ "      CASE \n"
					+ "          WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 4 THEN \n"
					+ "              DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "          ELSE \n"
					+ "              DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year' + INTERVAL '3 months'\n"
					+ "      END) * 1000\n"
					+ "    AND wf.tenant_id = ?"
	);

	public static StringBuilder WT_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'APPROVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'APPROVE'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'request-service.water_tanker'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'watertanker'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder TP_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'APPROVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'APPROVE'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'request-service.tree_pruning'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'treePruning'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder MT_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT pi.businessid) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.action = 'APPROVE' THEN pi.businessid END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN pi.businessid NOT IN (\n"
					+ "    SELECT businessid FROM eg_wf_processinstance_v2 WHERE action = 'APPROVE'\n"
					+ ") THEN pi.businessid END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " WHERE o.businessservice = 'request-service.mobile_toilet'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_wf_processinstance_v2 pi\n"
					+ "WHERE pi.businessservice = 'mobileToilet'\n"
					+ "AND pi.tenantid = ?\n"
					+ "AND pi.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND pi.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder CND_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT wf.application_number) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.application_status IN ('APPROVED','COMPLETED') THEN wf.application_number END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.application_status NOT IN ('APPROVED','COMPLETED','REJECTED','CANCELLED') THEN wf.application_number END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " JOIN egcl_bill b ON o.billid = b.id\n"
					+ " JOIN ug_cnd_application_details wf2 ON b.consumercode = wf2.application_number\n"
					+ " WHERE o.businessservice = 'cnd-service'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM ug_cnd_application_details wf\n"
					+ "WHERE wf.tenant_id = ?\n"
					+ "AND wf.created_time >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND wf.created_time < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	public static StringBuilder ADV_DASHBOARD_QUERY_ = new StringBuilder(
			"SELECT \n"
					+ "COUNT(DISTINCT wf.booking_no) AS Total_Applications_Received,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.booking_status = 'BOOKED' THEN wf.booking_no END) AS Total_Applications_Approved,\n"
					+ "COUNT(DISTINCT CASE WHEN wf.booking_status <> 'BOOKED' THEN wf.booking_no END) AS Total_Applications_Pending,\n"
					+ "(\n"
					+ " SELECT COALESCE(SUM(o.amountpaid),0)\n"
					+ " FROM egcl_paymentdetail o\n"
					+ " JOIN eg_adv_booking_detail wf2 ON o.receiptdate = wf2.payment_date\n"
					+ " WHERE o.businessservice = 'adv-services'\n"
					+ " AND o.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ " AND o.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000\n"
					+ ") AS Total_Amount\n"
					+ "FROM eg_adv_booking_detail wf\n"
					+ "WHERE wf.tenant_id = ?\n"
					+ "AND wf.createdtime >= EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE - INTERVAL '1 year') + INTERVAL '3 months' END) * 1000\n"
					+ "AND wf.createdtime < EXTRACT(EPOCH FROM CASE WHEN EXTRACT(MONTH FROM CURRENT_DATE) >= 4\n"
					+ "     THEN DATE_TRUNC('year', CURRENT_DATE + INTERVAL '1 year') + INTERVAL '3 months'\n"
					+ "     ELSE DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months' END) * 1000"
	);

	
	
	

}
