sonar.projectKey=upyog-ui
sonar.projectName=UPYOG UI React Project

sonar.host.url=http://13.126.113.90:9000
sonar.token={YOUR_USER_TOKEN}
sonar.sources=web/micro-ui-internals/packages/modules/gc
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/public/**
sonar.sourceEncoding=UTF-8