sonar.projectKey=upyog-ui
sonar.projectName=UPYOG UI React Project

sonar.host.url=http://13.126.113.90:9000
sonar.token=squ_f12725b9805c7aaee2d4b322d19297d4a0df46f1

sonar.sources=web/micro-ui-internals/packages/modules/est


sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/public/**
sonar.sourceEncoding=UTF-8

