sonar.projectKey=upyog-ui
sonar.projectName=UPYOG UI React Project

sonar.host.url=http://13.126.113.90:9000
sonar.token={YOUR_USER_TOKEN}
sonar.sources={The path of the file, you need to chcek starting from "web"}
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/public/**
sonar.sourceEncoding=UTF-8
