-- Table: public.eg_asset_depreciation_details

-- DROP TABLE IF EXISTS public.eg_asset_depreciation_details;

CREATE TABLE IF NOT EXISTS public.eg_asset_depreciation_details
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    asset_id character varying(64) COLLATE pg_catalog."default",
    book_value double precision,
    depreciation_value double precision,
    from_date date,
    to_date date,
    rate double precision,
    old_book_value double precision DEFAULT 0.0,
    updated_by character varying(64) COLLATE pg_catalog."default",
    created_by character varying(64) COLLATE pg_catalog."default" DEFAULT 'system'::character varying,
    created_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint,
    updated_at bigint DEFAULT ((EXTRACT(epoch FROM now()) * (1000)::numeric))::bigint,
    CONSTRAINT eg_asset_depreciation_details_pkey PRIMARY KEY (id),
    CONSTRAINT unique_asset_depreciation UNIQUE (asset_id, from_date, to_date),
    CONSTRAINT unique_asset_period UNIQUE (asset_id, from_date, to_date)
)