apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upyog-aggregation-service.fullname" . }}
  labels:
    {{- include "upyog-aggregation-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "upyog-aggregation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "upyog-aggregation-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "upyog-aggregation-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: UPYOG_REDIS_HOST
              value: {{ .Values.config.redis.host | quote }}
            - name: UPYOG_REDIS_PORT
              value: {{ .Values.config.redis.port | quote }}
            - name: UPYOG_OBSERVABILITY_TRACING_ENABLED
              value: {{ .Values.config.tracing.enabled | quote }}
            - name: UPYOG_OBSERVABILITY_TRACING_ENDPOINT
              value: {{ .Values.config.tracing.endpoint | quote }}
            - name: UPYOG_AUTH_ENABLED
              value: {{ .Values.config.auth.enabled | quote }}
            {{- range $key, $value := .Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "upyog-aggregation-service.fullname" $ }}-secrets
                  key: {{ $key }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
