CREATE TABLE IF NOT EXISTS sms_tracker (
    uuid  VARCHAR(255) PRIMARY KEY,
    amount  NUMERIC(10, 2) NOT NULL,
    application_no  VARCHAR(255) NOT NULL,
    tenant_id  VARCHAR(255) NOT NULL,
    service  VARCHAR(255) NOT NULL,
    month  VARCHAR(255),
    year  VARCHAR(255),
    financial_year VARCHAR(255) ,
    from_date   VARCHAR(255) NOT NULL,
    to_date   VARCHAR(255) NOT NULL,
    created_by  VARCHAR(128) NOT NULL,
    created_time   BIGINT NOT NULL,
    last_modified_by VARCHAR(128),
    last_modified_time BIGINT,
    ward   VARCHAR(256) NOT NULL,
    bill_id   VARCHAR(256) NOT NULL,
    additional_detail  JSONB,
    owner_mobile_no VARCHAR(20),
    owner_name VARCHAR(255),
    sms_request JSONB,
    sms_response JSONB,
    sms_status  BOOLEAN DEFAULT FALSE
);
