package org.egov.infra.mdms.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * Represents pending theme configuration changes.
 *
 * Any update request submitted by an employee will first be stored
 * in staging table and will become live only after workflow approval.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ThemeConfigStaging {

    /**
     * Unique identifier of staging record.
     */
    private String id;

    /**
     * State level tenant identifier.
     */
    private String tenantId;

    /**
     * Type of theme configuration being updated.
     *
     * Example:
     * EMPLOYEE
     * CITIZEN
     */
    private String themeType;

    /**
     * Updated JSON configuration submitted for approval.
     */
    private Map<String, Object> config;

    /**
     * Current status of change request.
     *
     * Values:
     * PENDING
     * APPROVED
     * REJECTED
     */
    private String status;

    /**
     * Workflow instance id generated by workflow service.
     */
    private String workflowId;

    /**
     * User who created the change request.
     */
    private String createdBy;

    /**
     * Timestamp when change request was created.
     */
    private Long createdTime;

    /**
     * User who last modified the staging request.
     */
    private String lastModifiedBy;

    /**
     * Timestamp when staging request was last modified.
     */
    private Long lastModifiedTime;

    /**
     * User who approved the configuration.
     */
    private String approvedBy;

    /**
     * Timestamp when configuration was approved.
     */
    private Long approvedTime;
}