ALTER TABLE public.eg_user_address
  ADD COLUMN IF NOT EXISTS houseNumber VARCHAR(255),
  ADD COLUMN IF NOT EXISTS houseName VARCHAR(255),
  ADD COLUMN IF NOT EXISTS streetName VARCHAR(255),
  ADD COLUMN IF NOT EXISTS address2 VARCHAR(255),
  ADD COLUMN IF NOT EXISTS landmark VARCHAR(255),
  ADD COLUMN IF NOT EXISTS locality VARCHAR(255) ;