-- =============================================================================
-- Migration: V20260713050754__add_scheduler_tables
-- Description: Consolidated schema script for dashboard data extractor pipeline.
--
-- Tables included:
--   1. ingestion_module_detail      — ULB-module configuration
--   2. ingestion_detail             — Daily ingestion audit records (includes exception_code)
--   3. legacy_data_ingestion_detail — Legacy batch & daily audit records (includes start_date, end_date, exception_code)
--   4. ingestion_module_summary     — Module ingestion status summary
--   5. adapter_ingestion_error_log  — Ingestion error log
--   6. shedlock                     — Distributed scheduler locking
-- =============================================================================

-- =============================================================================
-- Table 1: ingestion_module_detail
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_module_detail (
    detail_id                   VARCHAR(64)     NOT NULL,
    tenant_id                   VARCHAR(64)     NOT NULL,
    ulb_name                    VARCHAR(256)    NOT NULL,
    module_name                 VARCHAR(64)     NOT NULL,
    is_active                   BOOLEAN         NOT NULL DEFAULT TRUE,
    is_legacy_data_ingested     BOOLEAN         NOT NULL DEFAULT FALSE,
    last_ingested_date          DATE,
    schedule_cron               VARCHAR(128),
    created_by                  VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    created_time                BIGINT          NOT NULL,
    last_modified_by            VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    last_modified_time          BIGINT          NOT NULL,
    CONSTRAINT pk_ingestion_module_detail PRIMARY KEY (detail_id)
);

CREATE INDEX IF NOT EXISTS idx_ingestion_module_detail_tenant_module
    ON ingestion_module_detail (tenant_id, module_name)
    WHERE is_active = TRUE;

COMMENT ON TABLE ingestion_module_detail IS
    'Configuration and schedule metadata for each ULB-module ingestion stream.';
COMMENT ON COLUMN ingestion_module_detail.detail_id IS
    'Primary key — UUID generated by the application layer.';
COMMENT ON COLUMN ingestion_module_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB (e.g. pg.citya).';
COMMENT ON COLUMN ingestion_module_detail.ulb_name IS
    'Human-readable name of the Urban Local Body.';
COMMENT ON COLUMN ingestion_module_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_module_detail.is_active IS
    'Whether this ULB-module combination is currently scheduled for ingestion.';
COMMENT ON COLUMN ingestion_module_detail.is_legacy_data_ingested IS
    'Whether historical (legacy) data has been fully ingested for this module.';
COMMENT ON COLUMN ingestion_module_detail.last_ingested_date IS
    'The most recent date for which daily data was successfully ingested.';
COMMENT ON COLUMN ingestion_module_detail.schedule_cron IS
    'Cron expression defining the ingestion schedule. NULL if not scheduled.';


-- =============================================================================
-- Table 2: ingestion_detail
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_detail (
    module_ingestion_id         VARCHAR(64)     NOT NULL,
    module_detail_id            VARCHAR(64),
    tenant_id                   VARCHAR(64),
    module_name                 VARCHAR(64),
    push_date                   DATE,
    request_data                JSONB,
    response_data               JSONB,
    ingestion_status            VARCHAR(32),
    exception_code              VARCHAR(128),
    created_by                  VARCHAR(256),
    created_time                BIGINT,
    last_modified_by            VARCHAR(256),
    last_modified_time          BIGINT,
    CONSTRAINT pk_ingestion_detail PRIMARY KEY (module_ingestion_id),
    CONSTRAINT fk_ingestion_detail_module_detail
        FOREIGN KEY (module_detail_id)
        REFERENCES ingestion_module_detail (detail_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ingestion_detail_tenant_module_date
    ON ingestion_detail (tenant_id, module_name, push_date DESC);

CREATE INDEX IF NOT EXISTS idx_ingestion_detail_status
    ON ingestion_detail (ingestion_status)
    WHERE ingestion_status IN ('FAILURE', 'NOT_STARTED');

COMMENT ON TABLE ingestion_detail IS
    'Audit log of every daily ingestion push attempt to the National Dashboard.';
COMMENT ON COLUMN ingestion_detail.module_ingestion_id IS
    'Primary key — UUID generated by HttpLoader before pushing to Kafka.';
COMMENT ON COLUMN ingestion_detail.module_detail_id IS
    'Foreign key referencing ingestion_module_detail.detail_id.';
COMMENT ON COLUMN ingestion_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB whose data was pushed.';
COMMENT ON COLUMN ingestion_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_detail.push_date IS
    'Calendar date for which the module data was pushed.';
COMMENT ON COLUMN ingestion_detail.request_data IS
    'Full JSON of the NationalDashboardIngestRequest sent to the dashboard.';
COMMENT ON COLUMN ingestion_detail.response_data IS
    'HTTP response body (success) or exception message (failure).';
COMMENT ON COLUMN ingestion_detail.ingestion_status IS
    'Outcome: SUCCESS or FAILURE.';
COMMENT ON COLUMN ingestion_detail.exception_code IS
    'Standardized exception error code.';


-- =============================================================================
-- Table 3: legacy_data_ingestion_detail
-- =============================================================================
CREATE TABLE IF NOT EXISTS legacy_data_ingestion_detail (
    module_ingestion_id         VARCHAR(64)     NOT NULL,
    module_detail_id            VARCHAR(64),
    tenant_id                   VARCHAR(64),
    ulb_name                    VARCHAR(256),
    module_name                 VARCHAR(64),
    push_date                   DATE,
    start_date                  DATE,
    end_date                    DATE,
    user_id                     VARCHAR(64),
    request_data                JSONB,
    response_data               JSONB,
    ingestion_status            VARCHAR(32)     NOT NULL DEFAULT 'NOT_STARTED',
    exception_code              VARCHAR(128),
    created_by                  VARCHAR(256),
    created_time                BIGINT,
    last_modified_by            VARCHAR(256),
    last_modified_time          BIGINT,
    CONSTRAINT pk_legacy_ingestion_detail PRIMARY KEY (module_ingestion_id),
    CONSTRAINT fk_legacy_ingestion_detail_module_detail
        FOREIGN KEY (module_detail_id)
        REFERENCES ingestion_module_detail (detail_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_legacy_ingestion_detail_tenant_module_date
    ON legacy_data_ingestion_detail (tenant_id, module_name, push_date DESC);

CREATE INDEX IF NOT EXISTS idx_legacy_ingestion_detail_status
    ON legacy_data_ingestion_detail (ingestion_status)
    WHERE ingestion_status IN ('NOT_STARTED', 'FAILURE');

COMMENT ON TABLE legacy_data_ingestion_detail IS
    'Audit log of every legacy (historical daily/batch) ingestion push attempt.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_ingestion_id IS
    'Primary key — UUID generated by the legacy ingestion scheduler or orchestrator.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_detail_id IS
    'Foreign key referencing ingestion_module_detail.detail_id.';
COMMENT ON COLUMN legacy_data_ingestion_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB whose data was pushed.';
COMMENT ON COLUMN legacy_data_ingestion_detail.ulb_name IS
    'Name of the Urban Local Body whose legacy data was ingested.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN legacy_data_ingestion_detail.push_date IS
    'Calendar date on which legacy data was pushed.';
COMMENT ON COLUMN legacy_data_ingestion_detail.start_date IS
    'Inclusive start date of the legacy ingestion range.';
COMMENT ON COLUMN legacy_data_ingestion_detail.end_date IS
    'Inclusive end date of the legacy ingestion range.';
COMMENT ON COLUMN legacy_data_ingestion_detail.user_id IS
    'Identifier of the user or system that triggered the legacy ingestion.';
COMMENT ON COLUMN legacy_data_ingestion_detail.request_data IS
    'Full JSON of the NationalDashboardIngestRequest sent to the dashboard.';
COMMENT ON COLUMN legacy_data_ingestion_detail.response_data IS
    'HTTP response body (success) or exception message (failure).';
COMMENT ON COLUMN legacy_data_ingestion_detail.ingestion_status IS
    'Outcome: NOT_STARTED (default), SUCCESS, or FAILURE.';
COMMENT ON COLUMN legacy_data_ingestion_detail.exception_code IS
    'Standardized exception error code.';


-- =============================================================================
-- Table 4: ingestion_module_summary
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_module_summary (
    id                          VARCHAR(64)     NOT NULL,
    tenant_id                   VARCHAR(64)     NOT NULL,
    module_name                 VARCHAR(64)     NOT NULL,
    last_successful_date        DATE            NOT NULL,
    last_attempted_date         DATE,
    created_by                  VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    created_time                BIGINT          NOT NULL,
    last_modified_by            VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    last_modified_time          BIGINT          NOT NULL,
    CONSTRAINT pk_ingestion_module_summary PRIMARY KEY (id),
    CONSTRAINT uk_ingestion_module_summary_tenant_module UNIQUE (tenant_id, module_name)
);

CREATE INDEX IF NOT EXISTS idx_ingestion_module_summary_tenant_module
    ON ingestion_module_summary (tenant_id, module_name);

COMMENT ON TABLE ingestion_module_summary IS
    'Tracks the latest successful ingestion push date per tenant and module.';
COMMENT ON COLUMN ingestion_module_summary.id IS
    'Primary key — UUID generated by the application layer.';
COMMENT ON COLUMN ingestion_module_summary.tenant_id IS
    'DIGIT tenant identifier for the ULB (e.g. pg.citya or state code pg).';
COMMENT ON COLUMN ingestion_module_summary.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_module_summary.last_successful_date IS
    'The most recent calendar date for which metrics were successfully ingested.';
COMMENT ON COLUMN ingestion_module_summary.last_attempted_date IS
    'The most recent calendar date for which metrics ingestion was attempted (regardless of success or failure).';


-- =============================================================================
-- Table 5: adapter_ingestion_error_log
-- =============================================================================
CREATE TABLE IF NOT EXISTS adapter_ingestion_error_log (
    id                  VARCHAR(64)     NOT NULL,
    tenant_id           VARCHAR(64)     NOT NULL,
    module_name         VARCHAR(64)     NOT NULL,
    error_date          VARCHAR(64)     NOT NULL,
    issue_description   TEXT,
    created_time        BIGINT          NOT NULL,
    created_by          VARCHAR(64)     NOT NULL,
    CONSTRAINT pk_adapter_ingestion_error_log PRIMARY KEY (id)
);


-- =============================================================================
-- Table 6: shedlock
-- =============================================================================
CREATE TABLE IF NOT EXISTS shedlock (
    name VARCHAR(64) NOT NULL,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);

