// ignore_for_file: camel_case_types, non_constant_identifier_names

class i18 {
  i18._();
  static Common common = const Common();
  static Login login = const Login();
  static Register register = const Register();
  static Otp otp = const Otp();
  static Grievance grievance = const Grievance();
  static TradeLicense tradeLicense = const TradeLicense();
  static TlPropertyDetails tlProperty = const TlPropertyDetails();
  static Profile profile = const Profile();
  // static BirthDeath birthDeath = const BirthDeath();
  static PropertyTax propertyTax = const PropertyTax();
  static Building building = const Building();
  static BuildingReg buildingReg = const BuildingReg();
  static BuildingPg buildingPg = const BuildingPg();
  static WaterSewerage waterSewerage = const WaterSewerage();
  static Inbox inbox = const Inbox();
  static FsmLocal fsmLocal = const FsmLocal();
  static Challans challans = const Challans();
  static Nocs noc = const Nocs();
}

class Login {
  const Login();
  String get LOGIN_LABEL_HEADER => 'CS_LOGIN_PROVIDE_MOBILE_NUMBER';
  String get LOGIN_TEXT => 'CS_LOGIN_TEXT';
  String get LOGIN_PHONE_NO => 'CORE_COMMON_MOBILE_NUMBER';
  String get AGREE_THE_DIGITS => 'CCF_I_AGREE_THE_DIGITS_';
  String get PRIVACY_POLICY => 'CCF_PRIVACY_POLICY_';
  String get ERROR_MOBILE => 'CORE_COMMON_PHONE_NUMBER_PLACEHOLDER';
}

class Otp {
  const Otp();
  String get LOGIN_OTP => 'CS_LOGIN_OTP';
  String get LOGIN_OTP_TEXT => 'CS_LOGIN_OTP_TEXT';
  String get RESEND_OTP => 'CS_RESEND_OTP';
  String get RESEND_ANOTHER_OTP => 'CS_RESEND_ANOTHER_OTP';
  String get RESEND_SECONDS => 'CS_RESEND_SECONDS';
  String get INVALID_OTP => 'CS_INVALID_OTP';
}

class Register {
  const Register();
  String get REGISTER_LABEL_HEADER => 'CS_LOGIN_PROVIDE_NAME_DOB';
  String get REGISTER_TEXT => 'CS_LOGIN_NAME_TEXT';
  String get REGISTER_HAVE_ACCOUNT => 'CORE_REGISTER_HAVE_ACCOUNT';
}

class Common {
  const Common();
  String get HOME => 'COMMON_BOTTOM_NAVIGATION_HOME';
  String get EDIT_PROFILE => 'EDIT_PROFILE';
  String get LOGOUT => 'CORE_COMMON_LOGOUT';
  String get HELPLINE => 'CS_COMMON_HELPLINE';
  String get CONTINUE => 'CORE_COMMON_CONTINUE';
  String get NEXT => 'CS_COMMONS_NEXT';
  String get DOB => 'CORE_COMMON_DOB';
  String get SERVICE_DEFS => 'SERVICEDEFS.';
  String get OPEN => 'CS_COMMON_OPEN';
  String get CLOSED => 'CS_COMMON_CLOSED';
  String get TIMELINE => 'VIEW_TIMELINE';
  // String get VIEW_HISTORY => 'TL_VIEW_HISTORY';
  String get COMMENTS => 'WF_COMMON_COMMENTS';
  String get DOCUMENTS => 'CS_COMMON_ATTACHMENTS';
  String get YOU_RATED => 'CS_ADDCOMPLAINT_YOU_RATED';
  String get SAVE => 'CORE_COMMON_SAVE';
  String get MAKE_PAYMENT => 'COMMON_MAKE_PAYMENT';
  String get LOCATION_PREFIX => 'TENANT_TENANTS_';
  String get DOWNLOAD => 'CS_COMMON_DOWNLOAD';
  String get PAYMENT_RECEIPT => 'CS_COMMON_PAYMENT_RECEIPT';
  String get BIRTH => 'ACTION_TEST_BIRTH';
  String get DEATH => 'ACTION_TEST_DEATH';
  String get DOCS => 'PT_COMMON_DOCS';
  String get VIEWDETAILS => 'TL_VIEW_DETAILS';
  String get DATE_LABEL => 'TL_DATE_LABEL';
  String get NOC_TYPE => 'NOC_TYPE_LABEL';
  String get NOC_APPLICANT_DETAILS => 'NOC_APPLICANT_DETAILS_HEADER';
  String get NOC_APPLICANT_NAME => 'NOC_APPLICANT_NAME_LABEL';
  String get NOC_APPLICANT_DOB => 'NOC_APPLICANT_DOB_LABEL';
  String get NOC_APPLICANT_EMAIL => 'NOC_APPLICANT_EMAIL_LABEL';
  String get APPLICATION_STATUS => 'TL_COMMON_TABLE_COL_STATUS';
  String get PROPERTY_TAX_PAYMENT_HEADER => 'PT_MY_PAYMENTS_HEADER';
  String get WF_EMPLOYEE => 'WF_EMPLOYEE_';
  String get CANCEL => 'CANCEL';
  String get CS_COMMON_CANCEL => 'CS_COMMON_CANCEL';
  String get BOTTOM_HOME => 'ACTION_TEST_HOME';
  String get ALL_CITIZEN_SERVICES => 'DASHBOARD_CITIZEN_SERVICES_LABEL';
  String get SEARCH => 'COMMON_TABLE_SEARCH';
  String get ES_SEARCH => 'ES_COMMON_SEARCH';
  String get PROPERTY_TAX => 'MODULE_PT';
  String get TRADE_LICENSE => 'MODULE_TL';
  String get WATER_SEWERAGE => 'ACTION_TEST_WATER_AND_SEWERAGE';
  String get WATER => 'MODULE_WS';
  String get SEWERAGE => 'MODULE_SW';
  String get MODULE_FIRENOC => 'MODULE_FIRENOC';
  String get HELP_GRIEVANCE => 'ACTION_TEST_COMPLAINTS';
  String get BUILDING_PLAN_APPROVAL => 'ACTION_TEST_OBPS';
  String get ACTION_TEST_FSM => 'ACTION_TEST_FSM';
  String get BIRTH_AND_DEATH => 'ACTION_TEST_BIRTH_&_DEATH';
  String get FIRE_NOC => 'MODULE_FIRENOC';
  String get DESULDGING_SERVICES => 'ACTION_TEST_FSM';
  String get MCOLLECT => 'ACTION_TEST_MCOLLECT';
  String get LOGIN => 'CORE_COMMON_LOGIN';
  String get OTP => 'CORE_OTP_OTP';
  String get PINCODE => 'CORE_COMMON_PINCODE';
  String get OTP_BUTTON => 'CORE_OTP_BUTTON';
  String get LOGIN_PHONE_HINT_TEXT => 'CORE_COMMON_PHONE_NUMBER_PLACEHOLDER';
  String get SIGNUP_REGISTER_HEADING => 'CORE_COMMON_SIGNUP';
  String get DONT_HAVE_ACC => 'CORE_LOGIN_NO_ACCOUNT';
  String get LOGIN_AGREE_TERM => 'CCF_I_AGREE_THE_DIGITS_';
  String get NAME_HINT_TEXT => 'CORE_COMMON_NAME_PLACEHOLDER';
  String get HAVE_AN_ACCOUNT => 'CORE_REGISTER_HAVE_ACCOUNT';
  String get SELECT_EMPLOYEE => 'ACTION_TEST_EMPLOYEE';
  String get SELECT_CITIZEN => 'ACTION_TEST_CITIZEN';
  String get SELECT_CITY => 'CS_COMMON_CHOOSE_LOCATION';
  String get POPULAR_CITIES => 'CORE_POPULAR_ULBS';
  String get OTHER_CITIES => 'CORE_OTHER_ULBS';
  String get EMPLOYEE_USERNAME => 'CORE_LOGIN_USERNAME_PLACEHOLDER';
  String get EMPLOYEE_PASSWORD => 'CORE_LOGIN_PASSWORD_PLACEHOLDER';
  String get EMPLOYEE_CITY => 'CORE_COMMON_CITY_PLACEHOLDER';
  String get SUBMIT => 'CS_COMMON_SUBMIT';
  String get APPLICATION_DETAILS => 'CS_TITLE_APPLICATION_DETAILS';
  String get COMPLAINT_FILED => 'CS_COMMON_COMPLAINT_FILED';
  String get NAME => 'CORE_COMMON_NAME';
  String get MOBILE_NUMBER => 'CORE_COMMON_MOBILE_NUMBER';
  String get EMAIL_ID => 'CORE_COMMON_EMAIL_ID';
  String get WHATS_NEW => 'DASHBOARD_WHATS_NEW_LABEL';
  String get NOTIFICATION => 'CS_HEADER_NOTIFICATIONS';
  String get NO_DATA => 'ES_COMMON_NO_DATA';
  String get DOCUMENTS_NOT_FOUND => 'CE_DOCUMENTS_NOT_FOUND';
  String get CS_NA => 'CS_NA';
  String get ES_CLEAR => 'ES_COMMON_CLEAR_SEARCH';

  //LogOut
  String get LOGOUT_HEADER => 'CORE_LOGOUT_WEB_HEADER';
  String get LOGOUT_CONFIRMATION_MESSAGE =>
      'CORE_LOGOUT_WEB_CONFIRMATION_MESSAGE';
  String get CORE_LOGOUT_MESSAGE => 'CORE_LOGOUT_MESSAGE';
  String get LOGOUT_CANCEL => 'CORE_LOGOUT_CANCEL';
  String get LOGOUT_YES => 'CORE_LOGOUT_WEB_YES';

  String get CS_COMMON => 'CS_COMMON_';
  String get NA => 'NA';
  String get APPLY => 'ES_COMMON_APPLY';
  String get OWNER_TYPE => 'COMMON_MASTERS_OWNERTYPE_';
  String get FILED_VIA => 'ES_COMMON_FILED_VIA_';
  String get GO_TO_HOME => 'CORE_COMMON_GO_TO_HOME';

  //BPA
  String get APPLICANT_NAME => 'BPA_BASIC_DETAILS_APPLICATION_NAME_LABEL';
  String get BPA_APP_FEE_RECEIPT => 'BPA_APP_FEE_RECEIPT';
  String get BPA_PERMIT_ORDER => 'BPA_PERMIT_ORDER';

  //PT - BILL
  String get COMMON_ARREARS => 'COMMON_ARREARS';
  String get ARREARS_DETAILS => 'CS_ARREARS_DETAILS';
  String get BILL_NO => 'CS_BILL_NO';
  String get BILL_DUE_DATE => 'CS_BILL_DUEDATE';
  String get COMMON_ARREARS_TOTAL => 'COMMON_ARREARS_TOTAL';
  String get MUTATION_NUMBER_LABEL => 'PDF_STATIC_LABEL_MUATATION_NUMBER_LABEL';
  String get DOWNLOAD_RECEIPT => 'DOWNLOAD_RECEIPT_HEADER';

  //FIRE NOC
  String get CITIZEN_FIRENOC => 'WF_CITIZEN_FIRENOC_PAY';
  String get EMP_FIRE_NOC => 'ACTION_TEST_FIRE_NOC';

  //MCOLLECT
  String get CHALLAN_VALIDITY => 'CHALLAN_VALIDITY';
  String get DAY => 'COMMON_DAY';

  //WS benefit
  String get PAY_WATER_CHARGES => 'PAY_WATER_CHARGES_BY';
  String get COMMON_DAYS => 'COMMON_DAYS';
  String get OF_BILL_GEN_TO_AVOID => 'OF_BILL_GEN_TO_AVOID_LATE_FEE';
  String get WS_APPLICATION_PROCESSING => 'APPLICATION_PROCESSING_TIME';


  //Employee
  String get EMP_INBOX => 'CS_COMMON_INBOX_';
  String get TAKE_ACTION => 'WF_TAKE_ACTION';
  String get EMP_WORKLIST => 'WF_MY_WORKLIST';
  String get EMP_LOCATION_DETAILS => 'ES_NEW_APPLICATION_LOCATION_DETAILS';
  String get EMP_CITY => 'MYCITY_CODE_LABEL';
  String get EMP_STREET_NAME => 'PT_PROPERTY_ADDRESS_STREET_NAME';
  String get EMP_HOUSE_NO => 'PT_PROPERTY_ADDRESS_HOUSE_NO';
  String get EMP_IDENTITYPROOF => 'OWNER_IDENTITYPROOF';
  String get EMP_ADDRESSPROOF => 'OWNER_ADDRESSPROOF';

  //BPA
  String get EMP_APP_DATE => 'CS_APPLICATION_DETAILS_APPLICATION_DATE';
  String get EMP_TIME => 'ES_COMMON_TIME';
  String get BPA_NO_DOCUMENT => 'BPA_NO_DOCUMENTS_UPLOADED_LABEL';

  //WS
  String get EMP_SLA => 'ES_INBOX_SLA_DAYS_REMAINING';
  String get EMP_WS_TAX => 'WS_TAX_HEADER';
  String get EMP_INBOX_STATUS => 'CS_INBOX_STATUS_FILTER';

  //PT
  String get EMP_NEW_PROPERTY => 'ES_PT_NEW_PROPERTY';
  String get EMP_PROPERTY_DETAILS => 'PT_DETAILS';
  String get PROPERTY_ID => 'TL_PROPERTY_ID';
  String get OWNER_NAME => 'PT_OWNER_NAME';

  //TL
  String get EMP_ULB => 'WF_INBOX_HEADER_CURRENT_OWNER';
  String get EMP_TR_DETAILS => 'TL_COMMON_TR_DETAILS';
  String get EMP_TRD_NAME => 'TL_COMMON_TABLE_COL_TRD_NAME';
  String get EMP_COMMON_DOCS => 'PT_COMMON_DOCS';

  String get CS_COMMON_CHOOSE_FILE => 'CS_COMMON_CHOOSE_FILE';
  String get NO_OPTION => 'CMN_NOOPTION';
  String get TL_VALIDITY => 'TL_VALIDITY';
  String get TL_ISSUED_12_MONTH => 'APPLICATION_ISSUED_IN_LAST_12_MONTHS';
  String get TL_RENEWED_12_MONTH => 'APPLICATION_RENEWED_IN_LAST_12_MONTHS';

  String get COMMON_YEAR => 'COMMON_YEAR';
  String get CALL_CENTER_HELPLINE => 'CALL_CENTER_HELPLINE';
  String get CITIZEN_SERVICE_CENTER => 'CITIZEN_SERVICE_CENTER';
  String get VIEW_ON_MAP => 'VIEW_ON_MAP';

  //User Charges
  String get UC_COLLECT => 'UC_COMMON_HEADER_SEARCH';
  String get UC_EMAIL_ERROR => 'CS_ADDCOMPLAINT_EMAIL_ERROR';
  String get UC_SUBMIT => 'ES_COMMON_APPLICATION_SUBMIT';
}

class Inbox {
  const Inbox();
  String get LOCALITY => 'ES_INBOX_LOCALITY';
  String get FILTER_BY => 'ES_COMMON_FILTER_BY';
  String get NO_APPLICATION => 'CS_MYAPPLICATIONS_NO_APPLICATION';
  String get ASSIGNED_TO_ME => 'ES_INBOX_ASSIGNED_TO_ME';
  String get ASSIGNED_TO_ALL => 'ES_INBOX_ASSIGNED_TO_ALL';
}

class Grievance {
  const Grievance();
  String get GRIEVANCE => 'ES_PGR_HEADER_COMPLAINT';
  String get FILE_A_COMPLAINT => 'CS_COMMON_FILE_A_COMPLAINT';
  String get MY_COMPLAINTS => 'CS_HOME_MY_COMPLAINTS';
  String get ID => 'CS_COMMON_COMPLAINT_NO';
  //DETAILS
  String get DETAILS_HEADER => 'CS_HEADER_COMPLAINT_SUMMARY';
  String get DETAILS_ID => 'CS_COMPLAINT_DETAILS_COMPLAINT_NO';
  String get DETAILS_APPLICATION_STATUS =>
      'CS_COMPLAINT_DETAILS_APPLICATION_STATUS';
  String get DETAILS_TYPE => 'CS_ADDCOMPLAINT_COMPLAINT_TYPE';
  String get DETAILS_SUB_TYPE => 'CS_ADDCOMPLAINT_COMPLAINT_SUB_TYPE';
  String get DETAILS_PRIORITY => 'CS_ADDCOMPLAINT_PRIORITY_LEVEL';
  String get DETAILS_ADDITIONAL_DETAILS => 'CS_COMPLAINT_ADDTIONAL_DETAILS';
  String get DETAILS_COMPLAINT_FILED_DATE => 'CS_COMPLAINT_FILED_DATE';
  String get ADDRESS => 'ES_CREATECOMPLAINT_ADDRESS';
  String get GRIEVANCE_STATUS_TIMELINE =>
      'CS_COMPLAINT_DETAILS_COMPLAINT_TIMELINE';

  String get OPEN => 'CS_COMMON_PENDINGFORASSIGNMENT';
  String get CLOSED => 'CS_COMMON_CLOSEDAFTERRESOLUTION';

  String get STREETLIGHTS => '${i18.common.SERVICE_DEFS}STREETLIGHTS';
  String get GARBAGE => '${i18.common.SERVICE_DEFS}GARBAGE';

  //Timeline
  String get CLOSED_AFTER_RESOLUTION =>
      'CS_COMMON_CS_COMMON_CLOSEDAFTERRESOLUTION';
  String get COMPLIANT_RESOLVED => 'CS_COMMON_COMPLAINT_RESOLVED';
  String get PENDING_LME => 'CS_COMMON_PENDINGATLME';
  String get ACKNOWLEDGED => 'CS_COMMON_PENDINGFORASSIGNMENT';

  //PGR Form
  String get NEW_COMPLAINT => 'ES_CREATECOMPLAINT_NEW_COMPLAINT';
  String get COMPLAINT_DETAILS => 'CS_COMPLAINT_DETAILS_COMPLAINT_DETAILS';
  String get COMPLAINT_TYPE => 'CS_COMPLAINT_DETAILS_COMPLAINT_TYPE';
  String get COMPLAINT_SUBTYPE => 'CS_COMPLAINT_DETAILS_COMPLAINT_SUBTYPE';
  String get COMPLAINT_PRIORITY_LEVEL =>
      'CS_COMPLAINT_DETAILS_COMPLAINT_PRIORITY_LEVEL';
  String get MOHALLA => 'CS_CREATECOMPLAINT_MOHALLA';
  String get LANDMARK => 'CS_ADDCOMPLAINT_LANDMARK';
  String get EVIDENCE => 'CS_ADDCOMPLAINT_UPLOAD_PHOTO';
  String get UPLOAD_PHOTO_TEXT => 'CS_ADDCOMPLAINT_UPLOAD_PHOTO_TEXT';
  String get PROVIDE_ADDITIONAL_DETAILS =>
      'CS_ADDCOMPLAINT_PROVIDE_ADDITIONAL_DETAILS';
  String get ADDITIONAL_DETAILS_TEXT =>
      'CS_ADDCOMPLAINT_ADDITIONAL_DETAILS_TEXT';
  String get ADDITIONAL_DETAILS => 'CS_ADDCOMPLAINT_ADDITIONAL_DETAILS';
  String get SUBMIT_COMPLAINT =>
      'CS_ADDCOMPLAINT_ADDITIONAL_DETAILS_SUBMIT_COMPLAINT';
  String get COMPLAINT_SUBMITTED => 'CS_COMMON_COMPLAINT_SUBMITTED';
  String get COMPLAINT_NUMBER => 'CS_PGR_COMPLAINT_NUMBER';
  String get COMPLAINT_TEXT => 'CS_COMMON_TRACK_COMPLAINT_TEXT';
  String get GRIEVANCE_LOCATION => 'CS_ADDCOMPLAINT_LOCATION';
  String get GRIEVANCE_CITY => 'CS_COMPLAINT_DETAILS_CITY';
  String get SERVICEDEFS => 'SERVICEDEFS';

//EMP PGR
  String get EMP_ASSIGN => 'CS_ACTION_ASSIGN';
  String get EMP_EMPLOYEE_NAME => 'CS_COMMON_EMPLOYEE_NAME';
  String get EMP_EMPLOYEE_COMMENTS => 'CS_COMMON_EMPLOYEE_COMMENTS';
  String get PGR_FILTER_STATUS => 'ES_PGR_FILTER_STATUS';
  String get PGR_LOCALITY => 'CS_PGR_LOCALITY';
}

class TradeLicense {
  const TradeLicense();

  String get MY_APPLICATIONS => 'TL_MY_APPLICATIONS_HEADER';
  String get APPLICATION_NO => 'TL_COMMON_TABLE_COL_APP_NO';
  String get LICENSE_NO => 'TL_COMMON_TABLE_COL_LICENSE_NO';
  String get APPLICATION_CATEGORY => 'TL_APPLICATION_CATEGORY';
  String get OWNER_NAME => 'TL_COMMON_TABLE_COL_OWN_NAME';
  String get SLA => 'TL_COMMON_TABLE_COL_SLA_NAME';
  String get BUSINESS_NAME => 'TL_COMMON_TABLE_COL_TRD_NAME';
  String get VIEW_DETAILS => 'TL_VIEW_DETAILS';
  String get VIEW_DETAILS_PAY => 'TL_VIEW_DETAILS_PAY';
  String get APPLICATION_DETAILS => 'TL_TRADE_APPLICATION_DETAILS_LABEL';
  String get GST_NO => 'TL_TRADE_GST_NO';
  String get OPERATIONAL_AREA => 'TL_OPERATIONAL_AREA';
  String get NO_OF_EMPLOYEES => 'TL_NO_OF_EMPLOYEES';
  String get OWNERSHIP_DETAILS => 'TL_OWNERSHIP_DETAILS_HEADER';

  String get TRADE_OWNER => 'TL_PAYMENT_PAID_BY_PLACEHOLDER';
  String get GENDER => 'TL_NEW_OWNER_DETAILS_GENDER_LABEL';
  String get MOBILE => 'TL_MOBILE_NUMBER_LABEL';
  String get EMAIL => 'TL_EMAIL_ID_LABEL';
  String get GUARDIAN => 'TL_GUARDIAN_S_NAME_LABEL';
  String get RELATIONSHIP_WITH_GUARDIAN =>
      'TL_RELATIONSHIP_WITH_GUARDIAN_LABEL';

  String get TRADE_UNITS => 'TL_TRADE_UNITS_HEADER';
  String get UNIT => 'TL_UNIT_HEADER';
  String get INDUSTRY_TYPE => 'TL_NEW_TRADE_DETAILS_TRADE_CAT_LABEL';
  String get TRADE_DESC => 'TL_NEW_TRADE_DETAILS_TRADE_TYPE_LABEL';
  String get TRADE_SUB_TYPE => 'TL_NEW_TRADE_DETAILS_TRADE_SUBTYPE_LABEL';
  String get TRADE_TYPE_RES => 'TRADELICENSE_TRADETYPE_';
  String get TRADE_LICENSE_TYPE_RES => 'TRADELICENSE_LICENSETYPE_';
  String get TRADE_DESC_RES => 'TL_';

  String get ACCESSORY => 'TL_NEW_TRADE_DETAILS_HEADER_ACC';
  String get ACCESSORY_LABEL => 'TL_ACCESSORY_LABEL';
  String get ACCESSORY_TYPE => 'TL_REVIEWACCESSORY_TYPE_LABEL';
  String get ACCESSORY_COUNT => 'TL_NEW_TRADE_ACCESSORY_COUNT_LABEL';
  String get ACCESSORY_UOM => 'TL_NEW_TRADE_ACCESSORY_UOM_LABEL';
  String get ACCESSORY_UOMVALUE => 'TL_NEW_TRADE_ACCESSORY_UOMVALUE_LABEL';

  String get EVIDENCE => 'TL_COMMON_DOCS';
  String get APPLICATION_TIMELINE =>
      'CS_APPLICATION_DETAILS_APPLICATION_TIMELINE';

  String get TL_APPLICATION => 'TL_APPLICATION';
  String get TL_CERTIFICATE => 'TL_CERTIFICATE';
  String get TEST_TRADE_LICENSE => 'ACTION_TEST_TRADE_LICENSE';

  //Employee
  String get EMP_APPLICATION_NO => 'WF_INBOX_HEADER_APPLICATION_NO';
  String get EMP_APPLICATION_DATE => 'TL_COMMON_TABLE_COL_APP_DATE';
  String get EMP_APPLICATION_CHALLAN => 'TL_APPLICATION_CHALLAN_LABEL';
  String get EMP_FINANCIAL_YEAR => 'TL_FINANCIAL_YEAR_LABEL';
  String get EMP_LIC_TYPE => 'TL_NEW_TRADE_DETAILS_LIC_TYPE_LABEL';
  String get EMP_STRUCT_TYPE => 'TL_NEW_TRADE_DETAILS_STRUCT_TYPE_LABEL';
  String get EMP_STRUCT_SUB_TYPE =>
      'TL_NEW_TRADE_DETAILS_STRUCT_SUB_TYPE_LABEL';
  String get EMP_TRADE_COMM_DATE =>
      'TL_NEW_TRADE_DETAILS_TRADE_COMM_DATE_LABEL';
  String get EMP_GST_NUMBER => 'TL_NEW_GST_NUMBER_LABEL';
  String get EMP_OPERATIONAL_SQ_FT => 'TL_NEW_OPERATIONAL_SQ_FT_AREA_LABEL';
  String get EMP_NUMBER_OF_EMP => 'TL_NEW_NUMBER_OF_EMPLOYEES_LABEL';
}

class TlPropertyDetails {
  const TlPropertyDetails();
  String get PROPERTY_DETAILS => 'PT_DETAILS';
  String get ID => 'TL_PROPERTY_ID';
  String get NAME => 'PT_OWNER_NAME';
  String get ADDRESS => 'PROPERTY_ADDRESS';
  String get VIEW_DETAILS_BTN => 'TL_VIEW_PROPERTY_DETAIL';

  String get PROPERTY_INFO => 'PT_PROPERTY_INFO_HEADER';
  String get STATUS => 'PT_SEARCHPROPERTY_TABEL_STATUS';

  String get ADDRESS_HEADER => 'PT_PROPERTY_ADDRESS_SUB_HEADER';
  String get PINCODE => 'PT_PROPERTY_ADDRESS_PINCODE';
  String get CITY => 'PT_PROPERTY_ADDRESS_CITY';
  String get MOHALLA => 'PT_PROPERTY_ADDRESS_MOHALLA';
  String get HOUSE_NO => 'PT_PROPERTY_ADDRESS_HOUSE_NO';
  String get STREET_NAME => 'PT_PROPERTY_ADDRESS_STREET_NAME';

  String get PROPERTY_DETAILS_SUB => 'PT_ASSESMENT_INFO_SUB_HEADER';
  String get PROPERTY_TYPE => 'PT_ASSESMENT_INFO_TYPE_OF_BUILDING';
  String get USE => 'PT_ASSESMENT_INFO_USAGE_TYPE';
  String get AREA => 'PT_ASSESMENT_INFO_PLOT_SIZE';
  String get NO_OF_FLOOR => 'PT_ASSESMENT_INFO_NO_OF_FLOOR';

  String get OWNER_DETAILS_SUB => 'PT_OWNERSHIP_INFO_SUB_HEADER';
  String get OWNER => 'ES_OWNER';
  String get OWNERSHIP_INFO_NAME => 'PT_OWNERSHIP_INFO_NAME';
  String get OWNERSHIP_INFO_GENDER => 'PT_OWNERSHIP_INFO_GENDER';
  String get OWNERSHIP_INFO_MOBILE_NO => 'PT_OWNERSHIP_INFO_MOBILE_NO';
  String get SPECIAL_CATEGORY => 'PT_OWNERSHIP_INFO_USER_CATEGORY';
  String get GUARDIAN_NAME => 'PT_SEARCHPROPERTY_TABEL_GUARDIANNAME';
  String get OWNERSHIP_TYPE => 'PT_FORM3_OWNERSHIP_TYPE';
  String get OWNERSHIP_INFO_EMAIL_ID => 'PT_OWNERSHIP_INFO_EMAIL_ID';
  String get OWNERSHIP_ADDRESS => 'PT_OWNERSHIP_INFO_CORR_ADDR';
}

class Profile {
  const Profile();
  String get EDIT_PROFILE => 'EDIT_PROFILE';
  String get NAME => 'CORE_COMMON_PROFILE_NAME';
  String get GENDER => 'CORE_COMMON_PROFILE_GENDER';
  String get DOB => 'CORE_COMMON_PROFILE_DOB';
  String get EMAIL => 'CORE_COMMON_PROFILE_EMAIL';
  String get PROFILE_UPDATE_SUCCESS => 'CORE_COMMON_PROFILE_UPDATE_SUCCESS';
}

class PropertyTax {
  const PropertyTax();

  String get MY_PROPERTIES => 'PT_MY_PROPERTIES';
  String get MY_APPLICATION => 'PT_MY_APPLICATION';
  String get MY_PROPERTIES_HEADER => 'PT_MY_PROPERTIES_HEADER';
  String get LOAD_MORE => 'PT_LOAD_MORE_MSG';
  String get PROPERTY_ID => 'PT_COMMON_TABLE_COL_PT_ID';
  String get OWNER_NAME => 'PT_COMMON_TABLE_COL_OWNER_NAME';
  String get ADDRESS => 'PT_COMMON_COL_ADDRESS';
  String get STATUS_LABEL => 'PT_COMMON_TABLE_COL_STATUS_LABEL';
  String get VIEW_DETAILS => 'PT_VIEW_DETAILS';
  String get MY_PAYMENTS => 'PT_MY_PAYMENTS';

  String get PROPERTY_INFORMATION => 'PT_PROPERTY_INFORMATION';
  String get PROPERTY_UID => 'PT_PROPERTY_PTUID';
  String get TOTAL_AMOUNT_DUE => 'CS_COMMON_TOTAL_AMOUNT_DUE';
  String get VIEW_PAYMENT => 'PT_VIEW_PAYMENT';
  String get CITY => 'PT_COMMON_CITY';
  String get LOCALITY_OR_MOHALLA => 'PT_COMMON_LOCALITY_OR_MOHALLA';
  String get HOUSE_NO => 'PT_PROPERTY_ADDR_DOOR_HOUSE_NO';
  String get ASSESSMENT_DETAILS_HEADER =>
      'PT_PROPERTY_ASSESSMENT_DETAILS_HEADER';
  String get PROPERTY_TYPE => 'PT_COMMON_PROPERTY_TYPE';
  String get AREA => 'PT_ASSESMENT1_PLOT_SIZE';
  String get ELECTRICITY_ID => 'PT_ASSESSMENT1_ELECTRICITY';
  String get ASSESSMENT_UID => 'PT_ASSESSMENT1_UID';
  String get GROUND_FLOOR => 'PROPERTYTAX_FLOOR_0';
  String get UNIT => 'ES_APPLICATION_DETAILS_UNIT';
  String get UNIT_USAGE_TYPE => 'PT_ASSESSMENT_UNIT_USAGE_TYPE';
  String get SUB_TYPE_RES => 'COMMON_PROPTYPE_';
  String get COMMON_PROPUSGTYPE => 'COMMON_PROPUSGTYPE_';
  String get PROPERTYTAX_OCCUPANCYTYPE => 'PROPERTYTAX_OCCUPANCYTYPE_';
  String get PT_OWNERSHIP => 'PT_OWNERSHIP_';
  String get UNIT_OCCUPANY_TYPE => 'PT_OCCUPANY_TYPE_LABEL';
  String get UNIT_BUILTUP_AREA => 'PT_BUILTUP_AREA_LABEL';
  String get OWNERSHIP_DETAILS_HEADER =>
      'PT_COMMON_PROPERTY_OWNERSHIP_DETAILS_HEADER';
  String get OWNER_HISTORY => 'PT_OWNER_HISTORY';
  String get OWNER_APPLICANT_NAME_LABEL => 'PT_COMMON_APPLICANT_NAME_LABEL';
  String get OWNER_GENDER => 'PT_COMMON_GENDER_LABEL';
  String get OWNER_EMAIL => 'PT_MUTATION_AUTHORISED_EMAIL';
  String get SPECIAL_CATEGORY => 'PT_SPL_CAT';
  String get FILE_GRIEVANCE => 'PT_PGR';
  String get UPDATE_PROPERTY => 'PT_UPDATE_PROPERTY_BUTTON';
  String get SELF_ASSES => 'PT_SELF_ASSES_PROPERTY';
  String get MOBILE_NUMBER => 'PT_FORM3_MOBILE_NUMBER';
  String get GUARDIAN_NAME => 'PT_FORM3_GUARDIAN_NAME';
  String get RELATIONSHIP => 'PT_FORM3_RELATIONSHIP';

  String get MY_APPLICATIONS => 'CS_TITLE_MY_APPLICATIONS';
  String get TRACK => 'CS_CF_TRACK';
  String get APPLICATION_NO => 'PT_APPLICATION_NO_LABEL';
  String get APPLICATION_CATEGORY => 'PT_APPLICATION_CATEGORY';
  String get PTUID => 'PT_SEARCHPROPERTY_TABEL_PTUID';
  String get APP_TYPE => 'PT_COMMON_TABLE_COL_APP_TYPE';
  String get PT_TAX => 'PROPERTY_TAX';
  String get PT => 'PT.';
  String get PT_COMMON => 'PT_COMMON_';
  String get NO_BILLS_FOUND => 'CS_BILLS_TEXT_NO_BILLS_FOUND';

  //Helpdesk Benefits
  String get PROPERTIES_REGISTERED => 'PROPERTIES_REGISTERED_IN_LAST_12_MONTHS';
  String get APPLICATION_PROCESSED => 'APPLICATION_PROCESSED_IN_LAST_12_MONTHS';
  String get APPLICATION_PROCESSING => 'APPLICATION_PROCESSING_TIME';
  String get PT_COMMON_DAYS => 'COMMON_DAYS';
  String get APPLICATION_PROCESSING_FEE => 'APPLICATION_PROCESSING_FEE';

  //My applications
  String get APPLICATION_DETAILS => 'PT_MUTATION_APPLICATION_DETAILS';
  String get APPLICATION_NUMBER_LABEL => 'PT_APPLICATION_NUMBER_LABEL';
  String get APPLICATION_CHANNEL_LABEL => 'PT_APPLICATION_CHANNEL_LABEL';
  String get APPLICATION_CHANNEL_RES =>
      'ES_APPLICATION_DETAILS_APPLICATION_CHANNEL_';

  String get PROPERTY_ADDRESS_COLONY_NAME => 'PT_PROPERTY_ADDRESS_COLONY_NAME';
  String get ASSESMENT1_ELECTRICITY_NUMBER =>
      'PT_ASSESMENT1_ELECTRICITY_NUMBER';
  String get ASSESMENT1_ELECTRICITY_UID => 'PT_ASSESMENT1_ELECTRICITY_UID';
  String get STRUCTURE_TYPE_LABEL => 'PT_STRUCTURE_TYPE_LABEL';
  String get AGE_OF_PROPERTY_LABEL => 'PT_AGE_OF_PROPERTY_LABEL';

  String get FORM2_TOTAL_ANNUAL_RENT => 'PT_FORM2_TOTAL_ANNUAL_RENT';
  String get TRANSFEROR_SPECIAL_CATEGORY =>
      'PT_MUTATION_TRANSFEROR_SPECIAL_CATEGORY';

  String get PT_MUTATION_PENDING_COURT => 'PT_MUTATION_PENDING_COURT';
  String get PT_DETAILS_COURT_CASE => 'PT_DETAILS_COURT_CASE';
  String get PT_PROP_UNDER_GOV_ACQUISITION => 'PT_PROP_UNDER_GOV_AQUISITION';
  String get PT_DETAILS_GOV_ACQUISITION => 'PT_DETAILS_GOV_AQUISITION';

  String get PT_MUTATION_DETAILS => 'PT_MUTATION_DETAILS';
  String get PT_REGISTRATION_DETAILS => 'PT_REGISTRATION_DETAILS';

  String get PT_REASON_PROP_TRANSFER => 'PT_REASON_PROP_TRANSFER';
  String get PT_PROP_MARKET_VALUE => 'PT_PROP_MARKET_VALUE';
  String get PT_REG_NUMBER => 'PT_REG_NUMBER';
  String get PT_DOC_ISSUE_DATE => 'PT_DOC_ISSUE_DATE';
  String get PT_REG_DOC_VALUE => 'PT_REG_DOC_VALUE';
  String get PT_REMARKS => 'PT_REMARKS';

  //My payments
  String get PAYMENT_AMOUNT_PAID => 'CS_PAYMENT_AMOUNT_PAID_WITHOUT_SYMBOL';
  String get PAYMENT_PROPERTY_ID => 'PT_SEARCHPROPERTY_TABEL_PID';
  String get PAYMENT_OWNER_NAME => 'PT_OWNERS_NAME';
  String get PAYMENT_RECEIPT_DATE => 'PT_RECEIPT_DATE_LABEL';
  String get PAYMENT_RECEIPT_NO => 'PT_RECEIPT_NO_LABEL';
  String get PAYMENT_DOWNLOAD_RECEIPT => 'PT_DOWNLOAD_RECEIPT';
  String get COMMON_DOWNLOAD_RECEIPT => 'COMMON_DOWNLOAD_RECEIPT';

  //My Pt Bills
  String get MY_BILLS => 'CS_TITLE_MY_BILLS';
  String get PAYMENT_OVERDUE => 'CS_PAYMENT_OVERDUE';
  String get COMMON_DAYS => 'CS_COMMON_DAYS';
  String get CS_OWNER_NAME => 'CS_OWNER_NAME';
  String get PROPERTY_ADDRESS => 'PT_PROPERTY_ADDRESS';
  String get DUE_DATE => 'PT_DUE_DATE';
  String get PAYMENT_BILL_DETAILS => 'CS_PAYMENT_BILL_DETAILS';
  String get PT_UNIQUE_PROPERTY_ID => 'PT_UNIQUE_PROPERTY_ID';
  String get PAYMENT_BILLING_PERIOD => 'CS_PAYMENT_BILLING_PERIOD';
  String get PAYMENT_TOTAL_AMOUNT => 'CS_PAYMENT_TOTAL_AMOUNT';
  String get CS_BILL_PERIOD => 'CS_BILL_PERIOD';
  String get TL_COMMON_TOTAL_AMT => 'TL_COMMON_TOTAL_AMT';

  String get PT_FEE_AMOUNT => 'PT_FEE_AMOUNT';
  String get PT_PAYMENT_STATUS => 'PT_PAYMENT_STATUS';
  String get PT_MUT_BILL => 'PT_MUT_BILL_';

  //Payment history
  String get PT_PAYMENT_HISTORY => 'PT_PAYMENT_HISTORY';
  String get NO_PAYMENTS_HISTORY => 'PT_NO_PAYMENTS_HISTORY';

  // PT_PROPERTY_PTUID
  String get PT_HISTORY_BILL_PERIOD => 'PT_HISTORY_BILL_PERIOD';
  String get PT_HISTORY_BILL_NO => 'PT_HISTORY_BILL_NO';
  String get PT_HISTORY_RECEIPT_NO => 'PT_HISTORY_RECEIPT_NO';
  String get PT_HISTORY_PAYMENT_DATE => 'PT_HISTORY_PAYMENT_DATE';
  String get PT_HISTORY_AMOUNT_PAID => 'PT_HISTORY_AMOUNT_PAID';
  String get PT_HISTORY_PAYMENT_STATUS => 'PT_HISTORY_PAYMENT_STATUS';

  // PT_DOWNLOAD_RECEIPT
  String get MT_APPLICATION => 'MT_APPLICATION';
  String get PTUPNO_HEADER => 'PTUPNO_HEADER';
  String get PTUPNO_OWNER_NAME => 'PTUPNO_OWNER_NAME';
  String get PTUPNO_CURR_NO => 'PTUPNO_CURR_NO';
  String get PT_UPDATE_NEWNO => 'PT_UPDATE_NEWNO';
  String get PTUPNO_SENDOTP => 'PTUPNO_SENDOTP';

  String get PT_DATE_OF_TRANSFER => 'PT_DATE_OF_TRANSFER';
  String get PT_SPECIAL_OWNER_CATEGORY => 'PT_SPECIAL_OWNER_CATEGORY';
  String get NO_DOCUMENTS_FOUND => 'PT_NO_DOCUMENTS_MSG';
  String get PROPERTYTAX_BILLING_SLAB => 'PROPERTYTAX_BILLING_SLAB_';
  String get WF_PT => 'WF_PT_';

  String get FLOORS_MISSING_UNITS => 'PT_FLOORS_MISSING_UNITS';

  /* -------------------------------------------------------------------------- */
  /*                                 For Employe                                */
  /* -------------------------------------------------------------------------- */
  String get EMP_PT_STATUS => 'ES_PT_COMMON_STATUS_';
  String get EMP_PT_TITLE => 'ES_TITLE_PROPERTY_TAX';
  String get EMP_HOUSE_NO => 'PT_PROPERTY_ADDRESS_HOUSE_NO';
  String get EMP_NEW_ENUMERATION => 'ES_TITLE_NEW_PROPERTY_APPLICATION';
  String get EMP_LOCALITY => 'PT_LOCALITY_LABEL';
  String get EMP_PROPERTY_ASSESSMENT =>
      'ES_NEW_APPLICATION_PROPERTY_ASSESSMENT';
  String get EMP_USE => 'PT_ASSESMENT_INFO_USAGE_TYPE';
  String get EMP_PROPERTY_TYPE => 'PT_ASSESMENT_INFO_TYPE_OF_BUILDING';
  String get EMP_AREA_SQ_FT => 'PT_PLOT_SIZE_SQUARE_FEET_LABEL';
  String get EMP_ELECTRICITY_ID => 'PT_ELECTRICITY_LABEL';
  String get EMP_UID => 'PT_ELECTRICITY_UID_LABEL';
  String get EMP_STRUCTURE_TYPE => 'PT_STRUCTURE_TYPE';
  String get EMP_AGE_OF_PROPERTY => 'PT_AGE_OF_PROPERTY';
  String get EMP_PROVIDE_OWNERSHIP_DETAIL => 'PT_PROVIDE_OWNERSHIP_DETAILS';
  String get EMP_OWNER_NAME => 'PT_OWNER_NAME';
  String get EMP_GENDER => 'PT_FORM3_GENDER';
  String get EMP_MOBILE_NUMBER => 'PT_FORM3_MOBILE_NUMBER';
  String get EMP_GUARDIAN_NAME => 'PT_SEARCHPROPERTY_TABEL_GUARDIANNAME';
  String get EMP_RELATIONSHIP => 'PT_FORM3_RELATIONSHIP';
  String get EMP_SPECIAL_CATEGORY => 'PT_FORM3_SPECIAL_CATEGORY';
  String get EMP_EMAIL => 'PT_OWNERSHIP_INFO_EMAIL_ID';
  String get EMP_OWNER_ADDRESS => 'PT_OWNERSHIP_INFO_CORR_ADDR';
  String get EMP_INSTITUTION_NAME => 'PT_INSTITUTION_NAME';
  String get EMP_INSTITUTION_TYPE => 'PT_INSTITUTION_TYPE';
  String get EMP_LANDLINE_NUMBER => 'PT_LANDLINE_NUMBER_FLOATING_LABEL';
  String get EMP_DESIGNATION => 'TL_NEW_DESIG_OWNER_LABEL';
  String get EMP_DOCUMENTS_REQUIRED => 'ES_NEW_APPLICATION_DOCUMENTS_REQUIRED';
  String get EMP_USAGEPROOF => 'OWNER_USAGEPROOF';
  String get EMP_OCCUPANCY_PROOF => 'OWNER_OCCUPANCYPROOF';
  String get EMP_CONSTRUCTION_PROOF => 'OWNER_CONSTRUCTIONPROOF';
  String get EMP_REGISTRATION_PROOF => 'OWNER_REGISTRATIONPROOF';
  String get EMP_SELECT_FLOOR => 'PT_FORM2_SELECT_FLOOR';
  String get EMP_USAGE_TYPE => 'PT_PROPERTY_DETAILS_USAGE_TYPE_HEADER';
  String get EMP_UNIT_USAGE_TYPE => 'PT_FORM2_USAGE_TYPE';
  String get EMP_OCCUPANCY => 'PT_FORM2_OCCUPANCY';
  String get EMP_BUILT_AREA => 'PT_FORM2_BUILT_AREA';
  String get EMP_ADD_MORE_UNIT => 'PT_ADD_UNIT';
  String get EMP_RESPONSE_ACTION => 'ES_PT_RESPONSE_CREATE_ACTION';
  String get EMP_RESPONSE_LABEL => 'ES_PT_RESPONSE_CREATE_LABEL';
  String get EMP_RESPONSE_CREATE_DISPLAY => 'ES_PT_RESPONSE_CREATE_DISPLAY';

  String get PT_PROPERTY_APPLICATION_NO => 'PT_PROPERTY_APPLICATION_NO';
  String get SEARCH_UNIQUE_PROPERTY_ID => 'ES_SEARCH_UNIQUE_PROPERTY_ID';
  String get SEARCH_APPLICATION_MOBILE_NO => 'ES_SEARCH_APPLICATION_MOBILE_NO';
}

class Building {
  const Building();
  //Details
  String get PLOT_AREA => 'BPA_BOUNDARY_PLOT_AREA_LABEL';
  String get BOUNDARY_WALL_LEN => 'BPA_BOUNDARY_WALL_LENGTH_LABEL';
  String get SCRUTINY_DETAILS => 'BPA_STEPPER_SCRUTINY_DETAILS_HEADER';
  String get EDCR_NUMBER => 'BPA_EDCR_NO_LABEL';
  String get BPA_BLOCK_SUB => 'BPA_BLOCK_SUBHEADER ';
  String get OCCUPANCY_TABLE => 'BPA_TABLE_COL_OCCUPANCY';
  String get BUILDUP => 'BPA_TABLE_COL_BUILDUPAREA';
  String get FLOORAREA => 'BPA_TABLE_COL_FLOORAREA';
  String get FLOOR_NAME_0 => 'BPA_FLOOR_NAME_0';
  String get FLOOR_NAME_1 => 'BPA_FLOOR_NAME_1';
  String get PINCODE => 'BPA_DETAILS_PIN_LABEL';
  String get CITY => 'BPA_CITY_LABEL';
  String get STREET => 'BPA_DETAILS_SRT_NAME_LABEL';
  String get GENDER => 'BPA_APPLICANT_GENDER_LABEL';
  String get PRIMARY_OWNER => 'BPA_IS_PRIMARY_OWNER_LABEL';
  String get NOC_DETAILS => 'BPA_NOC_DETAILS_SUMMARY';
  String get BLOCK_SUBHEADER => 'BPA_BLOCK_SUBHEADER';
  String get CARPETAREA => 'BPA_TABLE_COL_CARPETAREA';
  String get APPLICATION => 'BPA_MY_APPLICATIONS';
  String get BPA_FLOOR => 'BPA_FLOOR_NAME_';
  String get BPA_FEE_DETAILS => 'BPA_FEE_DETAILS_LABEL';
  String get BPA_APPL_FEES_DETAILS => 'BPA_APPL_FEES_DETAILS';
  String get BPA_APPL_FEES => 'BPA_APPL_FEES';
  String get BPA_STATUS_LABEL => 'BPA_STATUS_LABEL';
  String get BPA_TOT_AMT_PAID => 'BPA_TOT_AMT_PAID';
  String get INSPECTION_REPORT => 'BPA_FI_REPORT';
  String get BPA_FEES_DETAILS => 'BPA_LOW_SANC_FEES_DETAILS';
  String get SANC_FEES => 'BPA_LOW_SANC_FEES';
  String get BPA_APP_STATUS_PREF => 'WF_BPA_';
  String get BPA_FLOOR_NAME => 'BPA_FLOOR_NAME_';
  String get BPA_SERVICE_TYPE => 'BPA_BASIC_DETAILS_SERVICE_TYPE_LABEL';
  String get OCCUPANCY_TYPE => 'BPA_BASIC_DETAILS_OCCUPANCY_LABEL';
  String get APPLICATION_TYPE => 'BPA_BASIC_DETAILS_APPLICATION_TYPE_LABEL';
  String get BUILDING_PLAN_SCRUTINY => 'BUILDING_PLAN_SCRUTINY';
  String get STATUS => 'TL_COMMON_TABLE_COL_STATUS';
  String get APPLICATION_NUMBER => 'BPA_APPLICATION_NUMBER_LABEL';
  String get BPA_SQ_FT_LABEL => 'BPA_SQ_FT_LABEL';
  String get BPA_SQ_MTRS_LABEL => 'BPA_SQ_MTRS_LABEL';
  String get INSPECTION_DATE => 'BPA_FI_DATE_LABEL';
  String get INSPECTION_TIME => 'BPA_FI_TIME_LABEL';
  String get INSPECTION_CHECKLIST => 'BPA_CHECK_LIST_DETAILS';
  String get INSPECTION_DOCUMENTS => 'BPA_FIELD_INSPECTION_DOCUMENTS';
  String get INSPECTION_REMARKS => 'BPA_ENTER_REMARKS';
  //MyApplication BPA Details

  String get BASIC_DETAILS => 'BPA_BASIC_DETAILS_TITLE';
  String get APPLICATION_DATE => 'BPA_BASIC_DETAILS_APP_DATE_LABEL';
  String get RISK_TYPE => 'BPA_BASIC_DETAILS_RISK_TYPE_LABEL';
  String get SAN_FEE_RECEIPT => 'BPA_SAN_FEE_RECEIPT';

  String get PLOT_DETAILS => 'BPA_PLOT_DETAILS_TITLE';
  String get PLOT_NUMBER => 'BPA_PLOT_NUMBER_LABEL';
  String get KHATA_NUMBER => 'BPA_KHATHA_NUMBER_LABEL';
  String get HOLDING_NUM => 'BPA_HOLDING_NUMBER_LABEL';
  String get LAND_REGIS_DETAIL => 'BPA_BOUNDARY_LAND_REG_DETAIL_LABEL';
  String get EDCR_DETAILS => 'BPA_EDCR_DETAILS';
  String get UPLOADED_PLAN_DIAG => 'BPA_UPLOADED_PLAN_DIAGRAM';
  String get SCRUNITY_REPORT_OUTPUT => 'BPA_SCRUNTINY_REPORT_OUTPUT';
  String get PROPOSED_BUILDING_ABS => 'BPA_BUILDING_EXTRACT_HEADER';
  String get TOTAL_BUILDUP_AREA => 'BPA_TOTAL_BUILT_UP_AREA_HEADER';
  String get NUMBER_FLOOR => 'BPA_SCRUTINY_DETAILS_NUMBER_OF_FLOORS_LABEL';
  String get HEIGHT_FROM_GROUND => 'BPA_HEIGHT_FROM_GROUND_LEVEL';
  String get BLOCKWISE_OCCUPANCY => 'BPA_OCC_SUBOCC_HEADER';
  String get SUB_OCCUPANCY => 'BPA_OCC_SUBOCC_HEADER';
  String get FLOOR => 'BPA_TABLE_COL_FLOOR';
  String get LEVEL => 'BPA_TABLE_COL_LEVEL';
  String get DEMOLITION_DETAILS => 'BPA_APP_DETAILS_DEMOLITION_DETAILS_LABEL';
  String get DEMOLITION_AREA => 'BPA_APPLICATION_DEMOLITION_AREA_LABEL';
  String get LOCATION_DETAILS => 'BPA_NEW_TRADE_DETAILS_HEADER_DETAILS';
  String get LOCALITY => 'BPA_LOC_MOHALLA_LABEL';
  String get LANDMARK => 'ES_NEW_APPLICATION_LOCATION_LANDMARK';
  String get OWNER_DETAILS => 'BPA_APPLICANT_DETAILS_HEADER';
  String get FIRE_NOC_APPLI => 'BPA_FIRE_NOC_LABEL';
  String get NOC_STATUS => 'BPA_NOC_STATUS';
  String get AIRPORT_NOC => 'BPA_AIRPORT_AUTHORITY_HEADER';
  String get NOC_DATE => 'BPA_SUDMITTED_ON_LABEL';
  String get NOC_DOCUMENT => 'BPA_DOCUMENT_DETAILS_LABEL';
  String get AIRPORT_NOC_APPLI => 'BPA_AIRPORT_AUTHORITY_LABEL';
  String get DOCUMENT_DETAILS => 'BPA_DOCUMENT_DETAILS_LABEL';
  String get BPA_SUB_OCCUPANCY_LABEL => 'BPA_SUB_OCCUPANCY_LABEL';
  String get PERMIT_APP_NUMBER => 'BPA_PERMIT_APP_NUMBER';
  String get PERMIT_VALIDITY => 'BPA_PERMIT_VALIDITY';
  String get OC_PERMIT_NUMBER_LABEL => 'BPA_OC_PERMIT_NUMBER_LABEL';
  String get OC_PERMIT_VALIDITY => 'BPA_OC_PERMIT_VALIDITY';

  String get I_AGREE => 'BPA_I_AGREE_THE_LABEL';
  String get TERMS_AND_CONDITIONS => 'BPA_TERMS_AND_CONDITIONS_LABEL';
  String get CITIZEN_DECLARATION_LABEL_1 => 'BPA_CITIZEN_1_DECLARAION_LABEL';
  String get CITIZEN_DECLARATION_LABEL_2 => 'BPA_CITIZEN_2_DECLARAION_LABEL';
  String get GO_BACK => 'BPA_GO_BACK_LABEL';
  String get BPA_FORWARD_APPLICATION_HEADER => 'BPA_FORWARD_APPLICATION_HEADER';
  String get ES_OBPS_ACTION_COMMENTS => 'ES_OBPS_ACTION_COMMENTS';
}

class BuildingReg {
  const BuildingReg();
  String get SLA_DAYS => 'BPA_COMMON_SLA';
  String get SERVICE_TYPE => 'BPA_COMMON_SERVICE';
}

class BuildingPg {
  const BuildingPg();
//String get INSPECTION_REPORT => 'BPA_FI_REPORT';
}

class WaterSewerage {
  const WaterSewerage();
  String get MODULE_WS => 'MODULE_WS';
  String get MY_APPLICATION => 'ACTION_TEXT_WS_MY_APPLICATION';
  String get HOME_MY_APPLICATION => 'CS_HOME_MY_APPLICATIONS';
  String get MY_BILLS => 'ACTION_TEST_WNS_MY_BILLS';
  String get MY_PAYMENTS => 'ACTION_TEST_MY_PAYMENTS';
  String get CONNECTIONS_PROPOSED => 'WS_NO_OF_CONNECTIONS_PROPOSED_LABEL';
  String get PROPOSED_PIPE_SIZE => 'WS_PROPOSED_PIPE_SIZE';
  String get WS_NO_WATER_CLOSETS_LABEL => 'WS_NO_WATER_CLOSETS_LABEL';
  String get WS_TOILETS_LABEL => 'WS_PROPOSED_WATER_TOILETS_LABEL';

  String get ESTIMATION_NOTICE => 'WS_ESTIMATION_NOTICE';
  String get APPLICATION => 'WS_APPLICATION';
  String get DISCONNECTION_NOTICE => 'WS_DISCONNECTION_NOTICE_LABEL';

  String get APPLICATION_NO => 'WS_MYCONNECTIONS_APPLICATION_NO';
  String get SERVICE_NAME => 'WS_SERVICE_NAME';
  String get CONSUMER_NAME => 'WS_CONSUMER_NAME';
  String get PROPERTY_ID => 'WS_PROPERTY_ID';
  String get STATUS => 'WS_STATUS';
  String get SLA => 'WS_SLA';
  String get PROPERTY_ADDRESS => 'WS_PROPERTY_ADDRESS';
  String get VIEW_DETAILS => 'WS_VIEW_DETAILS_LABEL';
  String get AMT_DUE_LABEL => 'WS_COMMON_TABLE_COL_AMT_DUE_LABEL';
  String get SERVICE_NAME_LABEL => 'WS_SERVICE_NAME_LABEL';
  String get APPLICATION_TYPE => 'WS_APPLICATION_TYPE_';
  String get APPLICATION_STATUS => 'WS_COMMON_TABLE_COL_APPLICATION_STATUS';
  String get DOCUMENT_DETAILS => 'WS_COMMON_DOCUMENT_DETAILS';
  String get WS_APPLICATION_TYPE_ => 'WS_APPLICATION_TYPE_';

  String get APPLICATION_DETAILS_HEADER => 'WS_APPLICATION_DETAILS_HEADER';
  String get FEE_DETAILS_HEADER => 'WS_FEE_DEATAILS_HEADER';
  String get ROAD_CUTTING_CHARGE_BERMCUTTINGKATCHA =>
      'WS_ROAD_CUTTING_CHARGE_BERMCUTTINGKATCHA';
  String get TOTAL_AMOUNT_DUE => 'WS_TOTAL_AMOUNT_DUE';
  String get PROPERTY_DETAILS => 'WS_COMMON_PROPERTY_DETAILS';
  String get PROPERTY_ID_LABEL => 'WS_PROPERTY_ID_LABEL';
  String get CONSUMER_NAME_LABEL => 'WS_OWN_DETAIL_OWN_NAME_LABEL';
  String get CONSUMER_GENDER_LABEL => 'WS_OWN_DETAIL_GENDER_LABEL';
  String get CONSUMER_MOBILE_LABEL => 'WS_OWN_DETAIL_MOBILE_NO_LABEL';
  String get CONSUMER_FATHER_OR_HUSBAND_LABEL =>
      'WS_OWN_DETAIL_FATHER_OR_HUSBAND_NAME';
  String get CONSUMER_RELATION_LABEL => 'WS_OWN_DETAIL_RELATION_LABEL';
  String get CONSUMER_ADDRESS_LABEL => 'WS_OWN_DETAIL_CROSADD';
  String get CONSUMER_OWNER_LABEL => 'WS_OWN_DETAIL_SPECIAL_APPLICANT_LABEL';
  String get CONSUMER_EMAIL_LABEL => 'WS_OWN_EMAIL_IDNO_LABEL';
  String get COMMON_MASTERS_OWNERTYPE_ => 'COMMON_MASTERS_OWNERTYPE_';
  String get VIEW_PROPERTY => 'WS_VIEW_PROPERTY';
  String get CONNECTION_HOLDER_DETAILS_HEADER =>
      'WS_COMMON_CONNECTION_HOLDER_DETAILS_HEADER';
  String get WS_CONN_HOLDER_SAME_AS_OWNER_DETAILS =>
      'WS_CONN_HOLDER_SAME_AS_OWNER_DETAILS';
  String get PROPERTY_OWNER_SAME_AS_CONN_HOLDERS =>
      'WS_PROPERTY_OWNER_SAME_AS_CONN_HOLDERS';
  String get NO_OF_TAPS => 'WS_TASK_DETAILS_CONN_DETAIL_NO_OF_TAPS_PROPOSED';
  String get PIPE_SIZE => 'WS_SERV_DETAIL_PIPE_SIZE';
  String get ADDITIONAL_DETAILS => 'WS_ADDITIONAL_DETAILS';

  String get ADDN_DETAILS => 'WS_COMMON_ADDN_DETAILS';
  String get CONNECTION_DETAIL => 'WS_COMMON_CONNECTION_DETAIL';
  String get CONNECTION_TYPE => 'WS_COMMON_TABLE_COL_CONNECTIONTYPE_LABEL';
  String get SERV_DETAIL_NO_OF_TAPS => 'WS_SERV_DETAIL_NO_OF_TAPS';
  String get SERV_DETAIL_WATER_CLOSETS => 'WS_NO_OF_WATER_CLOSETS_LABEL';
  String get SERV_DETAIL_NO_OF_TOILETS => 'WS_SERV_DETAIL_NO_OF_TOILETS';
  String get PIPE_SIZE_IN_INCHES_LABE => 'WS_PIPE_SIZE_IN_INCHES_LABEL';
  String get DETAIL_WATER_SOURCE => 'WS_SERV_DETAIL_WATER_SOURCE';
  String get SERV_DETAIL_WATER_SUB_SOURCE => 'WS_SERV_DETAIL_WATER_SUB_SOURCE';

  String get PLUMBER_DETAILS => 'WS_COMMON_PLUMBER_DETAILS';
  String get PLUMBER_PROVIDED_BY => 'WS_ADDN_DETAILS_PLUMBER_PROVIDED_BY';
  String get PLUMBER_SELF => 'WS_PLUMBER_SELF';
  String get PLUMBER_ULB => 'WS_PLUMBER_ULB';

  String get ROAD_CUTTING_DETAILS => 'WS_ROAD_CUTTING_DETAILS';
  String get ROAD_CUTTING_AREA_LABEL => 'WS_ROAD_CUTTING_AREA_LABEL';
  String get ADDN_DETAIL_ROAD_TYPE => 'WS_ADDN_DETAIL_ROAD_TYPE';
  String get ADDN_DETAILS_AREA_LABEL => 'WS_ADDN_DETAILS_AREA_LABEL';
  String get ACTIVATION_DETAILS => 'WS_ACTIVATION_DETAILS';
  String get METER_ID => 'WS_SERV_DETAIL_METER_ID';
  String get METER_INSTALL_DATE => 'WS_ADDN_DETAIL_METER_INSTALL_DATE';
  String get INITIAL_METER_READING => 'WS_ADDN_DETAILS_INITIAL_METER_READING';
  String get INITIAL_METER_READING_LABEL => 'WS_INITIAL_METER_READING_LABEL';
  String get INSTALLATION_DATE_LABEL => 'WS_INSTALLATION_DATE_LABEL';
  String get DETAIL_CONN_EXECUTION_DATE => 'WS_SERV_DETAIL_CONN_EXECUTION_DATE';

  String get WS_NUMBER_WATER_CLOSETS_LABEL => 'WS_NUMBER_WATER_CLOSETS_LABEL';



  // Application charge
  String get APPLICATION_CHARGE => 'WS_TASK_DETAILS_FEE_ESTIMATE';
  String get APPLICATION_FEE => 'WS_APPLICATION_FEE_HEADER';
  String get APPLICATION_SERVICE_FEE => 'WS_SERVICE_FEE_HEADER';
  String get WS_TOTAL_AMT => 'WS_COMMON_TOTAL_AMT';
  String get WS_COMMON => 'WS_COMMON_';

  // My bills
  String get WNS_MY_BILLS => 'CS_TITLE_MY_BILLS';
  String get WNS_SERVICE_TYPE => 'WS_SERVICE_TYPE_';
  String get WNS_AMOUNT_DUE => 'WNS_COMMON_TABLE_COL_AMT_DUE_LABEL';
  String get WNS_SERVICE => 'WNS_MYCONNECTIONS_SERVICE';
  String get WNS_CONSUMER_NO => 'WNS_MYCONNECTIONS_CONSUMER_NO';
  String get WNS_BILLING_PERIOD => 'WNS_BILLING_PERIOD';
  String get WNS_CONSUMER_NAME => 'WNS_CONSUMER_NAME_LABEL';
  String get WNS_ADDRESS => 'WNS_MYCONNECTION_ADDRESS';
  String get WNS_BILL_DUE_DATE => 'WNS_VIEW_BILL_DUE_DATE_LABEL';
  String get WNS_VIEW_DETAILS_AND_PAY => 'WS_VIEW_DETAILS_AND_PAY';
  String get WS_MYCONNECTIONS_CONSUMER_NO => 'WS_MYCONNECTIONS_CONSUMER_NO';

  String get WS_MY_PAYMENTS_HEADER => 'WS_MY_PAYMENTS_HEADER';
  String get CS_PAYMENT_AMOUNT_DUE_WITHOUT_SYMBOL =>
      'CS_PAYMENT_AMOUNT_DUE_WITHOUT_SYMBOL';
  String get WS_CONSUMER_CODE => 'WS_CONSUMER_CODE';
  String get WS_RECEIPT_NO_LABEL => 'WS_RECEIPT_NO_LABEL';
  String get WS_RECEIPT_DATE_LABEL => 'WS_RECEIPT_DATE_LABEL';
  String get WS_PAYMENT_STATUS => 'WS_PAYMENT_STATUS';
  String get WS_DOWNLOAD_RECEIPT => 'WS_DOWNLOAD_RECEIPT';
  String get WS_PLUMBER => 'WS_PLUMBER_';
  String get SAME_PROPERTY_OWNERS => 'WS_SAME_AS_PROPERTY_OWNERS';
  String get WS_ROADTYPE => 'WS_ROADTYPE_';
  String get SANCTION_LETTER => 'WS_SANCTION_LETTER';

  //WS Connections
  String get MYCONNECTIONS_HEADER => 'WS_MYCONNECTIONS_HEADER';
  String get MYCONNECTIONS_CONSUMER_NO => 'WS_MYCONNECTIONS_CONSUMER_NO';
  String get MYCONNECTION_ADDRESS => 'WS_MYCONNECTION_ADDRESS';
  String get MYCONNECTIONS_STATUS => 'WS_MYCONNECTIONS_STATUS';
  String get VIEW_DETAILS_LABEL => 'WS_VIEW_DETAILS_LABEL';
  String get VIEW_CONSUMPTION_LABEL =>
      'WS_CONNECTION_DETAILS_VIEW_CONSUMPTION_LABEL';
  String get CONNECTION_DETAIL_PDF => 'WS_CONNECTION_DETAILS';

  String get WS_STATUS => 'WS_STATUS';

  String get VIEW_CONSUMPTION => 'WS_VIEW_CONSUMPTION';
  String get BILL_BILLING_PERIOD_LABEL => 'WS_VIEW_BILL_BILLING_PERIOD_LABEL';
  String get CONSUMPTION_DETAILS_METER_STATUS_LABEL =>
      'WS_CONSUMPTION_DETAILS_METER_STATUS_LABEL';
  String get CONSUMPTION_DETAILS_LAST_READING_LABEL =>
      'WS_CONSUMPTION_DETAILS_LAST_READING_LABEL';
  String get CONSUMPTION_DETAILS_LAST_READING_DATE_LABEL =>
      'WS_CONSUMPTION_DETAILS_LAST_READING_DATE_LABEL';
  String get CONSUMPTION_DETAILS_CURRENT_READING_LABEL =>
      'WS_CONSUMPTION_DETAILS_CURRENT_READING_LABEL';
  String get CONSUMPTION_DETAILS_CURRENT_READING_DATE_LABEL =>
      'WS_CONSUMPTION_DETAILS_CURRENT_READING_DATE_LABEL';
  String get CONSUMPTION_DETAILS_CONSUMPTION_LABEL =>
      'WS_CONSUMPTION_DETAILS_CONSUMPTION_LABEL';

  /* -------------------------------------------------------------------------- */
  /*                                For employee                                */
  /* -------------------------------------------------------------------------- */
  String get EMP_APP_NO => 'WS_ACK_COMMON_APP_NO_LABEL';
  String get EMP_PROPERTY_ADDRESS => 'WS_PROPERTY_ADDRESS_LABEL';
  String get EMP_EDIT_APPLICATION => 'WS_APP_FOR_WATER_AND_SEWERAGE_EDIT_LABEL';
  String get EMP_ROAD_CUTTING_DETAILS => 'WS_COMMON_ROAD_CUTTING_DETAILS';
  String get EMP_NATURE_CONNECTION => 'WS_SERV_DETAIL_CONN_TYPE';
  String get EMP_CONNECTION_TYPE => 'WS_CONNECTIONTYPE_';
  String get EMP_WATERSOURCE_TYPE => 'WS_SERVICES_MASTERS_WATERSOURCE_';
  String get EMP_WATER_SUB_SOURCE => 'WS_SERV_DETAIL_WATER_SUB_SOURCE';
  String get EMP_PIPE_SIZE => 'WS_PIPE_SIZE_IN_INCHES_LABEL'; //abg module
  String get EMP_PLUMBER_PROVIDED_BY => 'WS_PLUMBER_';
  String get EMP_PLUMBER_LICENSE_NO => 'WS_PLIMBER_LICENSE_NO_LABEL';
  String get EMP_PLUMBER_NAME => 'WS_ADDN_DETAILS_PLUMBER_NAME_LABEL';
  String get EMP_PLUMBER_MOBILE_NO => 'WS_PLUMBER_MOBILE_NO_LABEL';
  String get EMP_ADD_ROAD_TYPE => 'WS_ADD_ROAD_TYPE';
  String get EMP_ROAD_TYPE => 'WS_ROAD_TYPE';
  String get EMP_AREA_SQ_FT => 'WS_AREA_SQ_FT';
}

//fsm
class FsmLocal {
  const FsmLocal();
  String get FSM_APPLICATION => 'CS_FSM_APPLICATION_TITLE_MY_APPLICATION';
  String get FSM_APPLICATION_NO => 'CS_FSM_APPLICATION_APPLICATION_NO';
  String get FSM_SERVICE_CATEGORY => 'CS_FSM_APPLICATION_SERVICE_CATEGORY';
  String get FSM_SERVICE_TITLE => 'CS_TITLE_FSM';
  String get FSM_STATUS => 'CS_COMMON_';

  //fsm details
  String get FSM_APPLICATION_DETAIL =>
      'CS_FSM_APPLICATION_DETAIL_TITLE_APPLICATION_DETAILS';
  String get FSM_REQUEST_NO => 'CS_FILE_DESLUDGING_APPLICATION_NO';
  String get FSM_SOURCE_TITLE => 'ES_APPLICATION_DETAILS_APPLICATION_CHANNEL_';
  String get FSM_APPLICATION_CHANNEL => 'ES_APPLICATION_CHANNEL';
  String get FSM_APPLICANT_NAME => 'ES_APPLICATION_DETAILS_APPLICANT_NAME';
  String get FSM_MOBILE_NO => 'ES_APPLICATION_DETAILS_APPLICANT_MOBILE_NO';
  String get FSM_EMAIL_ID => 'ES_APPLICATION_DETAILS_APPLICANT_EMAIL_ID';
  String get FSM_PROPERTY_ID => 'ES_APPLICATION_DETAILS_PROPERTY_ID';
  String get FSM_PROPERTY_TYPE => 'ES_APPLICATION_DETAILS_PROPERTY_TYPE';
  String get FSM_PROPERTY_TYPE_TITLE => 'PROPERTYTYPE_MASTERS_';
  String get FSM_PROPERTY_SUB_TYPE =>
      'ES_APPLICATION_DETAILS_PROPERTY_SUB-TYPE';
  String get FSM_LOCALITY => 'ES_APPLICATION_DETAILS_LOCATION_LOCALITY';
  String get FSM_STREET_NAME => 'PT_PROPERTY_ADDRESS_STREET_NAME';
  String get FSM_HOUSE_NO => 'PT_PROPERTY_ADDRESS_HOUSE_NO';
  String get FSM_LOCALITY_TITLE => 'PG_CITYA_REVENUE_';
  String get FSM_CITY => 'ES_APPLICATION_DETAILS_LOCATION_CITY';
  String get FSM_PINCODE => 'ES_APPLICATION_DETAILS_LOCATION_PINCODE';
  String get FSM_LANDMARK =>
      'CS_FILE_APPLICATION_PROPERTY_LOCATION_LANDMARK_LABEL';
  String get FSM_SLUM => 'CS_FILE_APPLICATION_PROPERTY_LOCATION_SLUM_LABEL';
  String get FSM_GEOLOCATION => 'ES_APPLICATION_DETAILS_LOCATION_GEOLOCATION';
  String get FSM_PIT_TYPE => 'ES_APPLICATION_DETAILS_PIT_TYPE';
  String get FSM_PIT_TYPE_TITLE => 'PITTYPE_MASTERS_';
  String get FSM_ROAD_WIDTH => 'ES_APPLICATION_DETAILS_ROAD_WIDTH';
  String get FSM_DISTANCE_FROM_ROAD =>
      'ES_APPLICATION_DETAILS_DISTANCE_FROM_ROAD';
  String get FSM_PIT_DIMENSION => 'ES_APPLICATION_DETAILS_PIT_DIMENSION';
  String get FSM_NO_TRIP => 'ES_APPLICATION_DETAILS_PAYMENT_NO_OF_TRIPS';
  String get FSM_AMOUNT_TRIP => 'ES_APPLICATION_DETAILS_AMOUNT_PER_TRIP';
  String get FSM_TOTAL_AMOUNT => 'ES_PAYMENT_DETAILS_TOTAL_AMOUNT';
  String get FSM_ADV_AMOUNT => 'ES_PAYMENT_DETAILS_ADV_AMOUNT';
  String get FSM_DUE_AMOUNT => 'FSM_DUE_AMOUNT_TO_BE_PAID';
  String get FSM_PAYMENT_AMOUNT => 'CS_COMMON_PAYMENT_AMOUNT';
  String get FSM_ASSIGNED_PSSO => 'ES_APPLICATION_DETAILS_ASSIGNED_DSO';
  String get FSM_VEHICLE_NO => 'ES_APPLICATION_DETAILS_VEHICLE_NO';
  String get FSM_VEHICLE_CAPACITY => 'ES_APPLICATION_DETAILS_VEHICLE_CAPACITY';
  String get FSM_SERVICE_DATE => 'ES_APPLICATION_DETAILS_POSSIBLE_SERVICE_DATE';
  String get FSM_LENGTH => 'CS_COMMON_LENGTH';
  String get FSM_BREADTH => 'CS_COMMON_BREADTH';
  String get FSM_DEPTH => 'CS_COMMON_DEPTH';
}

class Challans {
  const Challans();
  String get MY_CHALLAN => 'UC_MY_CHALLANS';
  String get NEW_CHALLAN => 'UC_COMMON_HEADER';
  String get CHALLAN_NO => 'UC_CHALLAN_NO';
  String get OWNER_NAME => 'UC_OWNER_NAME_LABEL';
  String get BILLING_PERIOD => 'UC_BILLING_PERIOD_LABEL';
  String get DUE_DATE => 'UC_DUE_DATE';
  String get UC_BUSINESS_SERVICE => 'BILLINGSERVICE_BUSINESSSERVICE_';
  String get CONSUMER_DETAILS => 'CONSUMERDETAILS';
  String get CONSUMER_NAME => 'UC_CONS_NAME_LABEL';
  String get MOBILE_NUMBER => 'UC_MOBILE_NUMBER';
  String get EMAIL_ID => 'UC_EMAIL_ID';
  String get DOOR_NO => 'UC_DOOR_NO_LABEL';
  String get BUILDING_NAME => 'UC_BLDG_NAME_LABEL';
  String get STREET_NAME => 'UC_SRT_NAME_LABEL';
  String get PIN_CODE => 'UC_PINCODE_LABEL';
  String get MOHALLA => 'UC_MOHALLA_LABEL';
  String get SERVICE_DETAILS => 'SERVICEDETAILS';
  String get CITY => 'UC_CITY_LABEL';
  String get SERVICE_CATEGORY => 'UC_SERVICE_CATEGORY_LABEL';
  String get SERVICE_TYPE => 'UC_SERVICE_TYPE_LABEL';
  String get FROM_DATE => 'UC_FROM_DATE_LABEL';
  String get TO_DATE => 'UC_TO_DATE_LABEL';

  String get BILL_GENERATED_SUCCESS => 'UC_BILL_GENERATED_SUCCESS_MESSAGE';
  String get BILL_GENERATION_MESSAGE => 'UC_BILL_GENERATION_MESSAGE_SUB';

  //EMP
  String get EMP_CHALLAN_NO => 'UC_CHALLAN_NUMBER';
  String get UC_RECIEPT_NUMBER_LABEL => 'UC_RECIEPT_NUMBER_LABEL';
  String get UC_TOTAL_DUE_AMOUT_LABEL => 'UC_TOTAL_DUE_AMOUT_LABEL';
  String get UC_SERVICE_DETAILS_LABEL => 'UC_SERVICE_DETAILS_LABEL';
  String get UC_CONSUMER_DETAILS_LABEL => 'UC_CONSUMER_DETAILS_LABEL';
  String get UC_COMMENT_LABEL => 'UC_COMMENT_LABEL';
  String get UC_BUILDING_NAME => 'UC_BUILDING_NAME_LABEL';
  String get UC_STREET_NAME => 'UC_STREET_NAME_LABEL';
  String get UC_CHALLAN => 'UC_CHALLAN';

  String get UC_CLEAR_SEARCH => 'UC_CLEAR_SEARCH_LABEL';
  String get UC_SEARCH => 'UC_SEARCH_MCOLLECT_HEADER';
  String get UC_SEARCH_HEADER => 'UC_SEARCH_HEADER';
  String get UC_STATUS => 'UC_COMMON_TABLE_COL_STATUS';
}

class Nocs {
  const Nocs();
  //FIRE_NOC Application
  String get NOC_APPLICATION => 'NOC_MY_APPLICATIONS_HEADER';
  String get NOC_BUILDING_NAME => 'NOC_COMMON_TABLE_COL_BUILDING_NAME_LABEL';
  String get NOC_APPLICATION_NO => 'NOC_COMMON_TABLE_COL_APP_NO_LABEL';
  String get NOC_NOC_NO => 'NOC_COMMON_TABLE_COL_NOC_NO_LABEL';
  String get NOC_APPLICANT_NAME => 'NOC_COMMON_TABLE_COL_OWN_NAME_LABEL';
  String get NOC_STATUS => 'NOC_COMMON_TABLE_COL_STATUS_LABEL';
  String get NOC_STATUS_RES => 'WF_FIRENOC_';

  //FIRE_NOC Details
  String get NOC_APP_HEADER => 'NOC_TASK_DETAILS_HEADER';
  String get NOC_FEE_ESTIMATE => 'NOC_FEE_ESTIMATE_HEADER';
  String get NOC_TOTAL_AMOUNT => 'TL_COMMON_TOTAL_AMT';
  String get NOC_DETAILS => 'NOC_NOC_DETAILS_HEADER';
  String get NOC_PROV_FIRE => 'NOC_PROVISIONAL_FIRE_NOC_NO_LABEL';
  String get NOC_PROPERTY_HEADER => 'PROPERTY_DETAILS_HEADER';
  String get NOC_PROPERTY_TYPE => 'NOC_PROPERTY_TYPE_LABEL';
  String get NOC_BUILDING => 'NOC_NAME_OF_BUILDING_LABEL';
  String get NOC_BUILDING_USAGE =>
      'NOC_PROPERTY_DETAILS_BUILDING_USAGE_TYPE_LABEL';
  String get NOC_BUILDING_USAGE_SUBTYPE =>
      'NOC_PROPERTY_DETAILS_BUILDING_USAGE_SUBTYPE_LABEL';
  String get NOC_PROPERTY_LOCATION => 'NOC_PROPERTY_LOCATION_DETAILS_HEADER';
  String get NOC_PROPERTY_ID => 'NOC_PROPERTY_ID_LABEL';
  String get NOC_PROPERTY_CITY => 'NOC_PROPERTY_CITY_LABEL';
  String get NOC_PROPERTY_DOOR =>
      'NOC_SUMMARY_PROPERTY__LOCATION_DOOR_HOUSE_NO_LABEL';
  String get NOC_PROPERTY_COLONY => 'NOC_PROPERTY_DETAILS_BLDG_NAME_LABEL';
  String get NOC_PROPERTY_STREET => 'NOC_PROPERTY_DETAILS_SRT_NAME_LABEL';
  String get NOC_PROPERTY_MOHALLA => 'NOC_PROPERTY_DETAILS_MOHALLA_LABEL';
  String get NOC_PROPERTY_PIN => 'NOC_PROPERTY_DETAILS_PIN_LABEL';
  String get NOC_PROPERTY_FIRESTATION =>
      'NOC_PROPERTY_DETAILS_FIRESTATION_LABEL';
  String get NOC_APPLICANT_MOBILE => 'NOC_APPLICANT_MOBILE_NO_LABEL';
  String get NOC_GENDER => 'NOC_GENDER_LABEL';
  String get NOC_APPLICANT_FATHER => 'NOC_APPLICANT_FATHER_HUSBAND_NAME_LABEL';
  String get NOC_APPLICANT_RELATIONSHIP => 'NOC_APPLICANT_RELATIONSHIP_LABEL';
  String get NOC_APPLICANT_PAN => 'NOC_APPLICANT_PAN_LABEL';
  String get NOC_APPLICANT_CORRESPONDENCE =>
      'NOC_APPLICANT_CORRESPONDENCE_ADDRESS_LABEL';
  String get NOC_SUMMARY_DOCUMENTS => 'NOC_SUMMARY_DOCUMENTS_HEADER﻿';
  String get NOC_PAID_SUCCESS => 'NOC_COMMON_PAID_SUCCESS';
  String get NOC_NOT_PAID => 'NOC_COMMON_NOT_PAID';
  String get FIRENOC_ROUNDOFF => 'FIRENOC_ROUNDOFF';
  String get FIRENOC_FEES => 'FIRENOC_FEES';
  String get FIRENOC_TAXES => 'FIRENOC_TAXES';

  String get PAYMENT_CONSUMER_CODE => 'PAYMENT_COMMON_CONSUMER_CODE';
}
