-- CREATE SEQUENCE seq_egf_budgetcoa
--     START WITH 1
--     INCREMENT BY 1
--     MINVALUE 1
--     NO MAXVALUE
--     CACHE 1;

-- CREATE TABLE egf_budgetcoa
-- (
--     id BIGINT NOT NULL DEFAULT nextval('seq_egf_budgetcoa'),
--     budgethead_id BIGINT NOT NULL,
--     account_code VARCHAR(20) NOT NULL,
--     account_head VARCHAR(255) NOT NULL,
--     createddate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
--     lastmodifieddate TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
--     CONSTRAINT pk_budgetcoa PRIMARY KEY (id),
--     CONSTRAINT fk_budgethead FOREIGN KEY (budgethead_id)
--         REFERENCES egf_budgethead(id) ON DELETE CASCADE
-- );

-- ALTER SEQUENCE seq_egf_budgetcoa OWNED BY egf_budgetcoa.id;
