import { useQuery } from "react-query";
import AccessControlService from "../services/elements/Access";
const useAccessControl = (tenantId) => {
  const getUserRoles = Digit.SessionStorage.get("User")?.info?.roles;

  const roles = getUserRoles?.map((role) => {
    return role.code;
  });
const actions={
  "responseInfo": {
      "apiId": "org.egov.accesscontrol",
      "ver": null,
      "ts": "Wed Aug 16 17:26:24 IST 2023",
      "resMsgId": "uief87324",
      "msgId": "1692186984736|en_IN",
      "status": "200 OK"
  },
  "modules": null,
  "actions": [
      {
          "id": 697,
          "name": "UpdateUserWithoutValidation",
          "url": "/user/users/{id}/_updatenovalidate",
          "displayName": "UserRole Mapping",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "ADMIN",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "Administration.UpdateUserWithoutValidation",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 1556,
          "name": "Home",
          "url": "url",
          "displayName": "Home",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "rainmaker-pgr",
          "enabled": true,
          "serviceCode": "PGR",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "Home",
          "navigationURL": "/",
          "leftIcon": "action:home",
          "rightIcon": ""
      },
      {
          "id": 1801,
          "name": "rainmaker-common-fire-noc",
          "url": "card",
          "displayName": "FIRE-NOC",
          "orderNumber": 3,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "fire-noc/search",
          "leftIcon": "social:people",
          "rightIcon": ""
      },
      {
          "id": 1803,
          "name": "Receipts",
          "url": "url",
          "displayName": "Receipts",
          "orderNumber": 4,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "UC",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "UC",
          "navigationURL": "uc-citizen/search",
          "leftIcon": "image:collections-bookmark",
          "rightIcon": ""
      },
      {
          "id": 1805,
          "name": "Complaints",
          "url": "url",
          "displayName": "Complaints",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "rainmaker-pgr",
          "enabled": true,
          "serviceCode": "PGR",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "Complaints",
          "navigationURL": "/digit-ui/citizen/pgr/complaints",
          "leftIcon": "custom:account-alert",
          "rightIcon": ""
      },
      {
          "id": 1806,
          "name": "PropertyTax",
          "url": "url",
          "displayName": "Property Tax",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "Property Tax",
          "navigationURL": "/digit-ui/citizen",
          "leftIcon": "communication:business",
          "rightIcon": ""
      },
      {
          "id": 1807,
          "name": "TradeLicense",
          "url": "url",
          "displayName": "Trade License",
          "orderNumber": 13,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "TradeLicense",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "TradeLicense",
          "navigationURL": "/digit-ui/citizen/",
          "leftIcon": "places:business-center",
          "rightIcon": ""
      },
      {
          "id": 1814,
          "name": "rainmaker-citizen-complaints",
          "url": "card",
          "displayName": "Complaints",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen",
          "leftIcon": "custom:account-alert",
          "rightIcon": ""
      },
      {
          "id": 1815,
          "name": "rainmaker-citizen-propertytax",
          "url": "card",
          "displayName": "Property Tax",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen",
          "leftIcon": "custom:home-city-outline",
          "rightIcon": ""
      },
      {
          "id": 1816,
          "name": "rainmaker-citizen-tradelicence",
          "url": "card",
          "displayName": "Trade Licence",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/",
          "leftIcon": "custom:trade-license",
          "rightIcon": ""
      },
      {
          "id": 1817,
          "name": "rainmaker-citizen-fire-noc",
          "url": "card",
          "displayName": "FIRE-NOC",
          "orderNumber": 3,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "fire-noc/home",
          "leftIcon": "custom:fire",
          "rightIcon": ""
      },
      {
          "id": 1880,
          "name": "BPAStakeHolderHome",
          "url": "url",
          "displayName": "BPA Stake Holder Home",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "rainmaker-bpa",
          "enabled": true,
          "serviceCode": "BPAREG",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "BPAStakeHolder",
          "navigationURL": "bpastakeholder-citizen/home",
          "leftIcon": "communication:business",
          "rightIcon": ""
      },
      {
          "id": 1883,
          "name": "rainmaker-citizen-wns",
          "url": "card",
          "displayName": "Water & Sewerage",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "wns",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws-home",
          "leftIcon": "custom:water-tap",
          "rightIcon": ""
      },
      {
          "id": 1884,
          "name": "rainmaker-citizen-wns",
          "url": "url",
          "displayName": "Water & Sewerage",
          "orderNumber": 13,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "wns",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "wns",
          "navigationURL": "/digit-ui/citizen/ws-home",
          "leftIcon": "custom:water-tap",
          "rightIcon": ""
      },
      {
          "id": 2059,
          "name": "Create FSM Application",
          "url": "/fsm/v1/_create",
          "displayName": "Apply FSM",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "FSM",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2060,
          "name": "Search FSM Application",
          "url": "/fsm/v1/_search",
          "displayName": "Search  FSM Appliacations",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "FSM",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2061,
          "name": "Update FSM Application",
          "url": "/fsm/v1/_update",
          "displayName": "Update FSM",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "FSM",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2066,
          "name": "Search Vendor/DSO",
          "url": "/vendor/v1/_search",
          "displayName": "Search  Vendor",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "vendor",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2067,
          "name": "FSM Application Audit Search",
          "url": "/fsm/v1/_audit",
          "displayName": "FSM Application Audit serach",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2070,
          "name": "FSM BillingSlab Search",
          "url": "/fsm-calculator/v1/billingSlab/_search",
          "displayName": "FSM BillingSlab Search",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2075,
          "name": "digit-ui FSM FSTPO",
          "url": "card",
          "displayName": "Faecal Sludge Management",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/employee/fstp-inbox",
          "leftIcon": "custom:localShipping",
          "rightIcon": ""
      },
      {
          "id": 2084,
          "name": "FSM Application Charge Payment Search",
          "url": "/collection-services/payments/FSM.TRIP_CHARGES/_search",
          "displayName": "FSM Application Charge Payment Search",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2306,
          "name": "digit-ui FSM",
          "url": "card",
          "displayName": "Faecal Sludge Management",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/",
          "leftIcon": "custom:localShipping",
          "rightIcon": ""
      },
      {
          "id": 2379,
          "name": "Birth Download",
          "url": "/birth-death-services/birth/_download",
          "displayName": "Download",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2380,
          "name": "Death Download",
          "url": "/birth-death-services/death/_download",
          "displayName": "Download",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2381,
          "name": "Birth View Certificate",
          "url": "/birth-death-services/birth/_viewfullcertdata",
          "displayName": "View Certificate",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2382,
          "name": "Death View Certificate",
          "url": "/birth-death-services/death/_viewfullcertdata",
          "displayName": "View Certificate",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2383,
          "name": "Get Hospitals",
          "url": "/birth-death-services/common/gethospitals",
          "displayName": "Get Hospitals",
          "orderNumber": 0,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "",
          "leftIcon": "",
          "rightIcon": ""
      },
      {
          "id": 2386,
          "name": "rainmaker-citizen-birth",
          "url": "card",
          "displayName": "Birth",
          "orderNumber": 8,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "birth-citizen/home",
          "leftIcon": "custom:library-books",
          "rightIcon": ""
      },
      {
          "id": 2391,
          "name": "rainmaker-citizen-death",
          "url": "card",
          "displayName": "death",
          "orderNumber": 8,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "death-citizen/home",
          "leftIcon": "custom:library-books",
          "rightIcon": ""
      },
      {
          "id": 2403,
          "name": "Birth Search Certificate",
          "url": "url",
          "displayName": "Birth Search Certificate",
          "orderNumber": 6,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "birth",
          "navigationURL": "birth-citizen/home",
          "leftIcon": "custom:library-books",
          "rightIcon": ""
      },
      {
          "id": 2404,
          "name": "Death Search Certificate",
          "url": "url",
          "displayName": "Death Search Certificate",
          "orderNumber": 7,
          "queryParams": "",
          "parentModule": "",
          "enabled": true,
          "serviceCode": "Birth-Death",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "death",
          "navigationURL": "death-citizen/home",
          "leftIcon": "custom:library-books",
          "rightIcon": ""
      },
      {
          "id": 2422,
          "name": "TL_FAQ_S",
          "url": "digit-ui-card",
          "displayName": "FAQs",
          "orderNumber": 7,
          "queryParams": "",
          "parentModule": "TL",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/tl-faq",
          "leftIcon": "TLIcon",
          "rightIcon": ""
      },
      {
          "id": 2423,
          "name": "PT_HOW_IT_WORKS",
          "url": "digit-ui-card",
          "displayName": "How It Works",
          "orderNumber": 9,
          "queryParams": "",
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt-how-it-works",
          "leftIcon": "propertyIcon",
          "rightIcon": ""
      },
      {
          "id": 2424,
          "name": "PT_FAQ_S",
          "url": "digit-ui-card",
          "displayName": "FAQs",
          "orderNumber": 8,
          "queryParams": "",
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt-faq",
          "leftIcon": "propertyIcon",
          "rightIcon": ""
      },
      {
          "id": 2425,
          "name": "Firenoc Citizen Home",
          "url": "digit-ui-card",
          "displayName": "FireNoc Search",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "FireNoc",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/citizen/fire-noc/home",
          "leftIcon": "FirenocIcon",
          "rightIcon": ""
      },
      {
          "id": 2426,
          "name": "Birth Certificate Home",
          "url": "digit-ui-card",
          "displayName": "Birth Search",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "Birth",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/citizen/birth-citizen/home",
          "leftIcon": "BirthIcon",
          "rightIcon": ""
      },
      {
          "id": 2427,
          "name": "Death Certificate Home",
          "url": "digit-ui-card",
          "displayName": "Death Search",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "Death",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/citizen/death-citizen/home",
          "leftIcon": "DeathIcon",
          "rightIcon": ""
      },
      {
          "id": 2437,
          "name": "PT_MY_PAYMENTS",
          "url": "digit-ui-card",
          "displayName": "My Payments",
          "orderNumber": 7,
          "queryParams": "",
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt/property/my-payments",
          "leftIcon": "propertyIcon",
          "rightIcon": ""
      },
      {
          "id": 2440,
          "name": "ACTION_TEST_WNS_MY_BILLS",
          "url": "digit-ui-card",
          "displayName": "My Bills",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/my-bills",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2441,
          "name": "ACTION_TEST_MY_PAYMENTS",
          "url": "digit-ui-card",
          "displayName": "My Payments",
          "orderNumber": 6,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/my-payments",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2442,
          "name": "ACTION_TEST_APPLY_NEW_CONNECTION",
          "url": "digit-ui-card",
          "displayName": "Apply for New Connection",
          "orderNumber": 4,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/create-application/docs-required",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2443,
          "name": "ACTION_TEXT_WS_SEARCH_AND_PAY",
          "url": "digit-ui-card",
          "displayName": "Search & Pay",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/search",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2444,
          "name": "ACTION_TEXT_WS_MY_APPLICATION",
          "url": "digit-ui-card",
          "displayName": "My Applications",
          "orderNumber": 5,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/my-applications",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2445,
          "name": "ACTION_TEXT_WS_MY_CONNECTION",
          "url": "digit-ui-card",
          "displayName": "My Connections",
          "orderNumber": 3,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws/my-connections",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2446,
          "name": "UC_SEARCH_AND_PAY",
          "url": "digit-ui-card",
          "displayName": "Search & Pay",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "MCollect",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/mcollect/search",
          "leftIcon": "MCollectIcon",
          "rightIcon": ""
      },
      {
          "id": 2447,
          "name": "UC_MY_CHALLANS",
          "url": "digit-ui-card",
          "displayName": "My Challans",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "MCollect",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/mcollect/My-Challans",
          "leftIcon": "MCollectIcon",
          "rightIcon": ""
      },
      {
          "id": 2448,
          "name": "CS_HOME_APPLY_FOR_DESLUDGING",
          "url": "digit-ui-card",
          "displayName": "Apply for Emptying of Septic Tank/Pit",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "FSM",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/fsm/new-application",
          "leftIcon": "FSMIcon",
          "rightIcon": ""
      },
      {
          "id": 2449,
          "name": "CS_HOME_MY_APPLICATIONS",
          "url": "digit-ui-card",
          "displayName": "My Applications",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "FSM",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/fsm/my-applications",
          "leftIcon": "FSMIcon",
          "rightIcon": ""
      },
      {
          "id": 2450,
          "name": "CS_COMMON_FILE_A_COMPLAINT",
          "url": "digit-ui-card",
          "displayName": "File a Complaint",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "PGR",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/pgr/create-complaint/complaint-type",
          "leftIcon": "PGRIcon",
          "rightIcon": ""
      },
      {
          "id": 2451,
          "name": "CS_HOME_MY_COMPLAINTS",
          "url": "digit-ui-card",
          "displayName": "My Complaints",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "PGR",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/pgr/complaints",
          "leftIcon": "PGRIcon",
          "rightIcon": ""
      },
      {
          "id": 2452,
          "name": "TL_CREATE_TRADE",
          "url": "digit-ui-card",
          "displayName": "Apply for Trade License",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "TL",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/tl/tradelicence/new-application",
          "leftIcon": "TLIcon",
          "rightIcon": ""
      },
      {
          "id": 2453,
          "name": "TL_RENEWAL_HEADER",
          "url": "digit-ui-card",
          "displayName": "Renew Trade License",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "TL",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/tl/tradelicence/renewal-list",
          "leftIcon": "TLIcon",
          "rightIcon": ""
      },
      {
          "id": 2454,
          "name": "TL_MY_APPLICATIONS_HEADER",
          "url": "digit-ui-card",
          "displayName": "My Applications",
          "orderNumber": 3,
          "queryParams": "",
          "parentModule": "TL",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/tl/tradelicence/my-application",
          "leftIcon": "TLIcon",
          "rightIcon": ""
      },
      {
          "id": 2455,
          "name": "BPA_CITIZEN_HOME_VIEW_APP_BY_CITIZEN_LABEL",
          "url": "digit-ui-card",
          "displayName": "View applications by Citizen",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "OBPS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/obps/my-applications",
          "leftIcon": "OBPSIcon",
          "rightIcon": ""
      },
      {
          "id": 2456,
          "name": "BPA_CITIZEN_HOME_STAKEHOLDER_LOGIN_LABEL",
          "url": "digit-ui-card",
          "displayName": "Register as a Stakeholder",
          "orderNumber": 2,
          "queryParams": "",
          "parentModule": "OBPS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/obps/stakeholder/apply/stakeholder-docs-required",
          "leftIcon": "OBPSIcon",
          "rightIcon": ""
      },
      {
          "id": 2457,
          "name": "BPA_CITIZEN_HOME_ARCHITECT_LOGIN_LABEL",
          "url": "digit-ui-card",
          "displayName": "Registered Architect Login",
          "orderNumber": 3,
          "queryParams": "",
          "parentModule": "OBPS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/obps/home",
          "leftIcon": "OBPSIcon",
          "rightIcon": ""
      },
      {
          "id": 2460,
          "name": "ABG_SEARCH_BILL_COMMON_HEADER",
          "url": "digit-ui-card",
          "displayName": "Search Bills",
          "orderNumber": 1,
          "queryParams": "",
          "parentModule": "Bills",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/bills/billSearch",
          "leftIcon": "BillsIcon",
          "rightIcon": ""
      },
      {
          "id": 2466,
          "name": "PRIVACY_AUDIT_REPORT",
          "url": "digit-ui-card",
          "displayName": "Privacy Audit Report",
          "orderNumber": 7,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/Audit",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2468,
          "name": "MCOLLECT_FAQ_S",
          "url": "digit-ui-card",
          "displayName": "FAQs",
          "orderNumber": 7,
          "queryParams": "",
          "parentModule": "MCollect",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/mcollect-faq",
          "leftIcon": "MCollectIcon",
          "rightIcon": ""
      },
      {
          "id": 2469,
          "name": "WS_FAQ_S",
          "url": "digit-ui-card",
          "displayName": "FAQs",
          "orderNumber": 8,
          "queryParams": "",
          "parentModule": "WS",
          "enabled": true,
          "serviceCode": "",
          "tenantId": "pg",
          "createdDate": null,
          "createdBy": null,
          "lastModifiedDate": null,
          "lastModifiedBy": null,
          "path": "",
          "navigationURL": "/digit-ui/citizen/ws-faq",
          "leftIcon": "WSIcon",
          "rightIcon": ""
      },
      {
          "id": 2470,
          "name": "PT_MY_APPLICATION",
          "url": "digit-ui-card",
          "displayName": "My Applications",
          "orderNumber": 5,
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "code": "",
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt/property/my-applications",
          "leftIcon": "propertyIcon",
          "rightIcon": "",
          "queryParams": "",
          "sidebar": "digit-ui-links",
          "sidebarURL": "/digit-ui/citizen/pt-home"
      },
      {
          "id": 2471,
          "name": "PT_MY_PROPERTIES",
          "url": "digit-ui-card",
          "displayName": "My Properties",
          "orderNumber": 4,
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "code": "",
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt/property/my-properties",
          "leftIcon": "propertyIcon",
          "rightIcon": "",
          "queryParams": "",
          "sidebar": "digit-ui-links",
          "sidebarURL": "/digit-ui/citizen/pt-home"
      },
      {
          "id": 2472,
          "name": "PT_PROPERTY_MUTATION",
          "url": "digit-ui-card",
          "displayName": "Transfer Property Ownership/Mutation",
          "orderNumber": 6,
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "code": "",
          "path": "",
          "navigationURL": "/digit-ui/citizen/pt/property/property-mutation/search-property",
          "leftIcon": "propertyIcon",
          "rightIcon": "",
          "queryParams": "",
          "sidebar": "digit-ui-links",
          "sidebarURL": "/digit-ui/citizen/pt-home"
      },
      {
          "id": 2473,
          "name": "OBPS_FAQ_S",
          "url": "digit-ui-card",
          "displayName": "FAQs",
          "orderNumber": 8,
          "parentModule": "OBPS",
          "enabled": true,
          "serviceCode": "",
          "code": "",
          "path": "",
          "navigationURL": "/digit-ui/citizen/obps-faq",
          "leftIcon": "TLIcon",
          "rightIcon": "",
          "queryParams": "",
          "sidebar": "digit-ui-links",
          "sidebarURL": "/digit-ui/citizen/obps-home"
      },
      {
          "id": 2474,
          "name": "CS_TITLE_MY_BILLS",
          "url": "digit-ui-card",
          "displayName": "My Bills",
          "orderNumber": 2,
          "parentModule": "PT",
          "enabled": true,
          "serviceCode": "",
          "code": "",
          "path": "",
          "navigationURL": "/digit-ui/citizen/payment/my-bills/PT",
          "leftIcon": "propertyIcon",
          "rightIcon": "",
          "queryParams": "",
          "sidebar": "digit-ui-links",
          "sidebarURL": "/digit-ui/citizen/pt-home"
      },{
        "id": 3001,
        "name": "SOR_HOME",
        "url": "digit-ui-card",
        "displayName": "SOR HOME",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sor-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },
     {
        "id": 3011,
        "name": "SOR_LIST",
        "url": "digit-ui-card",
        "displayName": "Schedule Of Rate(List)",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sor-list",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sor-home"
    },
    {
        "id": 3012,
        "name": "SOR_CREATE",
        "url": "digit-ui-card",
        "displayName": "Schedule Of Rate(Create)",
        "orderNumber": 2,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sor-create",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sor-home"
    }, 
    {
        "id": 3013,
        "name": "SOR_DETAILS",
        "url": "digit-ui-card",
        "displayName": "Schedule Of Rate(Details)",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sor-details/:sor_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sor-home"
    }, 
    {
        "id": 3014,
        "name": "SOR_EDIT",
        "url": "digit-ui-card",
        "displayName": "Schedule Of Rate(Update)",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sor-edit/:sor_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sor-home"
    }, 
    {
        "id": 3002,
        "name": "PRJ_HOME",
        "url": "digit-ui-card",
        "displayName": "Project Master Home",
        "orderNumber": 2,
        "queryParams": "",
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "tenantId": "pg",
        "createdDate": null,
        "createdBy": null,
        "lastModifiedDate": null,
        "lastModifiedBy": null,
        "path": "",
        "navigationURL": "/digit-ui/citizen/prj-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",        
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },
    {
        "id": 3021,
        "name": "PRJ_LIST",
        "url": "digit-ui-card",
        "displayName": "PRJ_LIST",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/prj-list",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/prj-home"
    },
    {
        "id": 3022,
        "name": "PRJ_CREATE",
        "url": "digit-ui-card",
        "displayName": "PRJ_CREATE",
        "orderNumber": 2,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/prj-create",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/prj-home"
    }, 
    {
        "id": 3023,
        "name": "PRJ_DETAILS",
        "url": "digit-ui-card",
        "displayName": "PRJ_DETAILS",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/prj-details/:project_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/prj-home"
    }, 
    {
        "id": 3024,
        "name": "PRJ_EDIT",
        "url": "digit-ui-card",
        "displayName": "PRJ_EDIT",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/prj-edit/:project_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/prj-home"
    },
    {
        "id": 3003,
        "name": "SCH_HOME",
        "url": "digit-ui-card",
        "displayName": "SCH_HOME",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sch-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },
     {
        "id": 3031,
        "name": "SCH_LIST",
        "url": "digit-ui-card",
        "displayName": "SCH_LIST",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sch-list",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sch-home"
    },
    {
        "id": 3032,
        "name": "SCH_CREATE",
        "url": "digit-ui-card",
        "displayName": "SCH_CREATE",
        "orderNumber": 2,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sch-create",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sch-home"
    }, 
    {
        "id": 3033,
        "name": "SCH_DETAILS",
        "url": "digit-ui-card",
        "displayName": "SCH_DETAILS",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sch-details/:scheme_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sch-home"
    }, 
    {
        "id": 3034,
        "name": "SCH_EDIT",
        "url": "digit-ui-card",
        "displayName": "SCH_EDIT",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/sch-edit/:scheme_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/sch-home"
    },
    {
        "id": 3004,
        "name": "PM_Home",
        "url": "digit-ui-card",
        "displayName": "PM Home",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/phm-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },
    {
        "id": 3041,
        "name": "PM_CREATE",
        "url": "digit-ui-card",
        "displayName": "PM(Create)",
        "orderNumber": 2,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/phm-create",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/phm-home"
    },
    {
        "id": 3042,
        "name": "PHM_LIST",
        "url": "digit-ui-card",
        "displayName": "PM(List)",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/phm-list",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/phm-home"
    },
    {
        "id": 3043,
        "name": "PHM_DETAILS",
        "url": "digit-ui-card",
        "displayName": "SCH_DETAILS",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/phm-details/:phm_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/phm-home"
    }, 
    {
        "id": 3044,
        "name": "PHM_EDIT",
        "url": "digit-ui-card",
        "displayName": "PHM_EDIT",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/phm-edit/:phm_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/phm-home"
    },
    
    

    {
        "id": 3005,
        "name": "Contaractor Master",
        "url": "digit-ui-card",
        "displayName": "Contaractor Master",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/cm-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },

    {
        "id": 3006,
        "name": "PMA_Home",
        "url": "digit-ui-card",
        "displayName": "PMA Home",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/pma-home",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms-home"
    },
    {
        "id": 3045,
        "name": "PMA_CREATE",
        "url": "digit-ui-card",
        "displayName": "PM(Create)",
        "orderNumber": 2,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/pma-create",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/pma-home"
    },
    {
        "id": 3046,
        "name": "PMA_LIST",
        "url": "digit-ui-card",
        "displayName": "PM(List)",
        "orderNumber": 1,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/pma-list",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/pma-home"
    },
    {
        "id": 3047,
        "name": "PMA_DETAILS",
        "url": "digit-ui-card",
        "displayName": "PMA_DETAILS",
        "orderNumber": 3,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/pma-details/:pma_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/pma-home"
    }, 
    {
        "id": 3048,
        "name": "PMA_EDIT",
        "url": "digit-ui-card",
        "displayName": "PMA_EDIT",
        "orderNumber": 4,
        "parentModule": "WMS",
        "enabled": true,
        "serviceCode": "CITIZEN_SERVICE_WMS",
        "code": "",
        "path": "",
        "navigationURL": "/digit-ui/citizen/wms/pma-edit/:pma_id",
        "leftIcon": "WMSIcon",
        "rightIcon": "",
        "queryParams": "",
        "sidebar": "digit-ui-links",
        "sidebarURL": "/digit-ui/citizen/wms/pma-home"
    },
    


  ]
};
//const actions=async () => await AccessControlService.getAccessControl(roles);
  const response = useQuery(["ACCESS_CONTROL", tenantId], actions,{enabled:roles?true:false});
  return response;
};
export default useAccessControl;
