package org.egov.common.constants;

public class MdmsFeatureConstants {
	
	public static final String TOILET = "Toilet";
	public static final String DOORS = "Doors";
	public static final String FRONT_SETBACK = "FrontSetBack";
	public static final String KITCHEN = "Kitchen";
	public static final String LANDING = "Landing";
	public static final String LIFT = "Lift";
	public static final String NON_HABITATIONAL_DOORS = "Non Habitational Doors";
	public static final String NO_OF_RISER = "NoOfRiser";
	public static final String PARKING = "Parking";
	public static final String PLANTATION = "Plantation";
	public static final String PLINTH_HEIGHT = "PlinthHeight";
	public static final String REAR_SETBACK = "RearSetBack";
	public static final String REQUIRED_TREAD = "RequiredTread";
	public static final String REQUIRED_WIDTH = "RequiredWidth";
	public static final String RISER_HEIGHT = "RiserHeight";
	public static final String ROOM_AREA = "Room Area";
	public static final String ROOM_WISE_DOOR_AREA = "Room Wise Door Area";
	public static final String ROOM_WISE_VENTILATION = "Room Wise Ventilation";
	public static final String COVERAGE = "Coverage";
	public static final String USAGES = "Usages";
	public static final String APPLICATION_TYPE = "ApplicationType";
	public static final String SERVICE_TYPE = "ServiceType";
	public static final String OCCUPANCY_TYPE = "OccupancyType";
	public static final String SUB_OCCUPANCY_TYPE = "SubOccupancyType";
	public static final String EDCR_RULES_FEATURES = "EdcrRulesFeatures";
	public static final String FAR = "Far";
	public static final String BALCONY = "Balcony";
    public static final String BASEMENT = "Basement";
    public static final String BATHROOM = "Bathroom";
    public static final String BATHROOM_WATER_CLOSETS = "BathroomWaterClosets";
    public static final String BLOCK_DISTANCES_SERVICE = "BlockDistancesService";
    public static final String CHIMNEY = "Chimney";
    public static final String EXIT_WIDTH = "ExitWidth";
    public static final String FIRE_STAIR = "FireStair";
    public static final String FIRE_TENDER_MOVEMENT = "FireTenderMovement";
    public static final String GOVT_BUILDING_DISTANCE = "GovtBuildingDistance";
    public static final String GUARD_ROOM = "GuardRoom";
    public static final String HEAD_ROOM = "HeadRoom";
    public static final String LAND_USE = "LandUse";
    public static final String INTERIOR_OPEN_SPACE_SERVICE = "InteriorOpenSpaceService";
    public static final String MEZZANINE_FLOOR_SERVICE = "MezzanineFloorService";
    public static final String MONUMENT_DISTANCE = "MonumentDistance";
    public static final String OVERHEAD_ELECTRICAL_LINE_SERVICE = "OverheadElectricalLineService";
    public static final String OVERHANGS = "OverHangs";
    public static final String PARAPET = "Parapet";
    public static final String PASSAGE_SERVICE = "PassageService";
    public static final String PLANTATION_GREEN_STRIP = "PlantationGreenStrip";
    public static final String PLOT_AREA = "PlotArea";
    public static final String PORTICO_SERVICE = "PorticoService";
    public static final String RAIN_WATER_HARVESTING = "RainWaterHarvesting";
    public static final String RAMP_SERVICE = "RampService";
    public static final String RIVER_DISTANCE = "RiverDistance";
    public static final String ROAD_WIDTH = "RoadWidth";
    public static final String ROOF_TANK = "RoofTank";
    public static final String SEGREGATED_TOILET = "SegregatedToilet";
    public static final String SEPTIC_TANK = "SepticTank";
    public static final String SOLAR = "Solar";
    public static final String SPIRAL_STAIR = "SpiralStair";
    public static final String STAIR_COVER = "StairCover";
    public static final String STORE_ROOM = "StoreRoom";
    public static final String TERRACE_UTILITY_SERVICE = "TerraceUtilityService";
    public static final String TRAVEL_DISTANCE_TO_EXIT = "TravelDistanceToExit";
    public static final String VEHICLE_RAMP = "VehicleRamp";
    public static final String VENTILATION = "Ventilation";
    public static final String VERANDAH = "Verandah";
    public static final String WATER_CLOSETS = "WaterClosets";
    public static final String WATER_TANK_CAPACITY = "WaterTankCapacity";
    public static final String SANITATION = "Sanitation";
    public static final String SIDE_YARD_SERVICE = "SideYardService";
    public static final String EDCR_MASTER_CONFIG = "EdcrMasterConfig";
    public static final String RISK_TYPE_COMPUTATION = "RiskTypeComputation"; 
    public static final String RESIDENTIAL = "residential"; 
    public static final String COMMERCIAL = "commercial"; 
    public static final String APARTMENT_FLAT = "apartment/flat"; 
    public static final String INDUSTRIAL = "industrial";
    public static final String WINDOW = "Window";
    public static final String ROOM_WISE_WINDOW_AREA = "Room Wise Window Area";
    public static final String DOOR_VENTILATION = "Door Ventilation";
    public static final String ROOM = "Room";
    public static final String ADDITIONAL_FEATURE = "AdditionalFeature";
    public static final String BPA = "BPA";

    // Private constructor to prevent instantiation
    private MdmsFeatureConstants() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}
