spring.application.name=refund-services

#rest config
server.port=8280
server.context-path=/refund-services
server.servlet.context-path=/refund-services
logging.level.org.egov=DEBUG

#db config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jackson.serialization.write-dates-as-timestamps=false

#flyway config
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.outOfOrder=true
#spring.flyway.table=collection_services_schema_version
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.locations=classpath:db/migration/main
spring.flyway.enabled=true
spring.flyway.validateOnMigrate=false

spring.jpa.show-sql=true


refund.receipts.search.paginate=true
refund.receipts.search.default.size=30
refund.receipts.search.max.size=200
refund.is.user.create.enabled=true


#kafka server config
spring.kafka.bootstrap.servers=localhost:9092

logging.pattern.console=%clr(%X{CORRELATION_ID:-}) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

# KAFKA CONSUMER CONFIGURATIONS
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=100
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.egov.tracer.kafka.deserializer.HashMapDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=collection-persist
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.properties.spring.json.use.type.headers=false



# KAFKA PRODUCER CONFIGURATIONS
spring.kafka.producer.retries=0
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


refund.workflow.send-to-finance=true

user.service.host=http://egov-user:8080/
egov.services.user_by_id=user/_search
egov.user.create.user=user/users/_createnovalidate
egov.services.user.get_user_details=user/_details?access_token=
egov.services.user.get_user_by_username=user/_search

# PG Service
pg.service.host=http://egov-pg-service:8080
pg.initiate.refund.endpoint=/refund/v1/_initiate

workflow.wf-host=http://egov-workflow-v2:8080/
workflow.wf-transition-path=egov-workflow-v2/egov-wf/process/_transition

idgen.host=http://egov-idgen:8080
idgen.endpoint=/egov-idgen/id/_generate
refund.idgen.name=refund.id
refund.idgen.format=REFUND-[CITY]-[SEQ]

egov.refund.finance-topic=egov.refund.finance.process

egov.system.user.uuid=a8f53ede-ca6d-48a3-a5ed-44b3e0f69963
