
ALTER TABLE eg_fm_applicantdocuments_log RENAME TO eg_fm_applicantdocument_log;

ALTER TABLE eg_fm_applicantservicedocuments_log RENAME TO eg_fm_applicantservicedocument_log;

ALTER TABLE eg_fm_filedetails_log RENAME TO eg_fm_filedetail_log;

ALTER TABLE eg_fm_servicedetails_log RENAME TO eg_fm_servicedetail_log;