module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: {
    enabled: process.env.NODE_ENV === "production",
    content: ["./example/index.html", "./src/**/*.scss"],
  },
  theme: {
    screens: {
      dt: "780px",
    },
    spacing: {
      sm: "8px",
      md: "16px",
      lg: "24px",
      xl: "32px",
      "2xl": "40px",
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "8": "32px",
      "10": "40px",
      "12": "48px",
      "1/2": "50%",
      "1/3": "33.333333%",
      "1/4": "25%",
      "3/4": "75%",
      full: "100%",
    },
    colors: {
      primary: {
        light: "#F18F5E",
        main: "#a82227",
        dark: "#C8602B",
      },
      secondary: "#22394D",
      text: {
        primary: "#0B0C0C",
        secondary: "#505A5F",
      },
      link: {
        normal: "#1D70B8",
        hover: "#003078",
      },
      border: "#D6D5D4",
      "input-border": "#464646",
      focus: "#a82227",
      error: "#D4351C",
      success: "#00703C",
      black: "#000000",
      grey: {
        dark: "#9E9E9E",
        mid: "#EEEEEE",
        light: "#FAFAFA",
        bg: "#E3E3E3",
      },
      white: "#FFFFFF",
    },
    fontFamily: {
      sans: ["Roboto", "sans-serif"],
      rc: ['"Roboto Condensed"', "sans-serif"],
    },
    extend: {},
  },
  variants: {},
  plugins: [],
};
