ALTER TABLE public.eg_ss_category
ALTER COLUMN id TYPE VARCHAR(1000),
ALTER COLUMN "label" TYPE VARCHAR(1000),
ALTER COLUMN tenantid TYPE VARCHAR(1000),
ALTER COLUMN createdby TYPE VARCHAR(1000),
ALTER COLUMN lastmodifiedby TYPE VARCHAR(1000);

ALTER TABLE public.eg_ss_question
ALTER COLUMN "uuid" TYPE VARCHAR(1000),
ALTER COLUMN surveyid TYPE VARCHAR(1000),
ALTER COLUMN questionstatement TYPE VARCHAR(1000),
ALTER COLUMN "options" TYPE VARCHAR(10000),
ALTER COLUMN "type" TYPE VARCHAR(1000),
ALTER COLUMN status TYPE VARCHAR(1000),
ALTER COLUMN createdby TYPE VARCHAR(1000),
ALTER COLUMN lastmodifiedby TYPE VARCHAR(1000),
ALTER COLUMN categoryid TYPE VARCHAR(1000),
ALTER COLUMN tenantid TYPE VARCHAR(1000);

ALTER TABLE public.eg_ss_answer
ALTER COLUMN "uuid" TYPE VARCHAR(1000),
ALTER COLUMN questionuuid TYPE VARCHAR(1000),
ALTER COLUMN surveyuuid TYPE VARCHAR(1000),
ALTER COLUMN answer TYPE VARCHAR(1000),
ALTER COLUMN createdby TYPE VARCHAR(1000),
ALTER COLUMN lastmodifiedby TYPE VARCHAR(1000),
ALTER COLUMN citizenid TYPE VARCHAR(1000),
ALTER COLUMN sectionuuid TYPE VARCHAR(1000),
ALTER COLUMN "comments" TYPE VARCHAR(1000),
ALTER COLUMN city TYPE VARCHAR(1000);

ALTER TABLE public.eg_ss_question_weightage
ALTER COLUMN questionuuid TYPE VARCHAR(1000),
ALTER COLUMN sectionuuid TYPE VARCHAR(1000);

ALTER TABLE public.eg_ss_survey_entity
ALTER COLUMN "uuid" TYPE VARCHAR(1000),
ALTER COLUMN tenantid TYPE VARCHAR(1000),
ALTER COLUMN title TYPE VARCHAR(1000),
ALTER COLUMN category TYPE VARCHAR(1000),
ALTER COLUMN description TYPE VARCHAR(1000),
ALTER COLUMN postedby TYPE VARCHAR(1000),
ALTER COLUMN createdby TYPE VARCHAR(1000),
ALTER COLUMN lastmodifiedby TYPE VARCHAR(1000);

ALTER TABLE public.eg_ss_survey_section
ALTER COLUMN "uuid" TYPE VARCHAR(1000),
ALTER COLUMN surveyuuid TYPE VARCHAR(1000),
ALTER COLUMN title TYPE VARCHAR(1000);