-- =============================================================================
-- Migration: V20260713050754__add_scheduler_tables
-- Description: Creates tables for the adapter-service ingestion pipeline.
--
-- This migration introduces three database tables:
--   1. ingestion_module_detail      — ULB-module configuration (FK target)
--   2. ingestion_detail             — daily ingestion audit records
--   3. legacy_data_ingestion_detail — legacy (monthly) ingestion audit records
--
-- Dependencies:
--   - ingestion_module_detail must be created first since both
--     ingestion_detail and legacy_data_ingestion_detail have a foreign key
--     referencing it via module_detail_id.
-- =============================================================================

-- =============================================================================
-- Table 1: ingestion_module_detail
-- Description: Configuration / schedule record for a specific ULB-module
-- combination. Each row defines the ingestion schedule, legacy migration
-- status, and the last data point that was successfully ingested.
--
-- Referenced by:
--   ingestion_detail.module_detail_id
--   legacy_data_ingestion_detail.module_detail_id
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_module_detail (
    detail_id                   VARCHAR(64)     NOT NULL,
    tenant_id                   VARCHAR(64)     NOT NULL,
    ulb_name                    VARCHAR(256)    NOT NULL,
    module_name                 VARCHAR(64)     NOT NULL,
    is_active                   BOOLEAN         NOT NULL DEFAULT TRUE,
    is_legacy_data_ingested     BOOLEAN         NOT NULL DEFAULT FALSE,
    last_ingested_date          DATE,
    schedule_cron               VARCHAR(128),
    created_by                  VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    created_time                BIGINT          NOT NULL,
    last_modified_by            VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    last_modified_time          BIGINT          NOT NULL,
    CONSTRAINT pk_ingestion_module_detail PRIMARY KEY (detail_id)
);

-- Index for looking up active module configurations by tenant and module name.
CREATE INDEX IF NOT EXISTS idx_ingestion_module_detail_tenant_module
    ON ingestion_module_detail (tenant_id, module_name)
    WHERE is_active = TRUE;

COMMENT ON TABLE ingestion_module_detail IS
    'Configuration and schedule metadata for each ULB-module ingestion stream.';
COMMENT ON COLUMN ingestion_module_detail.detail_id IS
    'Primary key — UUID generated by the application layer.';
COMMENT ON COLUMN ingestion_module_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB (e.g. pg.citya).';
COMMENT ON COLUMN ingestion_module_detail.ulb_name IS
    'Human-readable name of the Urban Local Body.';
COMMENT ON COLUMN ingestion_module_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_module_detail.is_active IS
    'Whether this ULB-module combination is currently scheduled for ingestion.';
COMMENT ON COLUMN ingestion_module_detail.is_legacy_data_ingested IS
    'Whether historical (legacy) data has been fully ingested for this module.';
COMMENT ON COLUMN ingestion_module_detail.last_ingested_date IS
    'The most recent date for which daily data was successfully ingested.';
COMMENT ON COLUMN ingestion_module_detail.schedule_cron IS
    'Cron expression defining the ingestion schedule. NULL if not scheduled.';


-- =============================================================================
-- Table 2: ingestion_detail
-- Description: One row per daily ingestion push attempt. Captures the full
-- request and response JSON so failures can be diagnosed without re-fetching
-- source data.
--
-- Mapped from Java entity:
--   org.upyog.adapter.entity.DailyIngestionData
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingestion_detail (
    module_ingestion_id         VARCHAR(64)     NOT NULL,
    module_detail_id            VARCHAR(64),
    tenant_id                   VARCHAR(64),
    module_name                 VARCHAR(64),
    push_date                   DATE,
    request_data                JSONB,
    response_data               JSONB,
    ingestion_status            VARCHAR(32),
    created_by                  VARCHAR(256),
    created_time                BIGINT,
    last_modified_by            VARCHAR(256),
    last_modified_time          BIGINT,
    CONSTRAINT pk_ingestion_detail PRIMARY KEY (module_ingestion_id),
    CONSTRAINT fk_ingestion_detail_module_detail
        FOREIGN KEY (module_detail_id)
        REFERENCES ingestion_module_detail (detail_id)
        ON DELETE SET NULL
);

-- Index to quickly find recent ingestion attempts for a given ULB and module.
CREATE INDEX IF NOT EXISTS idx_ingestion_detail_tenant_module_date
    ON ingestion_detail (tenant_id, module_name, push_date DESC);

-- Index to find failed records that may need retry.
CREATE INDEX IF NOT EXISTS idx_ingestion_detail_status
    ON ingestion_detail (ingestion_status)
    WHERE ingestion_status IN ('FAILURE', 'NOT_STARTED');

COMMENT ON TABLE ingestion_detail IS
    'Audit log of every daily ingestion push attempt to the National Dashboard.';
COMMENT ON COLUMN ingestion_detail.module_ingestion_id IS
    'Primary key — UUID generated by HttpLoader before pushing to Kafka.';
COMMENT ON COLUMN ingestion_detail.module_detail_id IS
    'Foreign key referencing ingestion_module_detail.detail_id.';
COMMENT ON COLUMN ingestion_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB whose data was pushed.';
COMMENT ON COLUMN ingestion_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_detail.push_date IS
    'Calendar date for which the module data was pushed.';
COMMENT ON COLUMN ingestion_detail.request_data IS
    'Full JSON of the NationalDashboardIngestRequest sent to the dashboard.';
COMMENT ON COLUMN ingestion_detail.response_data IS
    'HTTP response body (success) or exception message (failure).';
COMMENT ON COLUMN ingestion_detail.ingestion_status IS
    'Outcome: SUCCESS or FAILURE.';


-- =============================================================================
-- Table 3: legacy_data_ingestion_detail
-- Description: One row per legacy (historical) ingestion push attempt.
-- Unlike daily records which are date-specific, legacy records cover an
-- entire calendar month (push_month represents the first day of that month).
--
-- Mapped from Java entity:
--   org.upyog.adapter.entity.LegacyIngestionData
-- =============================================================================
CREATE TABLE IF NOT EXISTS legacy_data_ingestion_detail (
    module_ingestion_id         VARCHAR(64)     NOT NULL,
    module_detail_id            VARCHAR(64),
    tenant_id                   VARCHAR(64),
    ulb_name                    VARCHAR(256),
    module_name                 VARCHAR(64),
    push_month                  DATE,
    user_id                     VARCHAR(64),
    request_data                JSONB,
    response_data               JSONB,
    ingestion_status            VARCHAR(32)     NOT NULL DEFAULT 'NOT_STARTED',
    created_by                  VARCHAR(256),
    created_time                BIGINT,
    last_modified_by            VARCHAR(256),
    last_modified_time          BIGINT,
    CONSTRAINT pk_legacy_ingestion_detail PRIMARY KEY (module_ingestion_id),
    CONSTRAINT fk_legacy_ingestion_detail_module_detail
        FOREIGN KEY (module_detail_id)
        REFERENCES ingestion_module_detail (detail_id)
        ON DELETE SET NULL
);

-- Index to find legacy records by tenant, module, and month.
CREATE INDEX IF NOT EXISTS idx_legacy_ingestion_detail_tenant_module_month
    ON legacy_data_ingestion_detail (tenant_id, module_name, push_month DESC);

-- Index to find legacy records that still need to be processed or retried.
CREATE INDEX IF NOT EXISTS idx_legacy_ingestion_detail_status
    ON legacy_data_ingestion_detail (ingestion_status)
    WHERE ingestion_status IN ('NOT_STARTED', 'FAILURE');

COMMENT ON TABLE legacy_data_ingestion_detail IS
    'Audit log of every legacy (historical monthly) ingestion push attempt.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_ingestion_id IS
    'Primary key — UUID generated by the legacy ingestion scheduler.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_detail_id IS
    'Foreign key referencing ingestion_module_detail.detail_id.';
COMMENT ON COLUMN legacy_data_ingestion_detail.tenant_id IS
    'DIGIT tenant identifier for the ULB whose data was pushed.';
COMMENT ON COLUMN legacy_data_ingestion_detail.ulb_name IS
    'Name of the Urban Local Body whose legacy data was ingested.';
COMMENT ON COLUMN legacy_data_ingestion_detail.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN legacy_data_ingestion_detail.push_month IS
    'First day of the calendar month for which legacy data was pushed (e.g. 2023-04-01).';
COMMENT ON COLUMN legacy_data_ingestion_detail.user_id IS
    'Identifier of the user or system that triggered the legacy ingestion.';
COMMENT ON COLUMN legacy_data_ingestion_detail.request_data IS
    'Full JSON of the NationalDashboardIngestRequest sent to the dashboard.';
COMMENT ON COLUMN legacy_data_ingestion_detail.response_data IS
    'HTTP response body (success) or exception message (failure).';
COMMENT ON COLUMN legacy_data_ingestion_detail.ingestion_status IS
    'Outcome: NOT_STARTED (default), SUCCESS, or FAILURE.';
