-- =============================================================================
-- Migration: V20260720113000__add_ingestion_module_summary_table
-- Description: Creates ingestion_module_summary table to track the latest
--              successful data ingestion date for each tenant and module.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ingestion_module_summary (
    id                          VARCHAR(64)     NOT NULL,
    tenant_id                   VARCHAR(64)     NOT NULL,
    module_name                 VARCHAR(64)     NOT NULL,
    last_successful_date        DATE            NOT NULL,
    created_by                  VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    created_time                BIGINT          NOT NULL,
    last_modified_by            VARCHAR(256)    NOT NULL DEFAULT 'SYSTEM',
    last_modified_time          BIGINT          NOT NULL,
    CONSTRAINT pk_ingestion_module_summary PRIMARY KEY (id),
    CONSTRAINT uk_ingestion_module_summary_tenant_module UNIQUE (tenant_id, module_name)
);

CREATE INDEX IF NOT EXISTS idx_ingestion_module_summary_tenant_module
    ON ingestion_module_summary (tenant_id, module_name);

COMMENT ON TABLE ingestion_module_summary IS
    'Tracks the latest successful ingestion push date per tenant and module.';
COMMENT ON COLUMN ingestion_module_summary.id IS
    'Primary key — UUID generated by the application layer.';
COMMENT ON COLUMN ingestion_module_summary.tenant_id IS
    'DIGIT tenant identifier for the ULB (e.g. pg.citya or state code pg).';
COMMENT ON COLUMN ingestion_module_summary.module_name IS
    'Short code identifying the DIGIT module (e.g. PT, TL, FSM).';
COMMENT ON COLUMN ingestion_module_summary.last_successful_date IS
    'The most recent calendar date for which metrics were successfully ingested.';
